// "oksidlar" toifasi tajribalarini yasaydi: frontend/lab/data/reactions/oksidlar.json
// Ishga tushirish: node tools/seed/reactions/oksidlar.mjs
// Cho'kma rangi/teksturasi va gaz rangi/hidi bazadan (substances.json) olinadi.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const DATA = join(ROOT, 'frontend', 'lab', 'data');
const S = JSON.parse(readFileSync(join(DATA, 'substances.json'), 'utf8'));
const CAT = 'oksidlar';
const PREFIX = 'oksid';

const sub = (id) => { if (!S[id]) throw new Error(`modda yo'q: ${id}`); return S[id]; };
const ppt = (id) => { const s = sub(id); return { species: id, color: s.precipitate?.color || s.appearance?.color, texture: s.precipitate?.texture || 'mayda-kristall' }; };
const gas = (id) => { const s = sub(id); return { species: id, color: s.gas?.color ?? null, smell_uz: s.gas?.smell_uz ?? null }; };
const aq = (species, conc_M, volume_mL, extra = {}) => ({ species, state: 'aq', conc_M, volume_mL, ...extra });
const solid = (species, mass_g, form = 'kukun', extra = {}) => ({ species, state: 's', mass_g, form, ...extra });
const gasR = (species, extra = {}) => ({ species, state: 'g', ...extra });
const water = (volume_mL = 5) => ({ species: 'H2O', state: 'l', volume_mL });
const ind = (species, volume_mL = 0.5) => ({ species, state: 'aq', volume_mL });
const fenolftalein = { species: 'C20H14O4', state: 'aq', conc_M: 0.03, volume_mL: 0.2 };

// eritma ranglari (ions.json dagi qiymatlar)
const C = {
  rangsiz: '#ffffff', cu: '#4aa3dc', fe3: '#d39a2a', fe2: '#c9e6b4',
  lakmusB: '#8a4fb3', lakmusQ: '#d42a3a', fenolQ: '#d81b8c', univN: '#7cc23a', univI: '#3b1f6e',
};

function R(o) {
  return {
    id: null,
    category: CAT,
    title_uz: o.t,
    level: o.lvl,
    topic_uz: o.topic,
    engine: o.engine || 'rules',
    ...(o.nr ? { no_reaction: true, match: o.match } : {}),
    reactants: o.re,
    conditions: {
      heating: !!o.heat_c,
      temp_min_C: o.tmin ?? null,
      ...(o.tmax ? { temp_max_C: o.tmax } : {}),
      catalyst: null,
      medium: o.medium ?? null,
      light: false,
      note_uz: o.note ?? null,
    },
    equation: { molecular: o.mol ?? null, ionic_full: o.full ?? null, ionic_net: o.net ?? null, electron_balance: o.eb ?? null },
    mechanism: { type: o.mech, steps_uz: o.steps, organic: null },
    observations: {
      precipitate: o.ppt ? ppt(o.ppt) : null,
      gas: o.gas ? gas(o.gas) : null,
      solution_color_change: o.col ? { from: o.col[0], to: o.col[1] } : null,
      heat: o.heat,
      flame: null,
      effects: (o.fx || []).map((type) => ({ type })),
      text_uz: o.obs,
    },
    kinetics: o.kin,
    apparatus: o.app,
    procedure_uz: o.proc,
    safety_uz: o.safe,
    explanation_uz: o.expl,
    questions_uz: o.q,
    confidence: o.conf || 'yuqori',
  };
}

const T_BASIC = "Asosli oksidlarning xossalari";
const T_ACID = "Kislotali oksidlarning xossalari";
const T_AMF = "Amfoter oksidlarning xossalari";
const T_OXOX = "Oksidlarning o'zaro ta'siri";
const SAFE_ALK = "Ishqor eritmasi teri va ko'zni yemiradi; himoya ko'zoynagi va qo'lqopdan foydalaning.";
const SAFE_FUSE = "Suyuqlanma juda issiq va o'yuvchi: himoya ko'zoynagi, qo'lqop va tigel qisqichidan foydalaning, tigelga engashmang. Ishqor suyuqlanmasi chinni va shishani yemiradi — temir yoki nikel tigel ishlatiladi.";
const FUSE_NOTE_NAOH = "Aralashma tigelda kuchli qizdirib suyuqlantiriladi (NaOH 318 °C da suyuqlanadi); harorat chegarasi taxminiy.";
const FUSE_NOTE_NA2CO3 = "Aralashma mufel pechida yuqori haroratda suyuqlantiriladi (Na2CO3 851 °C da suyuqlanadi); harorat chegarasi taxminiy.";

const list = [
  // ------------------------------------------------------------ oksid + suv
  R({
    t: "Kalsiy oksidning suv bilan reaksiyasi (ohakni so'ndirish)", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('CaO', 1, "bo'lak"), water(5), fenolftalein],
    mol: 'CaO + H2O = Ca(OH)2', full: 'CaO + H2O = Ca²⁺ + 2OH⁻', net: 'CaO + H2O = Ca²⁺ + 2OH⁻',
    mech: 'birikish', steps: [
      "Oksid ioni O²⁻ suv molekulasidan protonni tortib oladi: O²⁻ + H2O → 2OH⁻.",
      "Ca²⁺ va OH⁻ ionlaridan kalsiy gidroksid (so'ndirilgan ohak) hosil bo'ladi.",
      "Ca(OH)2 suvda kam eriydi: bir qismi eritmaga o'tadi, qolgani oq bo'tqa (ohak suti) holida qoladi.",
    ],
    heat: 'kuchli-ekzotermik', fx: ['heat-haze', 'turbidity'], col: [C.rangsiz, C.fenolQ],
    obs: "Kesak qiziydi, bug' chiqadi va oq kukunga sochilib ketadi; oq loyqa suyuqlik hosil bo'ladi. Fenolftalein to'q pushti (malina) rangga kiradi.",
    kin: 'tez', app: ['chinni-kosacha', 'tomizgich', 'shisha-tayoqcha'],
    proc: [
      "Chinni kosachaga bir bo'lak kalsiy oksid (so'ndirilmagan ohak) qo'ying.",
      "Tomizgich bilan ustiga oz-ozdan suv tomizing va o'zgarishlarni kuzating.",
      "Hosil bo'lgan bo'tqaga yana suv qo'shib, shisha tayoqcha bilan aralashtiring.",
      "Aralashmaga 1–2 tomchi fenolftalein tomizing va rangini kuzating.",
    ],
    safe: "Reaksiya kuchli issiqlik chiqaradi, suyuqlik sachrashi mumkin: kosachaga engashmang, ko'zoynak taqing. Ohak terini quritadi va ko'zga juda xavfli.",
    expl: "Kalsiy oksid asosli oksid bo'lib, suv bilan birikib asos — kalsiy gidroksid hosil qiladi. Reaksiya ko'p issiqlik chiqaradi, shuning uchun suv qaynab bug'lanadi. Eritma ishqoriy muhitga ega bo'lgani uchun fenolftalein pushti rangga bo'yaladi.",
    q: ["Nima uchun bu jarayon 'ohakni so'ndirish' deyiladi?", "Qaysi metallarning oksidlari suv bilan ishqor hosil qiladi?", "Ohak suti va ohakli suvning farqi nimada?"],
  }),
  R({
    t: "Natriy oksidning suv bilan reaksiyasi", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('Na2O', 0.2), water(5), fenolftalein],
    mol: 'Na2O + H2O = 2NaOH', full: 'Na2O + H2O = 2Na⁺ + 2OH⁻', net: 'Na2O + H2O = 2Na⁺ + 2OH⁻',
    mech: 'birikish', steps: [
      "Na2O kristallidagi O²⁻ ioni suvdan proton oladi va ikki OH⁻ ioni hosil bo'ladi.",
      "Na⁺ ionlari gidratlanib eritmaga o'tadi — natriy gidroksid eritmasi hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.fenolQ],
    obs: "Oq kukun shiddat bilan eriydi, probirka isiydi. Fenolftalein qo'shilganda eritma to'q pushti rangga kiradi.",
    kin: 'tez', app: ['probirka', 'shpatel', 'tomizgich'],
    proc: [
      "Probirkaga 5 ml suv quying.",
      "Shpatel uchida ozroq natriy oksid kukunini soling va probirkani silkiting.",
      "Probirka devorini ushlab haroratni sezing.",
      "Eritmaga 1–2 tomchi fenolftalein tomizing.",
    ],
    safe: "Natriy oksid va hosil bo'lgan ishqor o'yuvchi; kukunni qo'l bilan ushlamang, ko'zoynak va qo'lqopdan foydalaning.",
    expl: "Ishqoriy metall oksidlari suv bilan shiddatli reaksiyaga kirishib ishqor hosil qiladi. Eritmada OH⁻ ionlari ko'p bo'lgani uchun muhit kuchli ishqoriy, fenolftalein pushti rangga kiradi.",
    q: ["Na2O qaysi turdagi oksid?", "Natriy oksidning suv bilan reaksiyasi tenglamasini yozing va hosil bo'lgan moddani nomlang."],
  }),
  R({
    t: "Kaliy oksidning suv bilan reaksiyasi va universal indikator", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('K2O', 0.2), water(5), ind('universal-indikator')],
    mol: 'K2O + H2O = 2KOH', full: 'K2O + H2O = 2K⁺ + 2OH⁻', net: 'K2O + H2O = 2K⁺ + 2OH⁻',
    mech: 'birikish', steps: [
      "K2O dagi O²⁻ ioni suv molekulasidan proton tortib oladi.",
      "Ikki gidroksid ioni va kaliy ionlari eritmaga o'tadi — kaliy gidroksid (o'yuvchi kaliy) hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.univN, C.univI],
    obs: "Kukun tez eriydi, eritma isiydi. Universal indikator yashil rangdan to'q binafsha rangga o'tadi (pH 13–14).",
    kin: 'tez', app: ['probirka', 'shpatel', 'tomizgich'],
    proc: [
      "Probirkaga 5 ml suv va 2–3 tomchi universal indikator qo'shing.",
      "Shpatel uchida ozroq kaliy oksid soling va silkiting.",
      "Indikator rangini shkala bilan solishtirib, pH ni aniqlang.",
    ],
    safe: SAFE_ALK,
    expl: "Kaliy oksid ishqoriy metall oksidi bo'lgani uchun suv bilan kuchli asos KOH hosil qiladi. Universal indikatorning to'q binafsha rangi kuchli ishqoriy muhitni ko'rsatadi.",
    q: ["Universal indikator kuchli ishqoriy muhitda qanday rangga kiradi?", "K2O va Na2O ning suv bilan reaksiyalari nimasi bilan o'xshash?"],
  }),
  R({
    t: "Bariy oksidning suv bilan reaksiyasi (barit suvi olish)", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('BaO', 0.3), water(10), fenolftalein],
    mol: 'BaO + H2O = Ba(OH)2', full: 'BaO + H2O = Ba²⁺ + 2OH⁻', net: 'BaO + H2O = Ba²⁺ + 2OH⁻',
    mech: 'birikish', steps: [
      "BaO dagi O²⁻ ioni suvdan proton olib ikkita OH⁻ ioniga aylanadi.",
      "Ba²⁺ va OH⁻ ionlari eritmaga o'tadi — bariy gidroksid (barit suvi) hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.fenolQ],
    obs: "Oq kukun issiqlik chiqarib eriydi. Fenolftalein qo'shilganda eritma to'q pushti rangga kiradi.",
    kin: 'tez', app: ['probirka', 'shpatel', 'tomizgich'],
    proc: [
      "Probirkaga 10 ml suv quying.",
      "Shpatel uchida ozroq bariy oksid soling va yaxshilab silkiting.",
      "Eritmaga 1–2 tomchi fenolftalein tomizib rangini kuzating.",
    ],
    safe: "Bariy birikmalari zaharli, BaO va Ba(OH)2 o'yuvchi: qo'lqop va ko'zoynak taqing, moddani og'izga tekkizmang, tajribadan so'ng qo'lni yuving.",
    expl: "Ishqoriy-yer metallaridan bariy oksidi suv bilan oson birikib, suvda yaxshi eriydigan kuchli asos Ba(OH)2 hosil qiladi. Uning eritmasi 'barit suvi' deb ataladi va CO2 ni aniqlashda ishlatiladi.",
    q: ["Barit suvi qanday maqsadda ishlatiladi?", "BaO, CaO va MgO ning suvga munosabatini solishtiring."],
  }),
  R({
    t: "Magniy oksidning issiq suv bilan sekin reaksiyasi", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('MgO', 0.2), { ...water(5), excess: true }],
    heat_c: true, tmin: 90, note: "Aralashma uzoq vaqt qaynatiladi; sovuq suvda reaksiya deyarli sezilmaydi.",
    mol: 'MgO + H2O = Mg(OH)2', full: null, net: null,
    mech: 'birikish', steps: [
      "MgO kristall panjarasi mustahkam, shuning uchun O²⁻ ionlari suv bilan faqat sirtda va sekin ta'sirlashadi.",
      "Qizdirilganda sirtda Mg(OH)2 qatlami hosil bo'ladi.",
      "Mg(OH)2 suvda juda kam eriydi, shuning uchun eritma kuchsiz ishqoriy bo'ladi.",
    ],
    heat: 'sezilarsiz', fx: ['boil', 'turbidity'],
    obs: "Oq kukun ko'rinishidan deyarli o'zgarmaydi, suyuqlik loyqa bo'lib qoladi; reaksiya juda sekin boradi.",
    kin: 'juda-sekin', app: ['probirka', 'probirka-qisqichi', 'spirt-lampasi', 'shpatel'],
    proc: [
      "Probirkaga ozroq magniy oksid kukuni soling va 5 ml suv quying.",
      "Probirkani qisqich bilan ushlab, bir necha daqiqa qaynatib turing.",
      "Sovigach, loyqa suyuqlikni kuzating; indikator qo'shib muhitni tekshirish mumkin.",
    ],
    safe: "Qaynayotgan suyuqlik sachrashi mumkin: probirka og'zini o'zingizga va boshqalarga qaratmang.",
    expl: "Magniy oksid asosli oksid, lekin u kalsiy va bariy oksidlaridan farqli ravishda suv bilan juda sekin, faqat qizdirilganda ta'sirlashadi. Hosil bo'ladigan Mg(OH)2 suvda deyarli erimaydi, shuning uchun eritma ishqoriyligi kuchsiz.",
    q: ["Nima uchun MgO suv bilan CaO ga qaraganda sekin reaksiyaga kirishadi?", "Mg(OH)2 ishqor hisoblanadimi?"],
  }),
  R({
    t: "Fosfor(V) oksidning suv bilan reaksiyasi va lakmus", lvl: '8-sinf', topic: T_ACID,
    re: [solid('P2O5', 0.2), water(5), ind('lakmus')],
    mol: 'P2O5 + 3H2O = 2H3PO4',
    mech: 'birikish', steps: [
      "P2O5 molekulasidagi musbat qutblangan fosfor atomlariga suv molekulasining kislorodi birikadi.",
      "P–O–P ko'priklari uziladi va protonlar ko'chib o'tib ortofosfat kislota H3PO4 hosil bo'ladi.",
      "H3PO4 eritmada qisman dissotsilanib H⁺ ionlarini beradi — lakmus qizaradi.",
    ],
    heat: 'kuchli-ekzotermik', fx: ['heat-haze', 'dissolve'], col: [C.lakmusB, C.lakmusQ],
    obs: "Oq kukun vishillab eriydi, eritma isiydi. Binafsha rangli lakmus qizil rangga o'tadi.",
    kin: 'tez', app: ['probirka', 'shpatel', 'tomizgich'],
    proc: [
      "Probirkaga 5 ml suv quying va 2–3 tomchi lakmus qo'shing.",
      "Shpatel uchida juda oz fosfor(V) oksid soling (ko'p solmang!).",
      "O'zgarishlarni va lakmus rangini kuzating.",
    ],
    safe: "P2O5 suvni shiddat bilan tortib oladi va terini kuydiradi; uni quruq shpatel bilan, oz miqdorda oling, ko'zoynak va qo'lqop taqing.",
    expl: "Fosfor(V) oksid kislotali oksid bo'lib, suv bilan birikib ortofosfat kislota hosil qiladi. Reaksiya ko'p issiqlik chiqaradi, shuning uchun P2O5 kuchli qurituvchi modda sifatida ishlatiladi. Kislotali muhitda lakmus qizil rangga kiradi.",
    q: ["Nima uchun P2O5 gazlarni quritishda ishlatiladi?", "Kislotali oksidni suvda eritilganda lakmus qanday rangga kiradi?"],
  }),
  R({
    t: "Oltingugurt(VI) oksidning suv bilan reaksiyasi", lvl: '9-sinf', topic: T_ACID,
    re: [solid('SO3', 0.2, 'kristall'), water(5)],
    mol: 'SO3 + H2O = H2SO4', full: 'SO3 + H2O = 2H⁺ + SO4²⁻', net: 'SO3 + H2O = 2H⁺ + SO4²⁻',
    mech: 'birikish', steps: [
      "Suv molekulasining kislorod atomi SO3 dagi elektron yetishmaydigan oltingugurt atomiga birikadi.",
      "Proton ko'chishi natijasida sulfat kislota hosil bo'ladi.",
      "H2SO4 kuchli kislota sifatida eritmada H⁺ va SO4²⁻ ionlariga ajraladi.",
    ],
    heat: 'kuchli-ekzotermik', fx: ['fog', 'heat-haze'],
    obs: "Oq kristallar suv bilan shiddat bilan, vishillab reaksiyaga kirishadi; ustida oq tuman (sulfat kislota tomchilari) paydo bo'ladi, eritma qiziydi.",
    kin: 'bir-zumda', app: ['probirka', 'shpatel', 'probirka-shtativi'],
    proc: [
      "Tajriba o'qituvchi tomonidan mo'rili shkafda ko'rsatiladi.",
      "Probirkaga 5 ml suv quying va shtativga o'rnating.",
      "Shpatel bilan juda oz miqdorda SO3 kristallaridan soling.",
      "Hosil bo'lgan tuman va eritma isishini kuzating.",
    ],
    safe: "SO3 juda o'yuvchi, havodagi namlik bilan sulfat kislota tumanini hosil qiladi: faqat mo'rili shkafda, ko'zoynak, qo'lqop va xalatda ishlang.",
    expl: "Oltingugurt(VI) oksid kislotali oksid bo'lib, suv bilan birikib sulfat kislota hosil qiladi. Reaksiya juda ko'p issiqlik chiqargani uchun sanoatda SO3 suvga emas, konsentrlangan sulfat kislotaga yuttiriladi (oleum hosil bo'ladi).",
    q: ["Nima uchun sanoatda SO3 suvga emas, sulfat kislotaga yuttiriladi?", "SO3 va SO2 ning suv bilan reaksiyasi mahsulotlarini solishtiring."],
  }),
  R({
    t: "Oltingugurt(IV) oksidning suvda erishi va lakmus", lvl: '9-sinf', topic: T_ACID,
    re: [gasR('SO2'), water(5), ind('lakmus')],
    mol: 'SO2 + H2O = H2SO3',
    mech: 'birikish', steps: [
      "SO2 molekulasi suv bilan birikib sulfit kislota hosil qiladi (jarayon qaytar).",
      "H2SO3 o'rtacha kuchli kislota: H2SO3 ⇄ H⁺ + HSO3⁻.",
      "Eritmada H⁺ ionlari paydo bo'lgani uchun lakmus qizaradi.",
    ],
    heat: 'sezilarsiz', fx: ['bubbles'], col: [C.lakmusB, C.lakmusQ],
    obs: "Gaz pufakchalari suvda yaxshi yutiladi; binafsha lakmus qizil rangga o'tadi, eritmadan o'tkir hid keladi.",
    kin: 'tez', app: ['probirka', 'gaz-naycha-egilgan', 'probirka-yon-naychali'],
    proc: [
      "Probirkaga 5 ml suv quying va 2–3 tomchi lakmus qo'shing.",
      "Gaz olish asbobidan chiqayotgan SO2 ni gaz o'tkazgich naycha orqali suvga 1–2 daqiqa o'tkazing.",
      "Lakmus rangining o'zgarishini kuzating.",
    ],
    safe: "SO2 zaharli, nafas yo'llarini qitiqlaydi: tajribani mo'rili shkafda o'tkazing, gazni hidlamang.",
    expl: "Oltingugurt(IV) oksid kislotali oksid, u suvda yaxshi eriydi va beqaror sulfit kislota hosil qiladi. Eritmadagi H⁺ ionlari lakmusni qizil rangga bo'yaydi. Karbonat angidrid ham suv bilan xuddi shunday, lekin ancha kuchsiz kislota hosil qiladi.",
    q: ["Sulfit kislota nima uchun faqat eritmada mavjud?", "SO2 ning suvdagi eritmasini qizdirsak nima kuzatiladi?"],
  }),
  // ------------------------------------------------------------ reaksiya ketmaydigan holatlar
  R({
    t: "Kremniy(IV) oksidning suv bilan reaksiyaga kirishmasligi", lvl: '8-sinf', topic: T_ACID, engine: 'record',
    nr: true, match: ['SiO2', 'H2O'], medium: 'neytral',
    re: [solid('SiO2', 0.5, 'kukun'), water(5)],
    mech: 'fizik', steps: [
      "SiO2 — atom kristall panjarali modda: har bir Si atomi to'rtta O atomi bilan kovalent bog'langan.",
      "Suv molekulalari bu mustahkam uch o'lchamli panjarani buza olmaydi.",
    ],
    heat: 'sezilarsiz', fx: [],
    obs: "Qum (SiO2) suvda erimaydi va hech qanday o'zgarish kuzatilmaydi; lakmus rangi o'zgarmaydi.",
    kin: 'bir-zumda', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga ozroq toza qum yoki kvars kukuni soling.",
      "Ustiga 5 ml suv quyib chayqating, so'ng 1–2 tomchi lakmus qo'shing.",
      "Bir necha daqiqa kuzating.",
    ],
    safe: "Kvars changini nafas bilan olmang; kukun bilan ehtiyotkor ishlang.",
    expl: "Kremniy(IV) oksid kislotali oksid, lekin u suv bilan reaksiyaga kirishmaydi — bu kislotali oksidlar orasidagi muhim istisno. Shuning uchun silikat kislota bevosita SiO2 dan emas, silikatlarga kislota ta'sir ettirib olinadi.",
    q: ["Silikat kislotani qanday olish mumkin?", "Qaysi boshqa oksidlar suv bilan reaksiyaga kirishmaydi?"],
  }),
  R({
    t: "Mis(II) oksidning suv bilan reaksiyaga kirishmasligi", lvl: '8-sinf', topic: T_BASIC, engine: 'record',
    nr: true, match: ['CuO', 'H2O'], medium: 'neytral',
    re: [solid('CuO', 0.2), water(5), fenolftalein],
    mech: 'fizik', steps: [
      "CuO ga mos keladigan gidroksid Cu(OH)2 suvda erimaydi.",
      "Shu sababli CuO suv bilan bevosita birikmaydi; eritmada OH⁻ ionlari paydo bo'lmaydi.",
    ],
    heat: 'sezilarsiz', fx: [],
    obs: "Qora kukun suvda erimaydi, idish tubiga cho'kadi; fenolftalein rangsizligicha qoladi.",
    kin: 'bir-zumda', app: ['probirka', 'shpatel', 'tomizgich'],
    proc: [
      "Probirkaga ozroq mis(II) oksid kukuni soling.",
      "Ustiga 5 ml suv quyib yaxshilab chayqating.",
      "1–2 tomchi fenolftalein qo'shib rangini kuzating.",
    ],
    safe: "Mis birikmalari zararli: kukunni yutmang, ishdan keyin qo'lni yuving.",
    expl: "Faqat ishqoriy va ishqoriy-yer metallarining (Ca, Sr, Ba) oksidlari suv bilan reaksiyaga kirishib ishqor hosil qiladi. Erimaydigan asoslarga mos keladigan oksidlar (CuO, FeO, Fe2O3 va boshqalar) suv bilan reaksiyaga kirishmaydi, ularning gidroksidlari bilvosita — tuz eritmasiga ishqor ta'sir ettirib olinadi.",
    q: ["Cu(OH)2 ni qanday olish mumkin?", "Qaysi metallarning oksidlari suv bilan reaksiyaga kirishadi?"],
  }),
  R({
    t: "Kremniy(IV) oksidning xlorid kislota bilan reaksiyaga kirishmasligi", lvl: '9-sinf', topic: T_ACID, engine: 'record',
    nr: true, match: ['SiO2', 'H⁺'],
    re: [solid('SiO2', 0.5), aq('HCl', 2, 3)],
    mech: 'fizik', steps: [
      "Kislotali oksid kislotalarning H⁺ ionlari bilan ta'sirlashmaydi — ikkalasi ham kislotali xossaga ega.",
      "SiO2 ning atom kristall panjarasi juda mustahkam.",
    ],
    heat: 'sezilarsiz', fx: [],
    obs: "Qum xlorid kislotada erimaydi, hech qanday o'zgarish kuzatilmaydi.",
    kin: 'bir-zumda', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga ozroq qum (SiO2) soling.",
      "Ustiga 3 ml xlorid kislota quying va chayqating.",
      "Bir necha daqiqa kuzating.",
    ],
    safe: "Xlorid kislota terini qitiqlaydi va kuydiradi: ko'zoynak va qo'lqopdan foydalaning.",
    expl: "Kislotali oksidlar kislotalar bilan reaksiyaga kirishmaydi. SiO2 faqat ftorid kislota (HF) bilan ta'sirlashadi — shu sababli HF shishani yemiradi va polietilen idishda saqlanadi.",
    q: ["Qaysi kislota shishani yemiradi va nima uchun?", "SiO2 qanday moddalar bilan reaksiyaga kirishadi?"],
  }),
  // ------------------------------------------------------------ asosli oksid + kislota
  R({
    t: "Mis(II) oksidning sulfat kislotada erishi", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('CuO', 0.2), aq('H2SO4', 1, 4, { excess: true })], heat_c: true,
    note: "Reaksiyani tezlatish uchun aralashma biroz isitiladi.",
    mol: 'CuO + H2SO4 = CuSO4 + H2O', full: 'CuO + 2H⁺ + SO4²⁻ = Cu²⁺ + SO4²⁻ + H2O', net: 'CuO + 2H⁺ = Cu²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "Kislotaning H⁺ ionlari CuO sirtidagi O²⁻ ionlariga birikib suv hosil qiladi.",
      "Bo'shagan Cu²⁺ ionlari gidratlanib eritmaga o'tadi va uni ko'k rangga bo'yaydi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.cu],
    obs: "Qora kukun qizdirilganda asta-sekin eriydi, eritma ko'k rangga kiradi.",
    kin: "o'rtacha", app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga shpatel uchida mis(II) oksid soling.",
      "Ustiga 3–4 ml suyultirilgan sulfat kislota quying.",
      "Probirkani qisqich bilan ushlab, qaynatmasdan sekin isiting.",
      "Kukunning erishi va eritma rangini kuzating.",
    ],
    safe: "Sulfat kislota terini kuydiradi; isitilganda probirka og'zini o'zingizga qaratmang, ko'zoynak taqing.",
    expl: "Mis(II) oksid asosli oksid bo'lib, kislotalar bilan tuz va suv hosil qiladi. Eritmaning ko'k rangi gidratlangan Cu²⁺ ionlariga bog'liq. Bu usulda laboratoriyada mis kuporosi olinadi.",
    q: ["Eritmaning ko'k rangi qaysi zarrachaga bog'liq?", "CuO va H2SO4 reaksiyasining qisqartirilgan ionli tenglamasini yozing."],
  }),
  R({
    t: "Mis(II) oksidning xlorid kislotada erishi", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('CuO', 0.2), aq('HCl', 2, 3, { excess: true })],
    mol: 'CuO + 2HCl = CuCl2 + H2O', full: 'CuO + 2H⁺ + 2Cl⁻ = Cu²⁺ + 2Cl⁻ + H2O', net: 'CuO + 2H⁺ = Cu²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "H⁺ ionlari CuO tarkibidagi kislorod bilan suv hosil qiladi.",
      "Cu²⁺ ionlari eritmaga o'tadi; xlorid ionlari ishtirokida eritma yashil-ko'k tusga ega bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.cu],
    obs: "Qora kukun eriydi, eritma yashil-ko'k rangga kiradi.",
    kin: "o'rtacha", app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga shpatel uchida mis(II) oksid soling.",
      "Ustiga 3 ml xlorid kislota quying va chayqating.",
      "Kerak bo'lsa, biroz isiting va eritma rangini kuzating.",
    ],
    safe: "Xlorid kislota bug'lari nafas yo'llarini qitiqlaydi: ko'zoynak va qo'lqopdan foydalaning, yaxshi shamollatiladigan joyda ishlang.",
    expl: "Asosli oksid kislota bilan tuz va suv hosil qiladi. Mis(II) xlorid eritmasining rangi konsentratsiyaga bog'liq: suyultirilganda ko'k, konsentrlanganda yashil bo'ladi.",
    q: ["Nima uchun CuCl2 eritmasi CuSO4 eritmasidan rangi bilan farq qilishi mumkin?", "Bu reaksiya qaysi turga kiradi?"],
  }),
  R({
    t: "Mis(II) oksidning nitrat kislotada erishi", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('CuO', 0.2), aq('HNO3', 2, 3, { excess: true })], heat_c: true,
    note: "Suyultirilgan nitrat kislota ishlatiladi, aralashma biroz isitiladi.",
    mol: 'CuO + 2HNO3 = Cu(NO3)2 + H2O', full: 'CuO + 2H⁺ + 2NO3⁻ = Cu²⁺ + 2NO3⁻ + H2O', net: 'CuO + 2H⁺ = Cu²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "Nitrat kislotaning H⁺ ionlari CuO dagi kislorod bilan suv hosil qiladi.",
      "Misning oksidlanish darajasi o'zgarmaydi (+2), shuning uchun gaz ajralmaydi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.cu],
    obs: "Qora kukun eriydi, eritma havorang-ko'k tusga kiradi; gaz ajralmaydi.",
    kin: "o'rtacha", app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga shpatel uchida mis(II) oksid soling.",
      "Ustiga 3 ml suyultirilgan nitrat kislota quying.",
      "Biroz isitib, kukunning erishini kuzating.",
    ],
    safe: "Nitrat kislota terini sarg'aytiradi va kuydiradi: ko'zoynak va qo'lqopdan foydalaning.",
    expl: "Mis(II) oksid nitrat kislota bilan oddiy almashinish reaksiyasiga kirishadi, chunki misning oksidlanish darajasi allaqachon +2. Mis metalidan farqli ravishda bu reaksiyada azot oksidlari ajralmaydi.",
    q: ["Mis metali va mis(II) oksidning nitrat kislota bilan reaksiyalari qanday farq qiladi?", "Reaksiyaning ionli tenglamalarini yozing."],
  }),
  R({
    t: "Magniy oksidning xlorid kislotada erishi", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('MgO', 0.2), aq('HCl', 2, 4, { excess: true })],
    mol: 'MgO + 2HCl = MgCl2 + H2O', full: 'MgO + 2H⁺ + 2Cl⁻ = Mg²⁺ + 2Cl⁻ + H2O', net: 'MgO + 2H⁺ = Mg²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "H⁺ ionlari MgO dagi O²⁻ ionlari bilan suv hosil qiladi.",
      "Mg²⁺ ionlari eritmaga o'tadi — rangsiz magniy xlorid eritmasi hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'],
    obs: "Oq kukun kislotada tez eriydi, rangsiz tiniq eritma hosil bo'ladi, probirka biroz isiydi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga shpatel uchida magniy oksid soling.",
      "Ustiga 3–4 ml xlorid kislota quyib chayqating.",
      "Kukunning erishini kuzating.",
    ],
    safe: "Xlorid kislota bilan ehtiyot bo'ling: ko'zoynak va qo'lqopdan foydalaning.",
    expl: "Magniy oksid suv bilan juda sekin ta'sirlashsa ham, kislotalarda oson eriydi — bu uning asosli oksid ekanligini ko'rsatadi. Natijada tuz (MgCl2) va suv hosil bo'ladi.",
    q: ["MgO ning suv va kislotaga munosabatini solishtiring.", "Oshqozon kislotaliligini kamaytiruvchi dorilarda nima uchun MgO ishlatiladi?"],
  }),
  R({
    t: "Magniy oksidning sirka kislota bilan reaksiyasi", lvl: '10-sinf', topic: T_BASIC,
    re: [solid('MgO', 0.2), aq('CH3COOH', 2, 4, { excess: true })],
    mol: 'MgO + 2CH3COOH = (CH3COO)2Mg + H2O', full: 'MgO + 2CH3COOH = Mg²⁺ + 2CH3COO⁻ + H2O', net: 'MgO + 2CH3COOH = Mg²⁺ + 2CH3COO⁻ + H2O',
    mech: 'neytrallanish', steps: [
      "Sirka kislota kuchsiz elektrolit — eritmada asosan molekula holida bo'ladi.",
      "CH3COOH molekulalari protonini MgO dagi kislorodga beradi, suv hosil bo'ladi.",
      "Mg²⁺ va atsetat ionlari eritmada qoladi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'],
    obs: "Oq kukun sirka kislotada asta-sekin eriydi, rangsiz eritma hosil bo'ladi.",
    kin: "o'rtacha", app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga shpatel uchida magniy oksid soling.",
      "Ustiga 4 ml sirka kislota eritmasi quying va chayqating.",
      "Kukunning erish tezligini xlorid kislotadagi tajriba bilan solishtiring.",
    ],
    safe: "Sirka kislota o'tkir hidli, ko'zni qitiqlaydi: ko'zoynak taqing, bug'ini hidlamang.",
    expl: "Magniy oksid kuchli asosli xossaga ega bo'lgani uchun kuchsiz sirka kislota bilan ham reaksiyaga kirishadi. Kuchsiz kislota bo'lgani uchun reaksiya xlorid kislotaga qaraganda sekinroq boradi; ionli tenglamada sirka kislota molekula holida yoziladi.",
    q: ["Nima uchun ionli tenglamada CH3COOH molekula holida yoziladi?", "MgO ning HCl va CH3COOH da erish tezligi nima uchun farq qiladi?"],
  }),
  R({
    t: "Kalsiy oksidning xlorid kislota bilan reaksiyasi", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('CaO', 0.2), aq('HCl', 2, 4, { excess: true })],
    mol: 'CaO + 2HCl = CaCl2 + H2O', full: 'CaO + 2H⁺ + 2Cl⁻ = Ca²⁺ + 2Cl⁻ + H2O', net: 'CaO + 2H⁺ = Ca²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "Suvli eritmada CaO avval suv bilan Ca(OH)2 ga aylanadi.",
      "Gidroksid ionlari kislotaning H⁺ ionlari bilan neytrallanib suv hosil qiladi.",
      "Natijada rangsiz kalsiy xlorid eritmasi qoladi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve', 'heat-haze'],
    obs: "Oq kukun issiqlik chiqarib tez eriydi, rangsiz tiniq eritma hosil bo'ladi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga shpatel uchida kalsiy oksid soling.",
      "Ustiga oz-ozdan 3–4 ml xlorid kislota quying.",
      "Probirka isishini va kukunning erishini kuzating.",
    ],
    safe: "Reaksiya issiqlik chiqaradi, kislotani oz-ozdan qo'shing; ko'zoynak va qo'lqopdan foydalaning.",
    expl: "Kalsiy oksid asosli oksid sifatida kislota bilan tuz va suv hosil qiladi. Ohak suvga qaraganda kislotada to'liq eriydi, chunki hosil bo'lgan CaCl2 suvda yaxshi eriydi.",
    q: ["Bu reaksiyaning qisqartirilgan ionli tenglamasini yozing.", "Nima uchun reaksiya issiqlik chiqarishi bilan boradi?"],
  }),
  R({
    t: "Temir(II) oksidning sulfat kislotada erishi", lvl: '9-sinf', topic: T_BASIC,
    re: [solid('FeO', 0.2), aq('H2SO4', 1, 4, { excess: true })],
    mol: 'FeO + H2SO4 = FeSO4 + H2O', full: 'FeO + 2H⁺ + SO4²⁻ = Fe²⁺ + SO4²⁻ + H2O', net: 'FeO + 2H⁺ = Fe²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "H⁺ ionlari FeO dagi kislorod bilan suv hosil qiladi.",
      "Fe²⁺ ionlari eritmaga o'tib, uni och yashil rangga bo'yaydi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.fe2],
    obs: "Qora kukun eriydi, och yashil tusli eritma hosil bo'ladi.",
    kin: "o'rtacha", app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga shpatel uchida temir(II) oksid soling.",
      "Ustiga 4 ml suyultirilgan sulfat kislota quying va chayqating.",
      "Eritma rangini kuzating; uni uzoq havoda qoldirsangiz, sarg'ayishi mumkin.",
    ],
    safe: "Sulfat kislota terini kuydiradi: ko'zoynak va qo'lqopdan foydalaning.",
    expl: "Temir(II) oksid asosli oksid bo'lib, kislota bilan temir(II) tuzi hosil qiladi. Fe²⁺ ionlari havodagi kislorod ta'sirida asta-sekin Fe³⁺ ga oksidlanadi, shuning uchun eritma vaqt o'tishi bilan sarg'ayadi.",
    q: ["Fe²⁺ eritmasi havoda nima uchun o'zgaradi?", "FeO va Fe2O3 ning kislota bilan reaksiyalari mahsulotlari qanday farq qiladi?"],
  }),
  R({
    t: "Temir(III) oksidning xlorid kislotada erishi", lvl: '9-sinf', topic: T_BASIC,
    re: [solid('Fe2O3', 0.2), aq('HCl', 2, 5, { excess: true })], heat_c: true,
    note: "Temir(III) oksid xona haroratida sekin eriydi, shuning uchun aralashma isitiladi.",
    mol: 'Fe2O3 + 6HCl = 2FeCl3 + 3H2O', full: 'Fe2O3 + 6H⁺ + 6Cl⁻ = 2Fe³⁺ + 6Cl⁻ + 3H2O', net: 'Fe2O3 + 6H⁺ = 2Fe³⁺ + 3H2O',
    mech: 'neytrallanish', steps: [
      "Qizdirilganda H⁺ ionlari Fe2O3 sirtidagi kislorod ionlari bilan suv hosil qiladi.",
      "Fe³⁺ ionlari eritmaga o'tib, uni sariq-qo'ng'ir rangga bo'yaydi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.fe3],
    obs: "Qizil-qo'ng'ir kukun isitilganda asta-sekin eriydi, eritma sariq-qo'ng'ir rangga kiradi.",
    kin: 'sekin', app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga shpatel uchida temir(III) oksid soling.",
      "Ustiga 4–5 ml xlorid kislota quying.",
      "Probirkani qisqich bilan ushlab, qaynatmasdan isiting va eritma rangini kuzating.",
    ],
    safe: "Isitilgan xlorid kislotadan HCl bug'lari ajraladi: mo'rili shkafda ishlang, ko'zoynak taqing.",
    expl: "Temir(III) oksid kislotalar bilan temir(III) tuzlarini hosil qiladi. Eritmaning sariq-qo'ng'ir rangi Fe³⁺ ionlariga bog'liq. Bu reaksiya temir buyumlarni zangdan tozalashda ishlatiladi.",
    q: ["Zang tarkibi qanday?", "Nima uchun reaksiyani tezlatish uchun isitish kerak?"],
  }),
  R({
    t: "Temir(III) oksidning sulfat kislotada erishi", lvl: '9-sinf', topic: T_BASIC,
    re: [solid('Fe2O3', 0.2), aq('H2SO4', 1, 6, { excess: true })], heat_c: true,
    note: "Aralashma isitiladi; xona haroratida reaksiya juda sekin.",
    mol: 'Fe2O3 + 3H2SO4 = Fe2(SO4)3 + 3H2O', full: 'Fe2O3 + 6H⁺ + 3SO4²⁻ = 2Fe³⁺ + 3SO4²⁻ + 3H2O', net: 'Fe2O3 + 6H⁺ = 2Fe³⁺ + 3H2O',
    mech: 'neytrallanish', steps: [
      "Isitilganda sulfat kislotaning H⁺ ionlari oksid sirtidagi kislorodni suvga aylantiradi.",
      "Fe³⁺ ionlari eritmaga o'tadi — temir(III) sulfat hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.fe3],
    obs: "Qizil-qo'ng'ir kukun isitilganda eriydi, eritma sarg'ish tusga kiradi.",
    kin: 'sekin', app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga shpatel uchida temir(III) oksid soling.",
      "Ustiga 5–6 ml suyultirilgan sulfat kislota quying.",
      "Probirkani qisqich bilan ushlab, ehtiyotkorlik bilan isiting va o'zgarishni kuzating.",
    ],
    safe: "Isitilgan sulfat kislota sachrasa kuchli kuydiradi: probirka og'zini o'zingizga qaratmang, ko'zoynak taqing.",
    expl: "Temir(III) oksid asosli xossani namoyon qilib, kislota bilan tuz va suv hosil qiladi. Temirning oksidlanish darajasi +3 bo'lgani uchun temir(III) sulfat hosil bo'ladi.",
    q: ["Fe2O3 ning sulfat kislota bilan reaksiyasining ionli tenglamalarini yozing.", "Fe2O3 qaysi turdagi oksid?"],
  }),
  R({
    t: "Temir(II,III) oksidning xlorid kislotada erishi", lvl: '9-sinf', topic: T_BASIC, engine: 'rules',
    re: [solid('Fe3O4', 0.2), aq('HCl', 2, 5, { excess: true })], heat_c: true,
    note: "Fe3O4 (temir kuyindisi, magnetit) xlorid kislotada isitilganda eriydi.",
    mol: 'Fe3O4 + 8HCl = FeCl2 + 2FeCl3 + 4H2O', full: 'Fe3O4 + 8H⁺ + 8Cl⁻ = Fe²⁺ + 2Fe³⁺ + 8Cl⁻ + 4H2O', net: 'Fe3O4 + 8H⁺ = Fe²⁺ + 2Fe³⁺ + 4H2O',
    mech: 'neytrallanish', steps: [
      "Fe3O4 — aralash oksid: tarkibida bitta Fe²⁺ va ikkita Fe³⁺ ioni bor (FeO·Fe2O3).",
      "H⁺ ionlari to'rtta kislorod ionini suvga aylantiradi.",
      "Eritmaga ikki xil tuz — temir(II) xlorid va temir(III) xlorid o'tadi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'], col: [C.rangsiz, C.fe3],
    obs: "Qora kukun isitilganda eriydi, sariq-qo'ng'ir tusli eritma hosil bo'ladi.",
    kin: "o'rtacha", app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga shpatel uchida temir(II,III) oksid soling.",
      "Ustiga 5 ml xlorid kislota quying.",
      "Probirkani qisqich bilan ushlab isiting va kukunning erishini kuzating.",
    ],
    safe: "Isitilgan xlorid kislotadan HCl bug'lari ajraladi: mo'rili shkafda ishlang, ko'zoynak taqing.",
    expl: "Temir(II,III) oksid ikki oksidning birikmasi (FeO·Fe2O3) sifatida qaraladi, shuning uchun kislota bilan bir vaqtda temir(II) va temir(III) tuzlarini hosil qiladi. Reaksiyada temirning oksidlanish darajalari o'zgarmaydi.",
    q: ["Fe3O4 ni nima uchun aralash oksid deyiladi?", "Eritmada Fe²⁺ va Fe³⁺ ionlari borligini qanday aniqlash mumkin?"],
  }),
  R({
    t: "Kumush(I) oksidning nitrat kislotada erishi", lvl: '9-sinf', topic: T_BASIC,
    re: [solid('Ag2O', 0.2), aq('HNO3', 2, 3, { excess: true })],
    mol: 'Ag2O + 2HNO3 = 2AgNO3 + H2O', full: 'Ag2O + 2H⁺ + 2NO3⁻ = 2Ag⁺ + 2NO3⁻ + H2O', net: 'Ag2O + 2H⁺ = 2Ag⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "H⁺ ionlari Ag2O dagi kislorod bilan suv hosil qiladi.",
      "Ag⁺ ionlari eritmaga o'tadi — rangsiz kumush nitrat eritmasi hosil bo'ladi.",
    ],
    heat: 'sezilarsiz', fx: ['dissolve'],
    obs: "Qo'ng'ir-qora kukun eriydi, rangsiz tiniq eritma hosil bo'ladi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga ozroq kumush(I) oksid soling.",
      "Ustiga 3 ml suyultirilgan nitrat kislota quyib chayqating.",
      "Kukunning erishini kuzating.",
    ],
    safe: "Nitrat kislota va kumush tuzlari terini qoraytiradi va kuydiradi: qo'lqop va ko'zoynakdan foydalaning.",
    expl: "Kumush(I) oksid asosli oksid bo'lib, nitrat kislotada erib, suvda yaxshi eriydigan kumush nitrat hosil qiladi. Hosil bo'lgan Ag⁺ ionlarini xloridlar yordamida aniqlash mumkin.",
    q: ["Hosil bo'lgan eritmaga NaCl qo'shilsa nima kuzatiladi?", "Ag2O ga mos keladigan gidroksid nima uchun mavjud emas?"],
  }),
  R({
    t: "Kumush(I) oksidning xlorid kislota bilan reaksiyasi", lvl: '9-sinf', topic: T_BASIC,
    re: [solid('Ag2O', 0.2), aq('HCl', 1, 3)],
    mol: 'Ag2O + 2HCl = 2AgCl↓ + H2O', full: 'Ag2O + 2H⁺ + 2Cl⁻ = 2AgCl↓ + H2O', net: 'Ag2O + 2H⁺ + 2Cl⁻ = 2AgCl↓ + H2O',
    mech: 'ion-almashinish', steps: [
      "H⁺ ionlari Ag2O dagi kislorod bilan suv hosil qiladi.",
      "Bo'shagan Ag⁺ ionlari darhol Cl⁻ ionlari bilan erimaydigan AgCl ga birikadi.",
      "Qo'ng'ir oksid oq suzmasimon tuzga aylanadi.",
    ],
    heat: 'sezilarsiz', ppt: 'AgCl', fx: [],
    obs: "Qo'ng'ir-qora kukun o'rnida oq suzmasimon cho'kma hosil bo'ladi, eritma rangsizligicha qoladi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga ozroq kumush(I) oksid soling.",
      "Ustiga 3 ml xlorid kislota quyib chayqating.",
      "Qattiq moddaning rangi va ko'rinishi o'zgarishini kuzating.",
    ],
    safe: "Kumush birikmalari terini qoraytiradi: qo'lqopdan foydalaning, ko'zoynak taqing.",
    expl: "Asosli oksid kislota bilan tuz va suv hosil qiladi, lekin bu holda hosil bo'lgan tuz — AgCl suvda erimaydi va cho'kmaga tushadi. Shuning uchun oksid eritmaga o'tmaydi, balki oq tuzga aylanadi.",
    q: ["Nima uchun Ag2O xlorid kislotada eritma hosil qilmaydi?", "Ag2O ni eritish uchun qaysi kislotani tanlash kerak?"],
  }),
  R({
    t: "Simob(II) oksidning nitrat kislotada erishi", lvl: '9-sinf', topic: T_BASIC,
    re: [solid('HgO', 0.1), aq('HNO3', 2, 3, { excess: true })],
    mol: 'HgO + 2HNO3 = Hg(NO3)2 + H2O', full: 'HgO + 2H⁺ + 2NO3⁻ = Hg²⁺ + 2NO3⁻ + H2O', net: 'HgO + 2H⁺ = Hg²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "H⁺ ionlari HgO dagi kislorod bilan suv hosil qiladi.",
      "Hg²⁺ ionlari eritmaga o'tadi — rangsiz simob(II) nitrat eritmasi hosil bo'ladi.",
    ],
    heat: 'sezilarsiz', fx: ['dissolve'],
    obs: "To'q sariq-qizil kukun eriydi, rangsiz eritma hosil bo'ladi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Tajriba o'qituvchi tomonidan mo'rili shkafda ko'rsatiladi.",
      "Probirkaga juda oz miqdorda simob(II) oksid soling.",
      "Ustiga 3 ml suyultirilgan nitrat kislota quyib chayqating va erishini kuzating.",
    ],
    safe: "Simob birikmalari juda zaharli: faqat qo'lqopda, mo'rili shkafda ishlang; chiqindilarni maxsus idishga yig'ing, kanalizatsiyaga to'kmang.",
    expl: "Simob(II) oksid asosli oksid bo'lib, nitrat kislotada erib simob(II) nitrat hosil qiladi. Simob birikmalari zaharli bo'lgani uchun bunday tajribalar faqat namoyish sifatida o'tkaziladi.",
    q: ["HgO qizdirilganda qanday parchalanadi?", "Reaksiyaning qisqartirilgan ionli tenglamasini yozing."],
  }),
  R({
    t: "Bariy oksidning sulfat kislota bilan reaksiyasi", lvl: '8-sinf', topic: T_BASIC,
    re: [solid('BaO', 0.2), aq('H2SO4', 1, 3)],
    mol: 'BaO + H2SO4 = BaSO4↓ + H2O', full: 'BaO + 2H⁺ + SO4²⁻ = BaSO4↓ + H2O', net: 'BaO + 2H⁺ + SO4²⁻ = BaSO4↓ + H2O',
    mech: 'ion-almashinish', steps: [
      "BaO suvli eritmada Ba²⁺ va OH⁻ ionlarini beradi.",
      "OH⁻ ionlari H⁺ bilan neytrallanadi, Ba²⁺ ionlari SO4²⁻ bilan erimaydigan BaSO4 hosil qiladi.",
    ],
    heat: 'ekzotermik', ppt: 'BaSO4', fx: [],
    obs: "Oq mayda kristall cho'kma hosil bo'ladi, probirka biroz isiydi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga 3 ml suyultirilgan sulfat kislota quying.",
      "Shpatel uchida ozroq bariy oksid soling va chayqating.",
      "Hosil bo'lgan cho'kmani kuzating.",
    ],
    safe: "Bariy birikmalari zaharli: qo'lqop taqing, moddani og'izga tekkizmang, ishdan so'ng qo'lni yuving.",
    expl: "Asosli oksid kislota bilan tuz va suv hosil qiladi. Bariy sulfat suvda ham, kislotalarda ham erimaydi, shuning uchun oq cho'kma tushadi.",
    q: ["Nima uchun BaSO4 cho'kmasi kislotada erimaydi?", "BaO ning HCl bilan reaksiyasida cho'kma hosil bo'ladimi?"],
  }),
  R({
    t: "Mis(I) oksidning suyultirilgan sulfat kislota bilan reaksiyasi (disproporsiyalanish)", lvl: 'litsey', topic: T_BASIC, engine: 'record',
    re: [solid('Cu2O', 0.2), aq('H2SO4', 1, 4, { excess: true, conc_max_M: 5 })],
    mol: 'Cu2O + H2SO4 = CuSO4 + Cu + H2O', full: 'Cu2O + 2H⁺ + SO4²⁻ = Cu²⁺ + SO4²⁻ + Cu + H2O', net: 'Cu2O + 2H⁺ = Cu²⁺ + Cu + H2O',
    eb: ['Cu⁺¹ − 1e⁻ = Cu⁺²', 'Cu⁺¹ + 1e⁻ = Cu'],
    mech: 'oksidlanish-qaytarilish', steps: [
      "Kislotada Cu2O dan Cu⁺ ionlari hosil bo'ladi, lekin ular suvli eritmada beqaror.",
      "Bir Cu⁺ ioni elektron berib Cu²⁺ ga oksidlanadi.",
      "Ikkinchi Cu⁺ ioni shu elektronni olib metall misga qaytariladi — disproporsiyalanish.",
    ],
    heat: 'sezilarsiz', fx: ['deposit', 'dissolve'], col: [C.rangsiz, C.cu],
    obs: "Qizil kukun qizg'ish-qo'ng'ir mis kukuniga aylanadi, eritma esa havorang-ko'k tusga kiradi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga ozroq mis(I) oksid soling.",
      "Ustiga 4 ml suyultirilgan sulfat kislota quyib chayqating.",
      "Cho'kma rangining o'zgarishini va eritma rangini kuzating.",
    ],
    safe: "Sulfat kislota terini kuydiradi: ko'zoynak va qo'lqopdan foydalaning.",
    expl: "Mis(I) ionlari suvli eritmada beqaror va disproporsiyalanadi: bir qismi Cu²⁺ ga oksidlanadi, bir qismi metall misga qaytariladi. Shuning uchun Cu2O suyultirilgan sulfat kislotada mis(I) sulfat emas, mis(II) sulfat va mis hosil qiladi.",
    q: ["Disproporsiyalanish reaksiyasi deganda nimani tushunasiz?", "Elektron balans tuzing va oksidlovchi hamda qaytaruvchini ko'rsating."],
    conf: 'yuqori',
  }),
  // ------------------------------------------------------------ amfoter oksidlar
  R({
    t: "Rux oksidning xlorid kislotada erishi", lvl: '8-sinf', topic: T_AMF,
    re: [solid('ZnO', 0.2), aq('HCl', 2, 3, { excess: true })],
    mol: 'ZnO + 2HCl = ZnCl2 + H2O', full: 'ZnO + 2H⁺ + 2Cl⁻ = Zn²⁺ + 2Cl⁻ + H2O', net: 'ZnO + 2H⁺ = Zn²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "Kislota bilan ta'sirlashganda ZnO asos xossasini namoyon qiladi.",
      "H⁺ ionlari kislorodni suvga aylantiradi, Zn²⁺ ionlari eritmaga o'tadi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'],
    obs: "Oq kukun kislotada eriydi, rangsiz tiniq eritma hosil bo'ladi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga shpatel uchida rux oksid soling.",
      "Ustiga 3 ml xlorid kislota quyib chayqating.",
      "Kukunning erishini kuzating. Natijani ishqor bilan o'tkaziladigan tajriba bilan solishtiring.",
    ],
    safe: "Xlorid kislota bilan ehtiyot bo'ling: ko'zoynak va qo'lqopdan foydalaning.",
    expl: "Rux oksid amfoter oksid: kislotalar bilan reaksiyada asosli oksid kabi tuz va suv hosil qiladi. Uning ishqorlar bilan ham reaksiyaga kirishishi keyingi tajribada ko'rsatiladi.",
    q: ["Amfoter oksid deb qanday oksidlarga aytiladi?", "Reaksiyaning qisqartirilgan ionli tenglamasini yozing."],
  }),
  R({
    t: "Rux oksidning natriy gidroksid eritmasida erishi", lvl: '8-sinf', topic: T_AMF, engine: 'record',
    re: [solid('ZnO', 0.2), aq('NaOH', 2, 4, { excess: true })], heat_c: true,
    note: "Konsentrlanganroq ishqor eritmasi bilan biroz isitiladi.",
    mol: 'ZnO + 2NaOH + H2O = Na2[Zn(OH)4]', full: 'ZnO + 2Na⁺ + 2OH⁻ + H2O = 2Na⁺ + [Zn(OH)4]²⁻', net: 'ZnO + 2OH⁻ + H2O = [Zn(OH)4]²⁻',
    mech: 'kompleks', steps: [
      "Ishqor bilan ta'sirlashganda ZnO kislotali oksid xossasini namoyon qiladi.",
      "Zn²⁺ markaziy ioni atrofida to'rtta OH⁻ ligandi joylashib, [Zn(OH)4]²⁻ gidroksokompleks hosil bo'ladi.",
      "Kompleks ion suvda eriydi — natriy tetragidroksosinkat eritmasi hosil bo'ladi.",
    ],
    heat: 'sezilarsiz', fx: ['dissolve'],
    obs: "Oq kukun ishqor eritmasida isitilganda eriydi, rangsiz tiniq eritma hosil bo'ladi.",
    kin: "o'rtacha", app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga shpatel uchida rux oksid soling.",
      "Ustiga 4 ml natriy gidroksid eritmasi quying.",
      "Probirkani qisqich bilan ushlab, qaynatmasdan isiting va kukunning erishini kuzating.",
    ],
    safe: SAFE_ALK + " Isitilgan ishqor sachrashi mumkin — probirka og'zini o'zingizga qaratmang.",
    expl: "Rux oksid ishqor eritmalarida erib gidroksokompleks — tetragidroksosinkat hosil qiladi. Shunday qilib, ZnO ham kislotalar, ham ishqorlar bilan reaksiyaga kirishadi, ya'ni amfoter oksid hisoblanadi.",
    q: ["ZnO ning amfoterligini isbotlovchi ikki reaksiya tenglamasini yozing.", "[Zn(OH)4]²⁻ ionida markaziy ion va ligandlarni ko'rsating."],
  }),
  R({
    t: "Rux oksidning natriy gidroksid bilan suyuqlantirilishi", lvl: '8-sinf', topic: T_AMF, engine: 'record',
    re: [solid('ZnO', 0.2), solid('NaOH', 0.2, 'granula')], heat_c: true, tmin: 350, note: FUSE_NOTE_NAOH,
    mol: 'ZnO + 2NaOH = Na2ZnO2 + H2O↑',
    mech: 'neytrallanish', steps: [
      "Suyuqlanmada suv yo'q, shuning uchun kompleks emas, 'suvsiz' tuz — natriy sinkat hosil bo'ladi.",
      "ZnO bu reaksiyada kislotali oksid vazifasini bajaradi (H2ZnO2 'kislota'siga mos keladi).",
      "Hosil bo'lgan suv yuqori haroratda bug' holida chiqib ketadi.",
    ],
    heat: 'sezilarsiz', fx: ['condensate'],
    obs: "Aralashma suyuqlanadi, suv bug'i ajraladi; sovigach oq qotishma qoladi.",
    kin: 'tez', app: ['tigel', 'tigel-qisqichi', 'chinni-uchburchak', 'uchoyoq', 'bunzen-gorelkasi'],
    proc: [
      "Temir tigelga rux oksid va natriy gidroksid granulalarini soling.",
      "Tigelni chinni uchburchakka qo'yib, gorelka alangasida kuchli qizdiring.",
      "Aralashma suyuqlanib, bug' ajralishi to'xtaguncha qizdiring, so'ng sovuting.",
    ],
    safe: SAFE_FUSE,
    expl: "Suyuqlantirishda ZnO ishqor bilan suvsiz tuz — natriy sinkat Na2ZnO2 hosil qiladi. Suvli eritmada esa xuddi shu jarayon gidroksokompleks [Zn(OH)4]²⁻ hosil bo'lishi bilan boradi. Ikkala holat ham ZnO ning kislotali xossasini ko'rsatadi.",
    q: ["Suyuqlanmada va eritmada ZnO ning ishqor bilan reaksiyasi mahsulotlari nima uchun farq qiladi?", "Na2ZnO2 ni nomlang va rux oksidlanish darajasini aniqlang."],
    conf: "o'rta",
  }),
  R({
    t: "Alyuminiy oksidning sulfat kislotada erishi", lvl: '9-sinf', topic: T_AMF,
    re: [solid('Al2O3', 0.2), aq('H2SO4', 1, 6, { excess: true })], heat_c: true,
    note: "Kuchli kuydirilgan alyuminiy oksid (korund) kislotalarda deyarli erimaydi; tajriba uchun yangi olingan (kuydirilmagan) Al2O3 olinadi va isitiladi.",
    mol: 'Al2O3 + 3H2SO4 = Al2(SO4)3 + 3H2O', full: 'Al2O3 + 6H⁺ + 3SO4²⁻ = 2Al³⁺ + 3SO4²⁻ + 3H2O', net: 'Al2O3 + 6H⁺ = 2Al³⁺ + 3H2O',
    mech: 'neytrallanish', steps: [
      "Kislota bilan reaksiyada Al2O3 asosli oksid xossasini namoyon qiladi.",
      "H⁺ ionlari kislorod ionlarini suvga aylantiradi, Al³⁺ ionlari eritmaga o'tadi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'],
    obs: "Oq kukun isitilganda asta-sekin eriydi, rangsiz eritma hosil bo'ladi.",
    kin: 'sekin', app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga shpatel uchida alyuminiy oksid soling.",
      "Ustiga 5–6 ml suyultirilgan sulfat kislota quying.",
      "Probirkani qisqich bilan ushlab, uzoqroq isiting va kukunning erishini kuzating.",
    ],
    safe: "Isitilgan sulfat kislota sachrasa kuchli kuydiradi: ko'zoynak taqing, probirka og'zini o'zingizga qaratmang.",
    expl: "Alyuminiy oksid amfoter oksid: kislotalar bilan tuz va suv hosil qiladi. Uning kristall panjarasi juda mustahkam bo'lgani uchun reaksiya sekin, faqat isitilganda boradi.",
    q: ["Nima uchun korund kislotalarda erimaydi?", "Al2O3 ning amfoterligini ko'rsatuvchi reaksiyalarni yozing."],
    conf: "o'rta",
  }),
  R({
    t: "Alyuminiy oksidning natriy gidroksid eritmasida erishi", lvl: '9-sinf', topic: T_AMF, engine: 'record',
    re: [solid('Al2O3', 0.2), aq('NaOH', 4, 5, { excess: true })], heat_c: true, tmin: 80,
    note: "Konsentrlangan ishqor eritmasi bilan uzoq qizdiriladi; kuydirilgan Al2O3 deyarli erimaydi.",
    mol: 'Al2O3 + 2NaOH + 3H2O = 2Na[Al(OH)4]', full: 'Al2O3 + 2Na⁺ + 2OH⁻ + 3H2O = 2Na⁺ + 2[Al(OH)4]⁻', net: 'Al2O3 + 2OH⁻ + 3H2O = 2[Al(OH)4]⁻',
    mech: 'kompleks', steps: [
      "Ishqor bilan ta'sirlashganda Al2O3 kislotali oksid xossasini namoyon qiladi.",
      "Al³⁺ atrofida to'rtta OH⁻ ligandi joylashib [Al(OH)4]⁻ gidroksokompleks hosil bo'ladi.",
      "Kompleks ion suvda eriydi — natriy tetragidroksoalyuminat eritmasi hosil bo'ladi.",
    ],
    heat: 'sezilarsiz', fx: ['dissolve', 'boil'],
    obs: "Oq kukun konsentrlangan ishqorda uzoq qizdirilganda asta-sekin eriydi.",
    kin: 'sekin', app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga shpatel uchida alyuminiy oksid soling.",
      "Ustiga 5 ml konsentrlangan natriy gidroksid eritmasi quying.",
      "Probirkani qisqich bilan ushlab, uzoq vaqt ehtiyotkorlik bilan qizdiring va o'zgarishni kuzating.",
    ],
    safe: SAFE_ALK + " Qaynayotgan ishqor sachrasa juda xavfli: probirka og'zini o'zingizga qaratmang.",
    expl: "Alyuminiy oksid ishqor eritmalarida erib tetragidroksoalyuminat hosil qiladi — bu uning kislotali xossasini ko'rsatadi. Sanoatda boksitdan toza alyuminiy oksid olish (Bayer usuli) shu reaksiyaga asoslangan.",
    q: ["Al2O3 ning NaOH eritmasi va suyuqlanmasi bilan reaksiyasi mahsulotlarini solishtiring.", "Bayer usulining mohiyati nimada?"],
    conf: "o'rta",
  }),
  R({
    t: "Alyuminiy oksidning natriy gidroksid bilan suyuqlantirilishi", lvl: '9-sinf', topic: T_AMF, engine: 'record',
    re: [solid('Al2O3', 0.2), solid('NaOH', 0.2, 'granula')], heat_c: true, tmin: 350, note: FUSE_NOTE_NAOH,
    mol: 'Al2O3 + 2NaOH = 2NaAlO2 + H2O↑',
    mech: 'neytrallanish', steps: [
      "Suyuqlanmada Al2O3 kislotali oksid vazifasini bajaradi (HAlO2 metaalyuminat kislotasiga mos keladi).",
      "Ishqor bilan suvsiz tuz — natriy metaalyuminat hosil bo'ladi.",
      "Ajralgan suv yuqori haroratda bug'lanib ketadi.",
    ],
    heat: 'sezilarsiz', fx: ['condensate'],
    obs: "Aralashma suyuqlanadi, suv bug'i ajraladi; sovigach oq qotishma qoladi.",
    kin: 'tez', app: ['tigel', 'tigel-qisqichi', 'chinni-uchburchak', 'uchoyoq', 'bunzen-gorelkasi'],
    proc: [
      "Temir yoki nikel tigelga alyuminiy oksid va natriy gidroksid soling.",
      "Tigelni chinni uchburchakka qo'yib, kuchli qizdiring.",
      "Aralashma to'liq suyuqlanib, bug' ajralishi to'xtagach, sovuting.",
    ],
    safe: SAFE_FUSE,
    expl: "Suyuqlantirishda alyuminiy oksid ishqor bilan suvsiz tuz — natriy metaalyuminat NaAlO2 hosil qiladi. Bu Al2O3 ning kislotali xossasini ko'rsatadi; suvli eritmada esa xuddi shu jarayon [Al(OH)4]⁻ kompleksining hosil bo'lishi bilan boradi.",
    q: ["NaAlO2 suvda eritilsa, eritmada qanday ion hosil bo'ladi?", "Al2O3 ning amfoterligini ko'rsatuvchi tenglamalarni yozing."],
    conf: "o'rta",
  }),
  R({
    t: "Alyuminiy oksidning soda bilan suyuqlantirilishi", lvl: '10-sinf', topic: T_AMF, engine: 'record',
    re: [solid('Al2O3', 0.2), solid('Na2CO3', 0.3)], heat_c: true, tmin: 900, note: FUSE_NOTE_NA2CO3,
    mol: 'Al2O3 + Na2CO3 = 2NaAlO2 + CO2↑',
    mech: 'ion-almashinish', steps: [
      "Yuqori haroratda kam uchuvchan Al2O3 uchuvchan kislotali oksid CO2 ni karbonatdan siqib chiqaradi.",
      "Al2O3 kislotali oksid vazifasini bajarib natriy metaalyuminat hosil qiladi.",
      "CO2 gaz holida chiqib ketadi, shuning uchun reaksiya oxirigacha boradi.",
    ],
    heat: 'endotermik', gas: 'CO2', fx: ['bubbles'],
    obs: "Suyuqlanmada gaz pufakchalari ajraladi; sovigach oq qotishma qoladi.",
    kin: 'tez', app: ['tigel', 'tigel-qisqichi', 'mufel-pechi'],
    proc: [
      "Tigelda alyuminiy oksid va suvsiz soda aralashmasini tayyorlang.",
      "Tigelni mufel pechiga qo'yib, aralashma suyuqlanguncha qizdiring.",
      "Gaz ajralishi to'xtagach, tigelni qisqich bilan chiqarib sovuting.",
    ],
    safe: SAFE_FUSE,
    expl: "Suyuqlanmada amfoter Al2O3 kislotali oksid sifatida karbonatdan uchuvchan CO2 ni siqib chiqaradi. Bu reaksiya alyuminiy birikmalari ishlab chiqarishda boksitni qayta ishlash usullaridan biri hisoblanadi.",
    q: ["Nima uchun bu reaksiya faqat suyuqlanmada boradi?", "SiO2 ning soda bilan reaksiyasi bilan qanday o'xshashlik bor?"],
    conf: "o'rta",
  }),
  R({
    t: "Qo'rg'oshin(II) oksidning nitrat kislotada erishi", lvl: '9-sinf', topic: T_AMF,
    re: [solid('PbO', 0.2), aq('HNO3', 2, 3, { excess: true })],
    mol: 'PbO + 2HNO3 = Pb(NO3)2 + H2O', full: 'PbO + 2H⁺ + 2NO3⁻ = Pb²⁺ + 2NO3⁻ + H2O', net: 'PbO + 2H⁺ = Pb²⁺ + H2O',
    mech: 'neytrallanish', steps: [
      "Kislota bilan PbO asosli oksid kabi ta'sirlashadi.",
      "H⁺ ionlari kislorodni suvga aylantiradi, Pb²⁺ ionlari eritmaga o'tadi.",
    ],
    heat: 'ekzotermik', fx: ['dissolve'],
    obs: "Sariq kukun eriydi, rangsiz tiniq eritma hosil bo'ladi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga ozroq qo'rg'oshin(II) oksid soling.",
      "Ustiga 3 ml suyultirilgan nitrat kislota quyib chayqating.",
      "Kukunning erishini kuzating.",
    ],
    safe: "Qo'rg'oshin birikmalari zaharli: qo'lqopda ishlang, changini nafas bilan olmang, chiqindilarni alohida idishga yig'ing.",
    expl: "Qo'rg'oshin(II) oksid amfoter oksid. Uni eritish uchun nitrat kislota tanlanadi, chunki qo'rg'oshin(II) nitrat suvda yaxshi eriydi, xlorid va sulfat esa kam eriydi.",
    q: ["Nima uchun PbO ni eritish uchun sulfat kislota yaramaydi?", "PbO ning ishqor bilan reaksiyasi tenglamasini yozing."],
  }),
  R({
    t: "Qo'rg'oshin(II) oksidning konsentrlangan ishqor eritmasida erishi", lvl: '10-sinf', topic: T_AMF, engine: 'record',
    re: [solid('PbO', 0.2), aq('NaOH', 4, 5, { excess: true })], heat_c: true,
    note: "Konsentrlangan ishqor eritmasi bilan isitiladi.",
    mol: 'PbO + 2NaOH + H2O = Na2[Pb(OH)4]', full: 'PbO + 2Na⁺ + 2OH⁻ + H2O = 2Na⁺ + [Pb(OH)4]²⁻', net: 'PbO + 2OH⁻ + H2O = [Pb(OH)4]²⁻',
    mech: 'kompleks', steps: [
      "Ishqor bilan ta'sirlashganda PbO kislotali xossasini namoyon qiladi.",
      "Pb²⁺ atrofida to'rtta OH⁻ ligand joylashib [Pb(OH)4]²⁻ gidroksokompleks hosil bo'ladi.",
    ],
    heat: 'sezilarsiz', fx: ['dissolve'],
    obs: "Sariq kukun isitilgan konsentrlangan ishqorda asta-sekin eriydi, rangsiz eritma hosil bo'ladi.",
    kin: "o'rtacha", app: ['probirka', 'shpatel', 'probirka-qisqichi', 'spirt-lampasi'],
    proc: [
      "Probirkaga ozroq qo'rg'oshin(II) oksid soling.",
      "Ustiga 5 ml konsentrlangan natriy gidroksid eritmasi quying.",
      "Probirkani qisqich bilan ushlab isiting va kukunning erishini kuzating.",
    ],
    safe: "Qo'rg'oshin birikmalari zaharli, ishqor o'yuvchi: qo'lqop va ko'zoynakda ishlang, isitilgan ishqor sachrashidan ehtiyot bo'ling.",
    expl: "Qo'rg'oshin(II) oksid ishqor eritmasida erib tetragidroksoplyumbat(II) hosil qiladi. Bu PbO ning amfoter oksid ekanligini tasdiqlaydi.",
    q: ["[Pb(OH)4]²⁻ ionini nomlang.", "PbO ning amfoterligini ko'rsatuvchi ikkita reaksiya tenglamasini yozing."],
    conf: "o'rta",
  }),
  R({
    t: "Xrom(III) oksidning natriy gidroksid bilan suyuqlantirilishi", lvl: 'litsey', topic: T_AMF, engine: 'record',
    re: [solid('Cr2O3', 0.2), solid('NaOH', 0.2, 'granula')], heat_c: true, tmin: 350, note: FUSE_NOTE_NAOH,
    mol: 'Cr2O3 + 2NaOH = 2NaCrO2 + H2O↑',
    mech: 'neytrallanish', steps: [
      "Cr2O3 amfoter oksid; suyuqlanmada ishqor bilan kislotali oksid sifatida ta'sirlashadi.",
      "Natriy xromit (NaCrO2, metaxromit kislota tuzi) hosil bo'ladi.",
      "Ajralgan suv bug' holida chiqib ketadi.",
    ],
    heat: 'sezilarsiz', fx: ['condensate'],
    obs: "Yashil kukun ishqor bilan suyuqlantirilganda suv bug'i ajraladi, yashil qotishma hosil bo'ladi.",
    kin: "o'rtacha", app: ['tigel', 'tigel-qisqichi', 'chinni-uchburchak', 'uchoyoq', 'bunzen-gorelkasi'],
    proc: [
      "Temir tigelga xrom(III) oksid va natriy gidroksid soling.",
      "Tigelni chinni uchburchakka qo'yib, kuchli qizdiring.",
      "Aralashma suyuqlanib, bug' ajralishi to'xtagach, sovuting va rangini kuzating.",
    ],
    safe: SAFE_FUSE + " Xrom birikmalari zararli.",
    expl: "Xrom(III) oksid kislotalarda ham, ishqor eritmalarida ham juda qiyin eriydi, lekin suyuqlantirishda ishqor bilan xromit hosil qiladi — bu uning kislotali xossasini ko'rsatadi. Havo kislorodi yoki oksidlovchi ishtirokida suyuqlanmada sariq xromat ham hosil bo'lishi mumkin.",
    q: ["Cr2O3 ning amfoterligini qanday tajribalar bilan ko'rsatish mumkin?", "NaCrO2 da xromning oksidlanish darajasini aniqlang."],
    conf: "o'rta",
  }),
  R({
    t: "Temir(III) oksidning natriy gidroksid bilan suyuqlantirilishi", lvl: 'litsey', topic: T_AMF, engine: 'record',
    re: [solid('Fe2O3', 0.2), solid('NaOH', 0.2, 'granula')], heat_c: true, tmin: 350, note: FUSE_NOTE_NAOH,
    mol: 'Fe2O3 + 2NaOH = 2NaFeO2 + H2O↑',
    mech: 'neytrallanish', steps: [
      "Fe2O3 asosan asosli oksid, ammo kuchsiz amfoter xossaga ham ega.",
      "Suyuqlanmada ishqor bilan natriy ferrit NaFeO2 hosil bo'ladi.",
      "Eritmada bu reaksiya deyarli bormaydi — faqat suyuqlanmada kuzatiladi.",
    ],
    heat: 'sezilarsiz', fx: ['condensate'],
    obs: "Qizil-qo'ng'ir kukun ishqor bilan suyuqlantirilganda suv bug'i ajraladi, qo'ng'ir qotishma hosil bo'ladi.",
    kin: "o'rtacha", app: ['tigel', 'tigel-qisqichi', 'chinni-uchburchak', 'uchoyoq', 'bunzen-gorelkasi'],
    proc: [
      "Temir tigelga temir(III) oksid va natriy gidroksid soling.",
      "Tigelni chinni uchburchakka qo'yib, kuchli qizdiring.",
      "Bug' ajralishi to'xtagach, tigelni sovuting.",
    ],
    safe: SAFE_FUSE,
    expl: "Temir(III) oksidning kislotali xossasi juda kuchsiz: u ishqor eritmalarida amalda erimaydi, ammo ishqor bilan suyuqlantirilganda ferrit hosil qiladi. Shu sababli Fe2O3 kuchsiz amfoter oksid hisoblanadi.",
    q: ["Fe2O3 ning amfoterligi ZnO va Al2O3 nikidan qanday farq qiladi?", "Ferritlar qayerda ishlatiladi?"],
    conf: "o'rta",
  }),
  // ------------------------------------------------------------ kislotali oksid + asos
  R({
    t: "Karbonat angidridning ohakli suv bilan reaksiyasi", lvl: '8-sinf', topic: T_ACID,
    re: [aq('Ca(OH)2', 0.02, 5), gasR('CO2')],
    note: "Ohakli suv — kalsiy gidroksidning to'yingan eritmasi.",
    mol: 'Ca(OH)2 + CO2 = CaCO3↓ + H2O', full: 'Ca²⁺ + 2OH⁻ + CO2 = CaCO3↓ + H2O', net: 'Ca²⁺ + 2OH⁻ + CO2 = CaCO3↓ + H2O',
    mech: 'ion-almashinish', steps: [
      "CO2 suvda erib karbonat kislota hosil qiladi va OH⁻ ionlari bilan neytrallanadi.",
      "Hosil bo'lgan CO3²⁻ ionlari Ca²⁺ bilan erimaydigan CaCO3 ni hosil qiladi.",
    ],
    heat: 'sezilarsiz', ppt: 'CaCO3', fx: ['bubbles', 'turbidity'],
    obs: "Gaz o'tkazilganda tiniq ohakli suv loyqalanadi — oq cho'kma hosil bo'ladi.",
    kin: 'tez', app: ['probirka', 'gaz-naycha-egilgan', 'kipp-apparati'],
    proc: [
      "Probirkaga 5 ml tiniq ohakli suv quying.",
      "Kipp apparatidan chiqayotgan karbonat angidridni gaz o'tkazgich naycha orqali ohakli suvga o'tkazing.",
      "Eritmaning loyqalanishini kuzating.",
    ],
    safe: "Gaz o'tkazgich naychani suyuqlikdan chiqarmasdan gaz oqimini to'xtatmang (suyuqlik orqaga so'rilishi mumkin).",
    expl: "Kislotali oksid CO2 asos bilan tuz va suv hosil qiladi. Kalsiy karbonat suvda erimaydi, shuning uchun ohakli suv loyqalanadi. Bu reaksiya karbonat angidridni aniqlashda ishlatiladi.",
    q: ["Ohakli suv yordamida nafas bilan chiqarilgan havoda CO2 borligini qanday isbotlash mumkin?", "Reaksiyaning ionli tenglamasini yozing."],
  }),
  R({
    t: "Ohakli suvga ortiqcha karbonat angidrid o'tkazish (loyqaning yo'qolishi)", lvl: '9-sinf', topic: T_ACID,
    re: [aq('Ca(OH)2', 0.02, 5), gasR('CO2', { excess: true })],
    note: "CO2 uzoq vaqt, ortiqcha miqdorda o'tkaziladi.",
    mol: 'Ca(OH)2 + 2CO2 = Ca(HCO3)2', full: 'Ca²⁺ + 2OH⁻ + 2CO2 = Ca²⁺ + 2HCO3⁻', net: 'OH⁻ + CO2 = HCO3⁻',
    mech: 'ion-almashinish', steps: [
      "Avval CaCO3 cho'kmasi hosil bo'ladi: Ca(OH)2 + CO2 = CaCO3↓ + H2O.",
      "Ortiqcha CO2 suv bilan karbonat kislota hosil qiladi va u CO3²⁻ ionlarini HCO3⁻ ga aylantiradi.",
      "Kalsiy gidrokarbonat suvda eriydi, shuning uchun loyqa yo'qoladi.",
    ],
    heat: 'sezilarsiz', fx: ['bubbles', 'turbidity', 'dissolve'],
    obs: "Avval ohakli suv loyqalanadi, gaz o'tkazish davom ettirilganda esa loyqa asta-sekin yo'qolib, eritma yana tiniq bo'ladi.",
    kin: "o'rtacha", app: ['probirka', 'gaz-naycha-egilgan', 'kipp-apparati'],
    proc: [
      "Probirkaga 5 ml tiniq ohakli suv quying.",
      "Unga Kipp apparatidan karbonat angidrid o'tkazing va loyqalanishni kuzating.",
      "Gaz o'tkazishni loyqa yo'qolguncha davom ettiring.",
      "Tiniq eritmani qaynatib ko'ring: u yana loyqalanadi.",
    ],
    safe: "Gaz o'tkazgich naychani suyuqlikdan chiqarib, so'ng gaz oqimini to'xtating; qaynatishda probirka og'zini o'zingizga qaratmang.",
    expl: "Ortiqcha CO2 suvda erimaydigan o'rta tuz CaCO3 ni eriydigan nordon tuz Ca(HCO3)2 ga aylantiradi. Tabiatda ohaktoshlarning erishi, g'orlar hosil bo'lishi va suvning vaqtinchalik qattiqligi shu jarayon bilan bog'liq. Qaynatilganda gidrokarbonat parchalanib, yana CaCO3 cho'kadi.",
    q: ["Nima uchun loyqa yo'qoladi?", "Suvning vaqtinchalik qattiqligi qanday yo'qotiladi?", "G'orlarda stalaktitlar qanday hosil bo'ladi?"],
  }),
  R({
    t: "Oltingugurt(IV) oksidning ohakli suv bilan reaksiyasi", lvl: '9-sinf', topic: T_ACID,
    re: [aq('Ca(OH)2', 0.02, 5), gasR('SO2')],
    mol: 'Ca(OH)2 + SO2 = CaSO3↓ + H2O', full: 'Ca²⁺ + 2OH⁻ + SO2 = CaSO3↓ + H2O', net: 'Ca²⁺ + 2OH⁻ + SO2 = CaSO3↓ + H2O',
    mech: 'ion-almashinish', steps: [
      "SO2 suvda sulfit kislota hosil qiladi va u OH⁻ ionlari bilan neytrallanadi.",
      "Hosil bo'lgan SO3²⁻ ionlari Ca²⁺ bilan erimaydigan CaSO3 ni hosil qiladi.",
    ],
    heat: 'sezilarsiz', ppt: 'CaSO3', fx: ['bubbles', 'turbidity'],
    obs: "Gaz o'tkazilganda ohakli suv loyqalanadi — oq cho'kma hosil bo'ladi.",
    kin: 'tez', app: ['probirka', 'gaz-naycha-egilgan', 'probirka-yon-naychali'],
    proc: [
      "Probirkaga 5 ml tiniq ohakli suv quying.",
      "Gaz olish asbobidan SO2 ni gaz o'tkazgich naycha orqali ohakli suvga o'tkazing.",
      "Eritmaning loyqalanishini kuzating.",
    ],
    safe: "SO2 zaharli: tajribani mo'rili shkafda o'tkazing, gazni hidlamang.",
    expl: "Oltingugurt(IV) oksid ham CO2 kabi ohakli suvni loyqalantiradi, shuning uchun ohakli suv bilan bu ikki gazni farqlab bo'lmaydi. SO2 ni o'tkir hidi va kaliy permanganat yoki bromli suvni rangsizlantirishi bilan farqlash mumkin.",
    q: ["CO2 va SO2 ni qanday farqlash mumkin?", "Issiqlik elektr stansiyalarida tutun tarkibidagi SO2 ni ushlashda ohakdan nima uchun foydalaniladi?"],
  }),
  R({
    t: "Karbonat angidridning barit suvi bilan reaksiyasi", lvl: '9-sinf', topic: T_ACID,
    re: [aq('Ba(OH)2', 0.1, 5), gasR('CO2')],
    mol: 'Ba(OH)2 + CO2 = BaCO3↓ + H2O', full: 'Ba²⁺ + 2OH⁻ + CO2 = BaCO3↓ + H2O', net: 'Ba²⁺ + 2OH⁻ + CO2 = BaCO3↓ + H2O',
    mech: 'ion-almashinish', steps: [
      "CO2 ishqoriy eritmada OH⁻ ionlari bilan CO3²⁻ ga aylanadi.",
      "CO3²⁻ ionlari Ba²⁺ bilan erimaydigan BaCO3 hosil qiladi.",
    ],
    heat: 'sezilarsiz', ppt: 'BaCO3', fx: ['bubbles', 'turbidity'],
    obs: "Gaz o'tkazilganda barit suvi tez loyqalanadi, oq cho'kma tushadi.",
    kin: 'tez', app: ['probirka', 'gaz-naycha-egilgan', 'kipp-apparati'],
    proc: [
      "Probirkaga 5 ml barit suvi (bariy gidroksid eritmasi) quying.",
      "Kipp apparatidan karbonat angidridni gaz o'tkazgich naycha orqali o'tkazing.",
      "Loyqalanishni ohakli suv bilan o'tkazilgan tajriba bilan solishtiring.",
    ],
    safe: "Bariy birikmalari zaharli: qo'lqop taqing, moddani og'izga tekkizmang.",
    expl: "Barit suvi ohakli suvdan konsentrlanganroq, chunki Ba(OH)2 suvda Ca(OH)2 ga qaraganda ancha yaxshi eriydi. Shuning uchun u CO2 ning juda oz miqdorini ham sezgir aniqlaydi.",
    q: ["Nima uchun barit suvi ohakli suvga qaraganda sezgirroq?", "Reaksiyaning ionli tenglamasini yozing."],
  }),
  R({
    t: "Karbonat angidridning natriy gidroksid eritmasiga yutilishi", lvl: '8-sinf', topic: T_ACID,
    re: [aq('NaOH', 1, 5, { excess: true }), gasR('CO2'), fenolftalein],
    mol: '2NaOH + CO2 = Na2CO3 + H2O', full: '2Na⁺ + 2OH⁻ + CO2 = 2Na⁺ + CO3²⁻ + H2O', net: '2OH⁻ + CO2 = CO3²⁻ + H2O',
    mech: 'neytrallanish', steps: [
      "CO2 suvda karbonat kislotaga aylanadi va ishqorning OH⁻ ionlari bilan neytrallanadi.",
      "Ishqor ortiqcha bo'lganda o'rta tuz — natriy karbonat hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['bubbles'],
    obs: "Gaz pufakchalari eritmaga to'liq yutiladi, ko'rinadigan o'zgarish bo'lmaydi; eritma ishqoriyligicha qoladi (fenolftalein pushti).",
    kin: 'tez', app: ['probirka', 'gaz-naycha-egilgan', 'kipp-apparati'],
    proc: [
      "Probirkaga 5 ml natriy gidroksid eritmasi quying va 1 tomchi fenolftalein qo'shing.",
      "Kipp apparatidan CO2 ni qisqa vaqt o'tkazing.",
      "Gaz pufakchalarining yutilishini kuzating.",
    ],
    safe: SAFE_ALK,
    expl: "Kislotali oksid ishqor bilan tuz va suv hosil qiladi. Ishqor ortiqcha bo'lganda o'rta tuz Na2CO3 hosil bo'ladi; uning eritmasi gidroliz tufayli ishqoriy muhitga ega. Bu reaksiya gazlarni CO2 dan tozalashda ishlatiladi.",
    q: ["Nima uchun natriy gidroksid saqlanadigan idish og'zi zich yopilishi kerak?", "CO2 ortiqcha bo'lsa, qanday tuz hosil bo'ladi?"],
  }),
  R({
    t: "Natriy gidroksid eritmasiga ortiqcha karbonat angidrid o'tkazish", lvl: '9-sinf', topic: T_ACID,
    re: [aq('NaOH', 1, 5), gasR('CO2', { excess: true }), fenolftalein],
    note: "CO2 ortiqcha miqdorda, uzoq vaqt o'tkaziladi.",
    mol: 'NaOH + CO2 = NaHCO3', full: 'Na⁺ + OH⁻ + CO2 = Na⁺ + HCO3⁻', net: 'OH⁻ + CO2 = HCO3⁻',
    mech: 'neytrallanish', steps: [
      "Avval natriy karbonat hosil bo'ladi.",
      "Ortiqcha CO2 suv bilan CO3²⁻ ionlarini HCO3⁻ ga aylantiradi: CO3²⁻ + CO2 + H2O = 2HCO3⁻.",
      "Natijada nordon tuz — natriy gidrokarbonat hosil bo'ladi, muhit kuchsiz ishqoriy bo'lib qoladi.",
    ],
    heat: 'ekzotermik', fx: ['bubbles'], col: [C.fenolQ, C.rangsiz],
    obs: "Gaz o'tkazish davomida fenolftaleinning to'q pushti rangi oqarib, deyarli rangsizlanadi.",
    kin: "o'rtacha", app: ['probirka', 'gaz-naycha-egilgan', 'kipp-apparati'],
    proc: [
      "Probirkaga 5 ml natriy gidroksid eritmasi quying va 1 tomchi fenolftalein qo'shing.",
      "Kipp apparatidan CO2 ni uzoq vaqt o'tkazing.",
      "Indikator rangining asta-sekin o'zgarishini kuzating.",
    ],
    safe: SAFE_ALK,
    expl: "Ishqor va kislotali oksid nisbatiga qarab o'rta yoki nordon tuz hosil bo'ladi. CO2 ortiqcha bo'lganda natriy gidrokarbonat hosil bo'ladi; uning eritmasi juda kuchsiz ishqoriy (pH ≈ 8), shuning uchun fenolftalein rangi deyarli yo'qoladi.",
    q: ["O'rta va nordon tuzlarning farqi nimada?", "NaHCO3 ning maishiy nomi va qo'llanilishini ayting."],
  }),
  R({
    t: "Oltingugurt(IV) oksidning natriy gidroksid eritmasiga yutilishi", lvl: '9-sinf', topic: T_ACID,
    re: [aq('NaOH', 1, 5, { excess: true }), gasR('SO2')],
    mol: '2NaOH + SO2 = Na2SO3 + H2O', full: '2Na⁺ + 2OH⁻ + SO2 = 2Na⁺ + SO3²⁻ + H2O', net: '2OH⁻ + SO2 = SO3²⁻ + H2O',
    mech: 'neytrallanish', steps: [
      "SO2 eritmada sulfit kislotaga aylanadi.",
      "Ishqor ortiqcha bo'lganda ikkala proton ham OH⁻ bilan neytrallanadi va o'rta tuz Na2SO3 hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['bubbles'],
    obs: "Gaz eritmaga to'liq yutiladi, o'tkir hid sezilmaydi; ko'rinadigan boshqa o'zgarish bo'lmaydi.",
    kin: 'tez', app: ['probirka', 'gaz-naycha-egilgan', 'probirka-yon-naychali'],
    proc: [
      "Probirkaga 5 ml natriy gidroksid eritmasi quying.",
      "Gaz olish asbobidan SO2 ni gaz o'tkazgich naycha orqali qisqa vaqt o'tkazing.",
      "Gazning yutilishini kuzating.",
    ],
    safe: "SO2 zaharli, ishqor o'yuvchi: mo'rili shkafda, ko'zoynak va qo'lqopda ishlang.",
    expl: "SO2 kislotali oksid sifatida ishqor bilan tuz va suv hosil qiladi. Laboratoriyada ortiqcha SO2 ni zararsizlantirish uchun gaz ishqor eritmasiga yuttiriladi.",
    q: ["Laboratoriyada zaharli kislotali gazlar qanday zararsizlantiriladi?", "SO2 ortiqcha bo'lsa, qanday tuz hosil bo'ladi?"],
  }),
  R({
    t: "Natriy gidroksid eritmasiga ortiqcha oltingugurt(IV) oksid o'tkazish", lvl: '9-sinf', topic: T_ACID,
    re: [aq('NaOH', 1, 5), gasR('SO2', { excess: true })],
    note: "SO2 ortiqcha miqdorda o'tkaziladi.",
    mol: 'NaOH + SO2 = NaHSO3', full: 'Na⁺ + OH⁻ + SO2 = Na⁺ + HSO3⁻', net: 'OH⁻ + SO2 = HSO3⁻',
    mech: 'neytrallanish', steps: [
      "Avval natriy sulfit hosil bo'ladi.",
      "Ortiqcha SO2 suv bilan SO3²⁻ ionlarini HSO3⁻ ga aylantiradi.",
      "Natijada nordon tuz — natriy gidrosulfit hosil bo'ladi va muhit kuchsiz kislotali bo'lib qoladi.",
    ],
    heat: 'ekzotermik', fx: ['bubbles'],
    obs: "Gaz avval to'liq yutiladi; oxirida eritma ustida SO2 ning o'tkir hidi seziladi, eritma kislotali bo'lib qoladi.",
    kin: "o'rtacha", app: ['probirka', 'gaz-naycha-egilgan', 'probirka-yon-naychali'],
    proc: [
      "Probirkaga 5 ml natriy gidroksid eritmasi quying.",
      "SO2 ni ortiqcha miqdorda, uzoq vaqt o'tkazing.",
      "Eritma muhitini universal indikator qog'ozi bilan tekshiring.",
    ],
    safe: "SO2 zaharli: faqat mo'rili shkafda ishlang, gazni hidlamang.",
    expl: "Ikki negizli kislotaga mos keladigan kislotali oksid ortiqcha bo'lganda nordon tuz hosil bo'ladi. NaHSO3 eritmasi kuchsiz kislotali, chunki HSO3⁻ ionining dissotsilanishi gidrolizidan ustun turadi.",
    q: ["Na2SO3 va NaHSO3 eritmalarining muhiti qanday?", "SO2 va NaOH ning qanday nisbatida o'rta, qanday nisbatida nordon tuz hosil bo'ladi?"],
    conf: 'yuqori',
  }),
  R({
    t: "Fosfor(V) oksidning natriy gidroksid eritmasi bilan reaksiyasi", lvl: '8-sinf', topic: T_ACID,
    re: [solid('P2O5', 0.1), aq('NaOH', 2, 5, { excess: true })],
    mol: 'P2O5 + 6NaOH = 2Na3PO4 + 3H2O', full: 'P2O5 + 6Na⁺ + 6OH⁻ = 6Na⁺ + 2PO4³⁻ + 3H2O', net: 'P2O5 + 6OH⁻ = 2PO4³⁻ + 3H2O',
    mech: 'neytrallanish', steps: [
      "P2O5 suv bilan ortofosfat kislotaga aylanadi.",
      "Ishqor ortiqcha bo'lganda kislotaning uchala protoni ham OH⁻ bilan neytrallanadi.",
      "O'rta tuz — natriy ortofosfat hosil bo'ladi.",
    ],
    heat: 'kuchli-ekzotermik', fx: ['dissolve', 'heat-haze'],
    obs: "Oq kukun ishqor eritmasida vishillab eriydi, eritma qiziydi.",
    kin: 'tez', app: ['probirka', 'shpatel'],
    proc: [
      "Probirkaga 5 ml natriy gidroksid eritmasi quying.",
      "Shpatel uchida juda oz fosfor(V) oksid soling.",
      "Erish va isishni kuzating.",
    ],
    safe: "P2O5 va ishqor terini kuydiradi: ko'zoynak va qo'lqopdan foydalaning, P2O5 ni oz miqdorda qo'shing.",
    expl: "Kislotali oksid ishqor bilan tuz va suv hosil qiladi. Uch negizli kislotaga mos keladigan P2O5 ishqor ortiqcha bo'lganda o'rta tuz — ortofosfat hosil qiladi; ishqor kam bo'lsa, nordon tuzlar (gidro- va digidrofosfatlar) hosil bo'ladi.",
    q: ["P2O5 va NaOH nisbati 1:2 bo'lsa, qanday tuz hosil bo'ladi?", "Reaksiyaning qisqartirilgan ionli tenglamasini yozing."],
  }),
  R({
    t: "Azot(IV) oksidning natriy gidroksid eritmasiga yutilishi", lvl: '9-sinf', topic: T_ACID, engine: 'rules',
    re: [gasR('NO2'), aq('NaOH', 1, 5)],
    mol: '2NO2 + 2NaOH = NaNO3 + NaNO2 + H2O', full: '2NO2 + 2Na⁺ + 2OH⁻ = 2Na⁺ + NO3⁻ + NO2⁻ + H2O', net: '2NO2 + 2OH⁻ = NO3⁻ + NO2⁻ + H2O',
    eb: ['N⁺⁴ − 1e⁻ = N⁺⁵', 'N⁺⁴ + 1e⁻ = N⁺³'],
    mech: 'oksidlanish-qaytarilish', steps: [
      "NO2 ishqor bilan ta'sirlashganda disproporsiyalanadi.",
      "Bir azot atomi +5 holatga (nitrat ioniga) oksidlanadi, ikkinchisi +3 holatga (nitrit ioniga) qaytariladi.",
      "Ikki tuz — natriy nitrat va natriy nitrit aralashmasi hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['color-gas'],
    obs: "Qo'ng'ir gaz ishqor eritmasiga tez yutilib rangsizlanadi; eritma rangsizligicha qoladi.",
    kin: 'tez', app: ['gaz-silindri', 'tomizgich'],
    proc: [
      "Tajriba o'qituvchi tomonidan mo'rili shkafda ko'rsatiladi.",
      "NO2 bilan to'ldirilgan silindrga 5 ml natriy gidroksid eritmasi quying.",
      "Silindrni tiqin bilan yopib chayqating va qo'ng'ir rangning yo'qolishini kuzating.",
    ],
    safe: "NO2 juda zaharli, ishqor o'yuvchi: faqat mo'rili shkafda, ko'zoynak va qo'lqopda ishlang.",
    expl: "NO2 ga bitta kislota mos kelmaydi, shuning uchun u ishqor bilan ikki xil tuz hosil qiladi. Bu reaksiya sanoatda chiqindi gazlarni azot oksidlaridan tozalashda qo'llaniladi.",
    q: ["Bu reaksiyada oksidlovchi va qaytaruvchi qaysi modda?", "Nima uchun NO2 ning ishqor bilan reaksiyasida ikki xil tuz hosil bo'ladi?"],
  }),
  R({
    t: "Kremniy(IV) oksidning natriy gidroksid bilan suyuqlantirilishi", lvl: '9-sinf', topic: T_ACID, engine: 'record',
    re: [solid('SiO2', 0.2), solid('NaOH', 0.3, 'granula')], heat_c: true, tmin: 350, note: FUSE_NOTE_NAOH,
    mol: 'SiO2 + 2NaOH = Na2SiO3 + H2O↑',
    mech: 'neytrallanish', steps: [
      "Yuqori haroratda SiO2 ning mustahkam panjarasi ishqor ta'sirida buziladi.",
      "SiO2 kislotali oksid sifatida ishqor bilan natriy silikat hosil qiladi.",
      "Suv bug' holida ajralib chiqadi.",
    ],
    heat: 'sezilarsiz', fx: ['condensate'],
    obs: "Aralashma suyuqlanadi, suv bug'i ajraladi; sovigach shishasimon massa — natriy silikat qoladi, u suvda eriydi.",
    kin: "o'rtacha", app: ['tigel', 'tigel-qisqichi', 'chinni-uchburchak', 'uchoyoq', 'bunzen-gorelkasi'],
    proc: [
      "Temir yoki nikel tigelga toza qum va natriy gidroksid granulalarini soling.",
      "Tigelni chinni uchburchakka qo'yib, kuchli qizdiring.",
      "Suyuqlanma bir xil bo'lib, bug' ajralishi to'xtagach, sovuting.",
      "Sovigan massaning bir qismini suvda eriting.",
    ],
    safe: SAFE_FUSE,
    expl: "Kremniy(IV) oksid suv va kislotalar bilan reaksiyaga kirishmaydi, lekin kislotali oksid sifatida ishqorlar bilan suyuqlantirilganda silikat hosil qiladi. Natriy silikatning konsentrlangan eritmasi 'suyuq shisha' deb ataladi.",
    q: ["Nima uchun ishqor eritmalari shisha idishlarda uzoq saqlanmaydi?", "'Suyuq shisha' qayerda ishlatiladi?"],
    conf: "o'rta",
  }),
  R({
    t: "Kremniy(IV) oksidning soda bilan suyuqlantirilishi (shisha olish asosi)", lvl: '9-sinf', topic: T_ACID, engine: 'record',
    re: [solid('SiO2', 0.2), solid('Na2CO3', 0.4)], heat_c: true, tmin: 900, note: FUSE_NOTE_NA2CO3,
    mol: 'SiO2 + Na2CO3 = Na2SiO3 + CO2↑',
    mech: 'ion-almashinish', steps: [
      "Yuqori haroratda kam uchuvchan kislotali oksid SiO2 uchuvchan CO2 ni karbonatdan siqib chiqaradi.",
      "Natriy silikat hosil bo'ladi, CO2 gaz holida chiqib ketadi.",
      "Gaz chiqib ketgani uchun muvozanat mahsulotlar tomoniga siljiydi.",
    ],
    heat: 'endotermik', gas: 'CO2', fx: ['bubbles'],
    obs: "Suyuqlanmadan gaz pufakchalari ajraladi; sovigach shishasimon massa qoladi.",
    kin: "o'rtacha", app: ['tigel', 'tigel-qisqichi', 'mufel-pechi'],
    proc: [
      "Tigelda toza qum va suvsiz soda aralashmasini tayyorlang.",
      "Tigelni mufel pechiga qo'yib, aralashma suyuqlanguncha qizdiring.",
      "Gaz ajralishi to'xtagach, tigelni qisqich bilan chiqarib sovuting.",
    ],
    safe: SAFE_FUSE,
    expl: "Suvli eritmada karbonat kislota silikat kislotadan kuchli, ammo suyuqlanmada uchuvchan bo'lmagan SiO2 uchuvchan CO2 ni siqib chiqaradi. Oddiy deraza shishasi qum, soda va ohaktosh aralashmasini suyuqlantirib olinadi.",
    q: ["Nima uchun eritmada CO2 silikatdan silikat kislotani siqib chiqaradi, suyuqlanmada esa aksincha?", "Oddiy shisha tarkibini yozing."],
    conf: "o'rta",
  }),
  R({
    t: "Karbonat angidridning soda eritmasi bilan reaksiyasi", lvl: '9-sinf', topic: T_ACID,
    re: [aq('Na2CO3', 1, 5), gasR('CO2')],
    mol: 'Na2CO3 + CO2 + H2O = 2NaHCO3', full: '2Na⁺ + CO3²⁻ + CO2 + H2O = 2Na⁺ + 2HCO3⁻', net: 'CO3²⁻ + CO2 + H2O = 2HCO3⁻',
    mech: 'ion-almashinish', steps: [
      "CO2 suvda karbonat kislota hosil qiladi.",
      "H2CO3 bitta protonini CO3²⁻ ioniga beradi va ikkita HCO3⁻ ioni hosil bo'ladi.",
      "O'rta tuz nordon tuzga — natriy gidrokarbonatga aylanadi.",
    ],
    heat: 'sezilarsiz', fx: ['bubbles'],
    obs: "Gaz eritmaga yutiladi; konsentrlangan eritmada natriy gidrokarbonatning oq kristallari ajralishi mumkin.",
    kin: "o'rtacha", app: ['probirka', 'gaz-naycha-egilgan', 'kipp-apparati'],
    proc: [
      "Probirkaga 5 ml soda eritmasi quying.",
      "Kipp apparatidan CO2 ni uzoq vaqt o'tkazing.",
      "Eritma muhitini tajribadan oldin va keyin universal indikator qog'ozi bilan solishtiring.",
    ],
    safe: "Gaz o'tkazgich naychani suyuqlikdan chiqarib, so'ng gaz oqimini to'xtating.",
    expl: "Karbonat angidrid o'rta tuz eritmasi bilan ta'sirlashib uni nordon tuzga aylantiradi. Muhit kuchli ishqoriydan kuchsiz ishqoriyga o'zgaradi. Bu reaksiya soda ishlab chiqarishning ammiakli usulida muhim bosqich hisoblanadi.",
    q: ["Na2CO3 va NaHCO3 eritmalarining pH qiymatlari qanday farq qiladi?", "Reaksiyaning qisqartirilgan ionli tenglamasini yozing."],
  }),
  R({
    t: "Karbonat angidridning natriy silikat eritmasi bilan reaksiyasi", lvl: '9-sinf', topic: T_ACID,
    re: [aq('Na2SiO3', 0.5, 5), gasR('CO2', { excess: true })],
    note: "CO2 ortiqcha miqdorda o'tkaziladi.",
    mol: 'Na2SiO3 + 2CO2 + 2H2O = H2SiO3↓ + 2NaHCO3', full: '2Na⁺ + SiO3²⁻ + 2CO2 + 2H2O = H2SiO3↓ + 2Na⁺ + 2HCO3⁻', net: 'SiO3²⁻ + 2CO2 + 2H2O = H2SiO3↓ + 2HCO3⁻',
    mech: 'ion-almashinish', steps: [
      "CO2 suvda karbonat kislota hosil qiladi; u silikat kislotadan kuchliroq.",
      "Kuchliroq kislota kuchsizroq kislotani tuzidan siqib chiqaradi.",
      "Silikat kislota suvda erimaydi va iviqsimon cho'kma hosil qiladi.",
    ],
    heat: 'sezilarsiz', ppt: 'H2SiO3', fx: ['bubbles', 'turbidity'],
    obs: "Gaz o'tkazilganda eritmada oq iviqsimon (kisel ko'rinishidagi) cho'kma hosil bo'ladi.",
    kin: "o'rtacha", app: ['probirka', 'gaz-naycha-egilgan', 'kipp-apparati'],
    proc: [
      "Probirkaga 5 ml natriy silikat eritmasi quying.",
      "Kipp apparatidan CO2 ni uzoq vaqt o'tkazing.",
      "Iviqsimon cho'kma hosil bo'lishini kuzating.",
    ],
    safe: "Natriy silikat eritmasi ishqoriy, teri va ko'zni qitiqlaydi: ko'zoynak taqing.",
    expl: "Karbonat kislota silikat kislotadan kuchli bo'lgani uchun uni tuzidan siqib chiqaradi. Shu sababli havoda ochiq qoldirilgan 'suyuq shisha' asta-sekin loyqalanadi.",
    q: ["Nima uchun ochiq qoldirilgan natriy silikat eritmasi loyqalanadi?", "Kislotalarning kuch qatorida karbonat va silikat kislotalarning o'rnini ko'rsating."],
  }),
  // ------------------------------------------------------------ oksid + oksid
  R({
    t: "Kalsiy oksidning karbonat angidrid bilan birikishi", lvl: '8-sinf', topic: T_OXOX, engine: 'record',
    re: [solid('CaO', 0.5), gasR('CO2')], heat_c: true, tmin: 400, tmax: 800,
    note: "Quruq kalsiy oksid CO2 oqimida qizdiriladi; xona haroratida reaksiya juda sekin. Harorat kalsiy karbonatning parchalanish haroratidan past bo'lishi kerak (chegaralar taxminiy).",
    mol: 'CaO + CO2 = CaCO3',
    mech: 'birikish', steps: [
      "Asosli oksid (CaO) kislotali oksid (CO2) bilan suvsiz sharoitda bevosita birikadi.",
      "O²⁻ ioni CO2 molekulasining uglerod atomiga birikib CO3²⁻ ionini hosil qiladi.",
      "Natijada tuz — kalsiy karbonat hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: [],
    obs: "Oq kukunning tashqi ko'rinishi deyarli o'zgarmaydi; massasi ortadi. Mahsulot kislota ta'sirida CO2 ajratadi.",
    kin: "o'rtacha", app: ['chinni-qayiqcha', 'gaz-naycha-togri', 'kipp-apparati', 'bunzen-gorelkasi'],
    proc: [
      "Chinni qayiqchaga kalsiy oksid kukunini soling va uni shisha naycha ichiga joylashtiring.",
      "Naycha orqali Kipp apparatidan quruq CO2 o'tkazing.",
      "Naychani qayiqcha joylashgan qismida qizdiring.",
      "Sovigach, mahsulotning bir qismiga xlorid kislota tomizib, gaz ajralishini tekshiring.",
    ],
    safe: "Qizigan shisha naychani sovimaguncha ushlamang; ko'zoynak taqing.",
    expl: "Asosli va kislotali oksidlar o'zaro birikib tuz hosil qiladi. Ohak havoda saqlanganda CO2 ni yutib, asta-sekin kalsiy karbonatga aylanadi — shuning uchun so'ndirilmagan ohak germetik idishda saqlanadi.",
    q: ["Oksidlarning o'zaro ta'siriga yana qanday misollar keltira olasiz?", "Mahsulot tarkibida karbonat borligini qanday isbotlash mumkin?"],
    conf: "o'rta",
  }),
  R({
    t: "Kalsiy oksidning kremniy(IV) oksid bilan suyuqlantirilishi", lvl: '9-sinf', topic: T_OXOX, engine: 'record',
    re: [solid('CaO', 0.3), solid('SiO2', 0.3)], heat_c: true, tmin: 1000,
    note: "Reaksiya juda yuqori haroratda (taxminan 1000 °C dan yuqori), sanoatda — domna pechida shlak hosil bo'lishida boradi.",
    mol: 'CaO + SiO2 = CaSiO3',
    mech: 'birikish', steps: [
      "Asosli oksid CaO kislotali oksid SiO2 bilan suyuqlanmada birikadi.",
      "Silikat ioni hosil bo'lib, tuz — kalsiy silikat (shlak) hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['glow'],
    obs: "Aralashma juda yuqori haroratda suyuqlanib, sovigach shishasimon (shlak) massaga aylanadi.",
    kin: "o'rtacha", app: ['tigel', 'tigel-qisqichi', 'mufel-pechi'],
    proc: [
      "Tigelda kalsiy oksid va qum aralashmasini tayyorlang.",
      "Tigelni mufel pechida juda yuqori haroratgacha qizdiring.",
      "Sovigach hosil bo'lgan massani kuzating.",
    ],
    safe: "Yuqori haroratli pech bilan faqat o'qituvchi ishlaydi; maxsus qo'lqop va tigel qisqichidan foydalaning.",
    expl: "Asosli oksid CaO va kislotali oksid SiO2 yuqori haroratda birikib kalsiy silikat hosil qiladi. Metallurgiyada ohaktosh flyus sifatida qo'shiladi: u ruda tarkibidagi qum bilan oson suyuqlanadigan shlak hosil qiladi.",
    q: ["Domna pechiga ohaktosh nima uchun qo'shiladi?", "Bu reaksiyada qaysi oksid asosli, qaysi biri kislotali?"],
    conf: "o'rta",
  }),
  R({
    t: "Natriy oksidning karbonat angidrid bilan birikishi", lvl: '8-sinf', topic: T_OXOX, engine: 'record',
    re: [solid('Na2O', 0.3), gasR('CO2')],
    note: "Quruq natriy oksid quruq CO2 bilan ta'sirlashadi.",
    mol: 'Na2O + CO2 = Na2CO3',
    mech: 'birikish', steps: [
      "Kuchli asosli oksid Na2O kislotali oksid CO2 ni oson biriktiradi.",
      "O²⁻ ioni CO2 ga birikib karbonat ioni hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: [],
    obs: "Oq kukun ko'rinishi deyarli o'zgarmaydi, lekin natriy karbonatga aylanadi; mahsulot kislota ta'sirida gaz ajratadi.",
    kin: 'tez', app: ['chinni-kosacha', 'gaz-naycha-egilgan', 'kipp-apparati'],
    proc: [
      "Quruq chinni kosachaga ozroq natriy oksid soling.",
      "Kukun ustiga quruq CO2 oqimini yuboring.",
      "Mahsulotning bir qismini suvda eritib, xlorid kislota qo'shing va gaz ajralishini kuzating.",
    ],
    safe: "Natriy oksid o'yuvchi: qo'lqop va ko'zoynakdan foydalaning.",
    expl: "Asosli oksid kislotali oksid bilan birikib tuz hosil qiladi. Natriy oksid kuchli asosli bo'lgani uchun havodagi CO2 va namlikni yutadi, shuning uchun germetik idishda saqlanadi.",
    q: ["Nima uchun Na2O ochiq havoda saqlanmaydi?", "Oksidlarning o'zaro ta'sirida qanday mahsulot hosil bo'ladi?"],
  }),
  R({
    t: "Kalsiy oksidning fosfor(V) oksid bilan birikishi", lvl: '9-sinf', topic: T_OXOX, engine: 'record',
    re: [solid('CaO', 0.3), solid('P2O5', 0.25)], heat_c: true,
    note: "Quruq oksidlar aralashmasi tigelda qizdiriladi.",
    mol: '3CaO + P2O5 = Ca3(PO4)2',
    mech: 'birikish', steps: [
      "Asosli oksid CaO va kislotali oksid P2O5 qizdirilganda bevosita birikadi.",
      "Oksid ionlari P2O5 bilan ortofosfat ionlarini hosil qiladi.",
      "Natijada tuz — kalsiy ortofosfat hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['glow'],
    obs: "Quruq oq kukunlar aralashmasi qizdirilganda qiziydi va oq qattiq massaga aylanadi.",
    kin: "o'rtacha", app: ['tigel', 'tigel-qisqichi', 'chinni-uchburchak', 'uchoyoq', 'bunzen-gorelkasi'],
    proc: [
      "Quruq tigelga kalsiy oksid va fosfor(V) oksid aralashmasini soling (P2O5 ni namlikdan saqlang).",
      "Tigelni chinni uchburchakka qo'yib qizdiring.",
      "Sovigach hosil bo'lgan massani kuzating.",
    ],
    safe: "P2O5 namlik bilan shiddatli reaksiyaga kirishadi va terini kuydiradi: quruq asboblar bilan ishlang, ko'zoynak va qo'lqop taqing.",
    expl: "Asosli va kislotali oksidlar o'zaro ta'sirlashib tuz hosil qiladi. Kalsiy ortofosfat suyak va fosforitlar tarkibiga kiradi.",
    q: ["Kalsiy ortofosfat tabiatda qanday minerallar tarkibida uchraydi?", "CaO va P2O5 ning qanday nisbatida o'rta tuz hosil bo'ladi?"],
    conf: "o'rta",
  }),
  R({
    t: "Kalsiy oksidning oltingugurt(VI) oksid bilan birikishi", lvl: '9-sinf', topic: T_OXOX, engine: 'record',
    re: [solid('CaO', 0.3), solid('SO3', 0.4, 'kristall')],
    note: "Quruq oksidlar o'zaro ta'sirlashadi; namoyish o'qituvchi tomonidan mo'rili shkafda o'tkaziladi.",
    mol: 'CaO + SO3 = CaSO4',
    mech: 'birikish', steps: [
      "Asosli oksid CaO kuchli kislotali oksid SO3 bilan bevosita birikadi.",
      "O²⁻ ioni SO3 ga birikib sulfat ionini hosil qiladi.",
      "Tuz — kalsiy sulfat hosil bo'ladi.",
    ],
    heat: 'ekzotermik', fx: ['heat-haze'],
    obs: "Oksidlar aralashtirilganda massa qiziydi va oq qattiq tuzga aylanadi.",
    kin: 'tez', app: ['chinni-kosacha', 'shpatel'],
    proc: [
      "Quruq chinni kosachaga kalsiy oksid kukunini soling.",
      "Mo'rili shkafda ustiga oz miqdorda oltingugurt(VI) oksid qo'shing va quruq shpatel bilan aralashtiring.",
      "Isish va mahsulot ko'rinishini kuzating.",
    ],
    safe: "SO3 juda o'yuvchi va havodagi namlik bilan sulfat kislota tumanini hosil qiladi: faqat mo'rili shkafda, ko'zoynak va qo'lqopda ishlang.",
    expl: "Asosli va kislotali oksidlar suvsiz sharoitda bevosita birikib tuz hosil qiladi. Oksidlarning kislota-asos xossalari qanchalik farq qilsa, ular shunchalik oson ta'sirlashadi.",
    q: ["Oksidlar o'zaro ta'sirlashganda nima uchun tuz hosil bo'ladi?", "CaO ning SO2 bilan reaksiyasida qanday tuz hosil bo'ladi?"],
    conf: "o'rta",
  }),
];

list.forEach((r, i) => { r.id = `${PREFIX}-${String(i + 1).padStart(4, '0')}`; });
const out = join(DATA, 'reactions', `${CAT}.json`);
writeFileSync(out, JSON.stringify({ category: CAT, reactions: list }, null, 1) + '\n');
console.log(`${list.length} ta yozuv yozildi: ${out}`);
