// "Uglevodorodlar" toifasi tajribalari generatori.
// Ishga tushirish: node tools/seed/reactions/uglevodorodlar.mjs
// Natija: frontend/lab/data/reactions/uglevodorodlar.json (uglevod-0001 namunasi o'zgarishsiz saqlanadi).
// Shu fayl spirtlar-fenollar.mjs va aldegid-ketonlar.mjs uchun umumiy yordamchilarni ham eksport qiladi.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
export const DATA = join(ROOT, 'frontend', 'lab', 'data');
const SUBS = JSON.parse(readFileSync(join(DATA, 'substances.json'), 'utf8'));

/** Cho'kma kuzatuvi: rang bazadan olinadi */
export function ppt(id, texture) {
  const s = SUBS[id];
  if (!s) throw new Error(`modda yo'q: ${id}`);
  return { species: id, color: s.precipitate?.color || s.appearance?.color, texture: texture || s.precipitate?.texture || 'mayda-kristall' };
}
export function gas(id, desc = null) { return { species: id, desc_uz: desc }; }

/** Qisqa yozuvdan to'liq tajriba yozuvini yasash */
export function mk(category, o) {
  const cond = { heating: false, temp_min_C: null, catalyst: null, medium: null, light: false, note_uz: null, ...(o.cond || {}) };
  if (cond.temp_min_C && o.cond?.heating === undefined) cond.heating = true;
  const r = {
    id: o.id,
    category,
    title_uz: o.title,
    level: o.level,
    topic_uz: o.topic,
    engine: o.engine || 'record',
  };
  if (o.no_reaction) { r.no_reaction = true; r.match = o.match; }
  if (o.equation_free) { r.equation_free = true; r.equation_free_uz = o.equation_free; }
  if (o.extra) Object.assign(r, o.extra);
  Object.assign(r, {
    reactants: o.reactants,
    conditions: cond,
    equation: { molecular: o.eq?.[0] ?? null, ionic_full: o.eq?.[1] ?? null, ionic_net: o.eq?.[2] ?? null, electron_balance: o.eq?.[3] ?? null },
    mechanism: { type: o.mtype || 'organik', steps_uz: o.steps, organic: o.tpl ? { template: o.tpl, params: o.params } : null },
    observations: {
      precipitate: o.ppt ?? null,
      gas: o.gas ?? null,
      solution_color_change: o.color ? { from: o.color[0], to: o.color[1] } : null,
      ...(o.solid ? { solid_color_change: { from: o.solid[0], to: o.solid[1] } } : {}),
      heat: o.heat || 'sezilarsiz',
      flame: o.flame ?? null,
      effects: (o.effects || []).map((type) => ({ type })),
      text_uz: o.text,
    },
    kinetics: o.kin || 'tez',
    apparatus: o.app,
    procedure_uz: o.proc,
    safety_uz: o.safety,
    explanation_uz: o.expl,
    questions_uz: o.q,
    confidence: o.conf || 'yuqori',
  });
  return r;
}

export function writeCategory(category, records, keep = []) {
  const out = { category, reactions: [...keep, ...records] };
  const path = join(DATA, 'reactions', `${category}.json`);
  writeFileSync(path, JSON.stringify(out, null, 1) + '\n');
  console.log(`${category}: ${out.reactions.length} ta yozuv -> ${path}`);
}

// Umumiy rang va xavfsizlik matnlari
export const COL = {
  bromliSuv: '#e8a040', rangsiz: '#ffffff', kmno4: '#8e1a8e', mno2Loyqa: '#b09070', dixromat: '#ef7d1a', xrom3: '#5f8a6e', feling: '#2a4ad0',
};
export const SAFE = {
  brom: "Brom zaharli va terini kuydiradi; bromli suv bilan mo'rili shkafda ishlang, bug'ini hidlamang.",
  benzol: "Benzol kanserogen va oson alangalanadi: tajribani faqat o'qituvchi mo'rili shkafda namoyish qiladi; ochiq alangadan uzoqda saqlang.",
  yonuvchi: "Uglevodorodlar oson alangalanadi; idishlarni ochiq alangadan uzoqda tuting, gaz yondirishdan oldin uning tozaligini sinov probirkasida tekshiring.",
  kmno4: "Kaliy permanganat kuchli oksidlovchi, terini va kiyimni bo'yaydi; ko'zoynak taqing.",
};

// ---------------------------------------------------------------------------------------------
const CAT = 'uglevodorodlar';
const R = (o) => mk(CAT, o);

const records = [
  // ===================== ALKANLAR =====================
  R({
    id: 'uglevod-0003', title: 'Propanning yonishi (suyultirilgan maishiy gaz)', level: '10-sinf', topic: 'Alkanlar: yonish reaksiyasi',
    reactants: [{ species: 'C3H8', state: 'g' }, { species: 'O2', state: 'g' }],
    cond: { ignition: true, ignition_C: 500, note_uz: "Propan (zajigalka yoki ballon gazi) naycha uchida yondiriladi." },
    eq: ['C3H8 + 5O2 → 3CO2↑ + 4H2O'],
    tpl: 'oksidlanish', params: { substrate: 'CH3–CH2–CH3', oxidant: 'O2', product: 'CO2 + H2O' },
    steps: ["Alangada C–C va C–H bog'lari uzilib, alkil radikallar hosil bo'ladi.", "Radikal zanjir orqali uglerod atomlari CO₂ gacha, vodorod atomlari H₂O gacha oksidlanadi.", "1 mol propan yonishi uchun 5 mol kislorod sarflanadi — havo yetishmasa is gazi (CO) va qurum hosil bo'ladi."],
    gas: gas('CO2'),
    heat: 'kuchli-ekzotermik', flame: { color: '#4a70f0', desc_uz: "havo yetarli bo'lsa ko'k, yetishmasa sarg'ish alanga" },
    effects: ['flame', 'condensate', 'heat-haze'],
    text: "Propan ko'k alanga bilan yonadi, ko'p issiqlik ajraladi. Sovuq stakan devorida suv tomchilari to'planadi.",
    kin: 'bir-zumda',
    app: ['gaz-silindri', 'gaz-naycha-toraytirilgan', 'kimyoviy-stakan', 'gugurt'],
    proc: ["Propan chiqayotgan naycha uchini gugurt bilan yondiring.", "Havo kirishini o'zgartirib alanga rangini kuzating.", "Alanga ustida sovuq quruq stakan tutib, suv tomchilarini kuzating."],
    safety: SAFE.yonuvchi + " Propan havodan og'ir, pastda to'planadi — xonani shamollating.",
    expl: "Propan — to'yingan uglevodorod, havoda to'liq yonib CO₂ va H₂O hosil qiladi. Maishiy gazdagi propan-butan aralashmasi bosim ostida suyultirilib saqlanadi; havo yetishmasa to'liq yonmaydi va zaharli is gazi hosil bo'ladi.",
    q: ["Propanning yonish tenglamasini tuzing va kislorod hajmini hisoblang (1 L propan uchun).", "To'liqsiz yonishda qanday mahsulotlar hosil bo'ladi?"],
  }),
  R({
    id: 'uglevod-0004', title: "Metanning yorug'likda xlorlanishi", level: '10-sinf', topic: "Alkanlar: radikal o'rin olish (S_R) reaksiyasi",
    reactants: [{ species: 'CH4', state: 'g' }, { species: 'Cl2', state: 'g' }],
    cond: { light: true, note_uz: "Metan va xlor aralashmasi solingan silindr sochilgan yorug'likka (yoki UB lampa ostiga) qo'yiladi." },
    eq: ['CH4 + Cl2 → CH3Cl + HCl↑'],
    tpl: 'SR', params: { substrate: 'CH4', reagent: 'Cl–Cl', radical: 'Cl•', alkyl_radical: '•CH3', product: 'CH3Cl', byproduct: 'HCl' },
    steps: ["Zanjirning boshlanishi: yorug'lik kvanti Cl–Cl bog'ini gomolitik uzadi — har bir atom bitta elektronni olib, ikkita Cl• radikali hosil bo'ladi.", "Zanjirning o'sishi: Cl• metandan vodorod atomini tortib oladi (HCl), metil radikali •CH₃ hosil bo'ladi.", "•CH₃ Cl₂ molekulasidan xlor atomini oladi: CH₃Cl va yangi Cl• hosil bo'lib zanjir davom etadi.", "Zanjirning uzilishi: ikki radikal juftlashib (Cl• + Cl•, •CH₃ + Cl•) zanjir to'xtaydi."],
    gas: gas('HCl', "rangsiz, nam havoda tutaydi; suvda juda yaxshi eriydi"),
    heat: 'ekzotermik', effects: ['fog', 'condensate'],
    text: "Silindrdagi xlorning sarg'ish-yashil rangi asta-sekin yo'qoladi, devorlarda moysimon tomchilar (CH₂Cl₂, CHCl₃, CCl₄) paydo bo'ladi. Silindr suvga botirilganda suv ko'tariladi (HCl eriydi), suvga ko'k lakmus qo'shilsa qizaradi.",
    kin: "o'rtacha",
    app: ['gaz-silindri', 'pnevmatik-vanna', 'yoritgich'],
    proc: ["Silindrni to'yingan osh tuzi eritmasi ustida metan va xlor bilan (hajmlar nisbati 1:1) to'ldiring.", "Silindrni sochilgan yorug'likka yoki lampa ostiga qo'ying.", "Bir necha daqiqadan so'ng gaz rangi, devordagi tomchilar va suyuqlik sathini kuzating.", "Silindrdagi suyuqlikka ko'k lakmus qog'ozini tekkizing."],
    safety: "Xlor zaharli — tajriba mo'rili shkafda o'tkaziladi. Aralashmani to'g'ri quyosh nuriga qo'ymang: kuchli yorug'likda reaksiya portlash bilan ketishi mumkin.",
    expl: "Alkanlar uchun eng xarakterli reaksiya — o'rin olish. Yorug'lik xlor molekulasini radikallarga parchalaydi va zanjirli radikal reaksiya boshlanadi; vodorod atomlari ketma-ket xlorga almashinib, aralashmada CH₃Cl, CH₂Cl₂, CHCl₃ va CCl₄ hosil bo'ladi. Ajralgan HCl suvda eriydi, shuning uchun silindrda suv ko'tariladi.",
    q: ["Nima uchun xlorlanish qorong'ida ketmaydi?", "Zanjirli reaksiyaning boshlanish, o'sish va uzilish bosqichlarini yozing.", "Metanni xlorlashda qanday mahsulotlar aralashmasi hosil bo'ladi?"],
  }),
  R({
    id: 'uglevod-0005', title: "Metan va xlorning qorong'ida reaksiyaga kirishmasligi", level: '10-sinf', topic: "Alkanlar: radikal reaksiyalar sharoiti",
    no_reaction: true, match: ['CH4', 'Cl2'],
    reactants: [{ species: 'CH4', state: 'g' }, { species: 'Cl2', state: 'g' }],
    cond: { note_uz: "Aralashma qorong'i joyda (yoki qora qog'ozga o'ralgan silindrda) saqlanadi." },
    steps: ["Xona haroratida va yorug'liksiz Cl–Cl bog'i uzilmaydi — radikal hosil bo'lmaydi.", "Erkin radikal bo'lmagani uchun zanjirli reaksiya boshlanmaydi."],
    text: "Qorong'ida xlorning sarg'ish-yashil rangi saqlanib qoladi, hech qanday o'zgarish kuzatilmaydi.",
    kin: 'bir-zumda',
    app: ['gaz-silindri', 'pnevmatik-vanna'],
    proc: ["Ikki silindrni metan va xlor aralashmasi bilan to'ldiring.", "Birini qora qog'ozga o'rab qorong'ida qoldiring, ikkinchisini yorug'likka qo'ying.", "Bir necha daqiqadan keyin ikkala silindrni solishtiring."],
    safety: "Xlor zaharli — mo'rili shkafda ishlang; silindrlarni ochishda gazni hidlamang.",
    expl: "Metanning xlor bilan o'rin olish reaksiyasi radikal zanjir mexanizmi bo'yicha boradi va uni boshlash uchun energiya — yorug'lik yoki qizdirish kerak. Qorong'ida va xona haroratida xlor molekulalari radikallarga parchalanmaydi, shuning uchun reaksiya amalda ketmaydi.",
    q: ["Bu tajriba reaksiya mexanizmi haqida nimani isbotlaydi?", "Qanday sharoitda metan va xlor reaksiyaga kirishadi?"],
  }),
  R({
    id: 'uglevod-0006', title: "Xlormetanning keyingi xlorlanishi (dixlormetan hosil bo'lishi)", level: 'litsey', topic: "Alkanlar: ketma-ket radikal xlorlanish",
    reactants: [{ species: 'CH3Cl', state: 'g' }, { species: 'Cl2', state: 'g' }],
    cond: { light: true, note_uz: "Gazlar aralashmasi UB lampa bilan yoritiladi." },
    eq: ['CH3Cl + Cl2 → CH2Cl2 + HCl↑'],
    tpl: 'SR', params: { substrate: 'CH3Cl', reagent: 'Cl–Cl', radical: 'Cl•', alkyl_radical: '•CH2Cl', product: 'CH2Cl2', byproduct: 'HCl' },
    steps: ["Yorug'lik ta'sirida Cl₂ gomolitik uzilib Cl• radikallari hosil bo'ladi.", "Cl• xlormetandan vodorod atomini tortib oladi: HCl va •CH₂Cl radikali hosil bo'ladi.", "•CH₂Cl radikali Cl₂ dan xlor atomini oladi, CH₂Cl₂ va yangi Cl• hosil bo'ladi."],
    gas: gas('HCl'),
    heat: 'ekzotermik', effects: ['fog', 'condensate'],
    text: "Xlorning rangi yo'qoladi, idish devorlarida rangsiz uchuvchan suyuqlik tomchilari (dixlormetan) paydo bo'ladi, nam havoda HCl tumani ko'rinadi.",
    kin: "o'rtacha",
    app: ['gaz-silindri', 'yoritgich'],
    proc: ["Silindrni xlormetan va xlor bilan (1:1) to'ldiring.", "Silindrni lampa bilan yoriting.", "Rang o'zgarishi va devordagi tomchilarni kuzating."],
    safety: "Xlor va xlormetan zaharli: faqat mo'rili shkafda, o'qituvchi namoyishi sifatida.",
    expl: "Metanni xlorlash bir bosqichda to'xtamaydi: hosil bo'lgan xlormetan ham radikal o'rin olishga kirishib dixlormetan, so'ng trixlormetan va tetraxlormetan hosil qiladi. Mahsulotlar nisbatini metan va xlor nisbati boshqaradi — xlor ko'p bo'lsa ko'proq xlorlangan mahsulotlar hosil bo'ladi.",
    q: ["Metanning to'rtala xlorli hosilasini nomlang.", "Asosan CH₃Cl olish uchun metan va xlor nisbatini qanday tanlash kerak?"],
  }),
  R({
    id: 'uglevod-0007', title: 'Xloroformning tetraxlormetangacha xlorlanishi', level: 'litsey', topic: "Alkanlar: ketma-ket radikal xlorlanish",
    reactants: [{ species: 'CHCl3', state: 'l', volume_mL: 2 }, { species: 'Cl2', state: 'g' }],
    cond: { light: true, note_uz: "Xlor xloroform orqali UB nuri ostida o'tkaziladi." },
    eq: ['CHCl3 + Cl2 → CCl4 + HCl↑'],
    tpl: 'SR', params: { substrate: 'CHCl3', reagent: 'Cl–Cl', radical: 'Cl•', alkyl_radical: '•CCl3', product: 'CCl4', byproduct: 'HCl' },
    steps: ["Yorug'lik Cl₂ ni ikki Cl• radikaliga ajratadi.", "Cl• xloroformdagi yagona vodorod atomini tortib oladi: HCl va •CCl₃ radikali hosil bo'ladi.", "•CCl₃ Cl₂ bilan ta'sirlashib CCl₄ va yangi Cl• hosil qiladi."],
    gas: gas('HCl'),
    heat: 'ekzotermik', effects: ['bubbles', 'fog'],
    text: "Xlor pufakchalari suyuqlik orqali o'tadi, idish og'zidan HCl tumani chiqadi; suyuqlik hajmi deyarli o'zgarmaydi (CCl₄ ham rangsiz suyuqlik).",
    kin: 'sekin',
    app: ['probirka', 'gaz-naycha-egilgan', 'yoritgich', 'shtativ'],
    proc: ["Probirkaga 2 ml xloroform quying va shtativga mahkamlang.", "Gaz naychasi orqali xlorni sekin o'tkazing va probirkani UB lampa bilan yoriting.", "Chiqayotgan gazga nam ko'k lakmus qog'ozini tuting."],
    safety: "Xloroform, CCl₄ va xlor zaharli — faqat mo'rili shkafda, o'qituvchi namoyishi.",
    expl: "Metanni xlorlashning oxirgi bosqichida xloroformdagi so'nggi vodorod atomi ham xlorga almashadi. Tetraxlormetan yonmaydigan erituvchi; endi vodorod atomi qolmagani uchun radikal xlorlanish shu yerda tugaydi.",
    q: ["CCl₄ ni xlorlash mumkinmi? Nima uchun?", "HCl ajralishini qanday aniqlash mumkin?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0008', title: "Etanning yorug'likda bromlanishi", level: '10-sinf', topic: "Alkanlar: radikal o'rin olish (S_R)",
    reactants: [{ species: 'C2H6', state: 'g' }, { species: 'Br2', state: 'l', volume_mL: 0.5 }],
    cond: { light: true, note_uz: "Etan brom bug'lari bilan aralashtirilib yoritiladi." },
    eq: ['C2H6 + Br2 → C2H5Br + HBr↑'],
    tpl: 'SR', params: { substrate: 'CH3–CH3', reagent: 'Br–Br', radical: 'Br•', alkyl_radical: '•CH2–CH3', product: 'CH3–CH2Br', byproduct: 'HBr' },
    steps: ["Yorug'lik Br–Br bog'ini gomolitik uzadi: 2Br•.", "Br• etandan vodorod atomini tortib oladi — HBr va etil radikali •C₂H₅ hosil bo'ladi.", "•C₂H₅ Br₂ dan brom atomini olib brometan va yangi Br• hosil qiladi.", "Radikallar juftlashganda zanjir uziladi."],
    gas: gas('HBr', "rangsiz, nam havoda tutaydigan gaz"),
    heat: 'sezilarsiz', effects: ['fog'],
    text: "Brom bug'larining qizg'ish-qo'ng'ir rangi asta-sekin yo'qoladi, nam havoda HBr tumani hosil bo'ladi.",
    kin: 'sekin',
    app: ['gaz-silindri', 'tomizgich', 'yoritgich'],
    proc: ["Etan bilan to'ldirilgan silindrga bir tomchi brom tomizing va yopib qo'ying.", "Silindrni lampa bilan yoriting.", "Brom bug'lari rangining o'zgarishini kuzating; chiqqan gazga nam ko'k lakmus tuting."],
    safety: SAFE.brom,
    expl: "Brom xlorga nisbatan sustroq reagent bo'lgani uchun alkanlarni bromlash sekinroq boradi, lekin mexanizm bir xil — radikal zanjir. Brom rangining yo'qolishi alkanlar ham yorug'likda galogenlar bilan o'rin olish reaksiyasiga kirishishini ko'rsatadi.",
    q: ["Nima uchun alkanlar bromli suvni qorong'ida rangsizlantirmaydi, yorug'likda esa brom bilan reaksiyaga kirishadi?", "Brom bilan xlorning alkanlarga ta'sirini solishtiring."],
  }),
  R({
    id: 'uglevod-0009', title: "Propanning bromlanishi: radikallar barqarorligi va tanlovchanlik", level: 'universitet', topic: "Alkanlar: radikal o'rin olishning tanlovchanligi",
    reactants: [{ species: 'C3H8', state: 'g' }, { species: 'Br2', state: 'l', volume_mL: 0.5 }],
    cond: { light: true, note_uz: "Propan va brom bug'lari aralashmasi yoritiladi." },
    eq: ['C3H8 + Br2 → CH3CHBrCH3 + HBr↑'],
    tpl: 'SR', params: { substrate: 'CH3–CH2–CH3', reagent: 'Br–Br', radical: 'Br•', alkyl_radical: 'CH3–•CH–CH3', product: 'CH3–CHBr–CH3', byproduct: 'HBr' },
    steps: ["Yorug'lik ta'sirida Br₂ dan Br• radikallari hosil bo'ladi.", "Br• asosan ikkilamchi uglerod atomidagi vodorodni tortib oladi, chunki ikkilamchi radikal CH₃–•CH–CH₃ birlamchi radikaldan barqarorroq.", "Ikkilamchi radikal Br₂ bilan ta'sirlashib 2-brompropan va yangi Br• hosil qiladi."],
    gas: gas('HBr'),
    heat: 'sezilarsiz', effects: ['fog'],
    text: "Brom bug'larining rangi asta-sekin yo'qoladi, HBr tumani hosil bo'ladi; mahsulot asosan 2-brompropandan iborat.",
    kin: 'sekin',
    app: ['gaz-silindri', 'tomizgich', 'yoritgich'],
    proc: ["Propan bilan to'ldirilgan silindrga bir tomchi brom tomizing.", "Silindrni yoriting va rang o'zgarishini kuzating.", "Mahsulotlar tarkibini (1- va 2-brompropan) muhokama qiling."],
    safety: SAFE.brom,
    expl: "Brom kam faol va shuning uchun tanlovchan reagent: u eng barqaror (ikkilamchi) radikal hosil bo'ladigan C–H bog'ini uzadi. Shu sababli propanni bromlaganda asosiy mahsulot 2-brompropan bo'ladi; xlorlashda esa tanlovchanlik ancha past va ikkala izomer sezilarli miqdorda hosil bo'ladi.",
    q: ["Radikallarni barqarorlik bo'yicha qatorga joylashtiring: birlamchi, ikkilamchi, uchlamchi.", "Nima uchun bromlash xlorlashga qaraganda tanlovchanroq?"],
  }),
  R({
    id: 'uglevod-0010', title: "Metanning bromli suvni rangsizlantirmasligi", level: '10-sinf', topic: "Alkanlar va alkenlarni farqlash",
    no_reaction: true, match: ['CH4', 'Br2'],
    reactants: [{ species: 'CH4', state: 'g' }, { species: 'bromli-suv', state: 'aq', volume_mL: 3 }],
    cond: { note_uz: "Metan bromli suv orqali o'tkaziladi." },
    steps: ["Metan molekulasida faqat mustahkam σ-bog'lar bor, π-bog' yo'q.", "Elektrofil brom hujum qila oladigan elektron zichligi bo'lmagani uchun birikish ketmaydi; qorong'ida radikal o'rin olish ham boshlanmaydi."],
    effects: ['bubbles'],
    text: "Metan pufakchalari o'tadi, lekin bromli suvning sariq-qo'ng'ir rangi saqlanib qoladi.",
    kin: 'bir-zumda',
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 3 ml bromli suv quying.", "Gaz naychasi orqali metan o'tkazing.", "Eritma rangini etilen o'tkazilgan probirka bilan solishtiring."],
    safety: SAFE.brom,
    expl: "To'yingan uglevodorodlarda qo'shbog' bo'lmagani uchun ular bromli suv va kaliy permanganat eritmasini rangsizlantirmaydi. Bu xossa alkanlarni to'yinmagan uglevodorodlardan farqlashda ishlatiladi.",
    q: ["Metan va etilenni qanday reaksiya yordamida farqlash mumkin?", "Qanday sharoitda metan brom bilan reaksiyaga kirishadi?"],
  }),
  R({
    id: 'uglevod-0011', title: "Geksanning kaliy permanganat eritmasini rangsizlantirmasligi", level: '10-sinf', topic: "Alkanlarning oksidlovchilarga chidamliligi",
    no_reaction: true, match: ['C6H14', 'MnO4⁻'],
    reactants: [{ species: 'C6H14', state: 'l', volume_mL: 1 }, { species: 'KMnO4', state: 'aq', conc_M: 0.02, volume_mL: 2 }],
    steps: ["Geksan molekulasida faqat qutbsiz va mustahkam C–C hamda C–H σ-bog'lari bor.", "Permanganat ioni xona haroratida bu bog'larni oksidlay olmaydi; geksan suvda erimay alohida qatlam hosil qiladi."],
    effects: ['layers'],
    text: "Ikki qatlam hosil bo'ladi: yuqorida rangsiz geksan, pastda binafsha rangli permanganat eritmasi. Chayqatilgandan keyin ham rang o'zgarmaydi.",
    kin: 'bir-zumda',
    app: ['probirka', 'tomizgich'],
    proc: ["Probirkaga 2 ml suyultirilgan KMnO₄ eritmasidan quying.", "Ustiga 1 ml geksan qo'shing va chayqating.", "Qatlamlarni va eritma rangini kuzating."],
    safety: SAFE.yonuvchi + ' ' + SAFE.kmno4,
    expl: "Alkanlar odatdagi sharoitda kuchli oksidlovchilar (KMnO₄, K₂Cr₂O₇) ta'siriga chidamli, shuning uchun ularni \"parafinlar\" (kam faol) deb atashgan. Permanganat rangining saqlanishi moddada qo'shbog' yoki uchbog' yo'qligini ko'rsatadi.",
    q: ["Qaysi uglevodorodlar KMnO₄ eritmasini rangsizlantiradi?", "Geksan suvda eriydimi? Qaysi qatlam yuqorida turadi va nima uchun?"],
  }),
  R({
    id: 'uglevod-0012', title: "Geksanning qorong'ida bromli suv bilan reaksiyaga kirishmasligi (brom ekstraksiyasi)", level: '10-sinf', topic: "Alkanlar: to'yinganlikni aniqlash",
    no_reaction: true, match: ['C6H14', 'Br2'],
    reactants: [{ species: 'C6H14', state: 'l', volume_mL: 1 }, { species: 'bromli-suv', state: 'aq', volume_mL: 3 }],
    cond: { note_uz: "Probirka qorong'ida chayqatiladi." },
    steps: ["Geksanda π-bog' yo'q, shuning uchun bromning elektrofil birikishi ketmaydi.", "Brom qutbsiz modda bo'lgani uchun suvdan ko'ra geksanda yaxshiroq eriydi va organik qatlamga o'tadi (fizik jarayon — ekstraksiya)."],
    effects: ['layers'],
    text: "Chayqatilgandan so'ng suv qatlami deyarli rangsizlanadi, yuqoridagi geksan qatlami esa sariq-to'q sariq rangga bo'yaladi. Brom yo'qolmaydi — u geksan qatlamiga o'tadi.",
    kin: 'bir-zumda',
    app: ['probirka', 'tomizgich'],
    proc: ["Probirkaga 3 ml bromli suv quying.", "Ustiga 1 ml geksan qo'shing, tiqin bilan berkitib chayqating.", "Qatlamlar ajralgach, har bir qatlam rangini kuzating."],
    safety: SAFE.brom + ' Geksan oson alangalanadi.',
    expl: "Bu tajribada kimyoviy reaksiya ketmaydi: bromli suvning rangsizlanishi alkenlardagidek birikish emas, balki bromning geksan qatlamiga ekstraksiyasidir. Agar organik qatlam ham rangsiz bo'lib qolsa — reaksiya ketgan bo'ladi; geksan bilan esa bu faqat yorug'lik ta'sirida sekin o'rin olish (HBr ajralishi) bilan sodir bo'ladi.",
    q: ["Bromli suvning \"rangsizlanishi\" har doim ham reaksiya belgisimi?", "Etilen va geksanning bromli suvga ta'sirini qanday farqlash mumkin?"],
  }),
  R({
    id: 'uglevod-0013', title: "Yodli suvdan yodni geksan bilan ekstraksiya qilish", level: '9-sinf', topic: "Moddalarni ajratish: ekstraksiya, erituvchilarda eruvchanlik",
    engine: 'rules', equation_free: "Kimyoviy reaksiya ketmaydi: yod qutbsiz erituvchi (geksan) da suvdagidan ancha yaxshi eriydi va organik qatlamga o'tadi (taqsimlanish).",
    reactants: [{ species: 'yodli-suv', state: 'aq', volume_mL: 5 }, { species: 'C6H14', state: 'l', volume_mL: 1 }],
    mtype: 'fizik',
    steps: ["Yod molekulasi I₂ qutbsiz, suv esa qutbli erituvchi — shuning uchun yod suvda yomon eriydi.", "Qutbsiz geksan bilan chayqatilganda yod molekulalari organik qatlamga o'tadi (\"o'xshash o'xshashda eriydi\").", "Geksan suvda erimaydi va zichligi kichik bo'lgani uchun yuqori qatlamni hosil qiladi."],
    color: ['#c08a50', '#ffffff'],
    effects: ['layers'],
    text: "Chayqatilgach suv qatlami deyarli rangsizlanadi, yuqoridagi geksan qatlami esa binafsha-pushti rangga kiradi.",
    kin: 'tez',
    app: ['ajratgich-voronka', 'shtativ', 'shtativ-halqasi', 'kimyoviy-stakan'],
    proc: ["Ajratgich voronkaga 5 ml yodli suv quying.", "Unga 1 ml geksan qo'shing, voronkani berkitib chayqating va vaqti-vaqti bilan bosimni chiqarib turing.", "Qatlamlar ajralgach, pastki suv qatlamini stakanga tushiring.", "Ikkala qatlam rangini solishtiring."],
    safety: "Geksan oson alangalanadi va bug'i zararli: ochiq alangadan uzoqda, shamollatiladigan joyda ishlang.",
    expl: "Ekstraksiya — moddani bir erituvchidan unda aralashmaydigan ikkinchi erituvchiga o'tkazish usuli. Yod qutbsiz geksanda yaxshi erigani uchun deyarli butunlay organik qatlamga o'tadi va o'ziga xos binafsha rang beradi; bu usul dengiz suvi va o'simliklardan yod ajratishda ham qo'llaniladi.",
    q: ["Nima uchun geksan qatlami yuqorida turadi?", "Yodning suvdagi va geksandagi eritmalari rangi nega har xil?"],
  }),
  R({
    id: 'uglevod-0015', title: "Alyuminiy karbidning gidrolizi — metan olish", level: '10-sinf', topic: "Alkanlarni olish: karbidlar gidrolizi",
    reactants: [{ species: 'Al4C3', state: 's', mass_g: 0.5 }, { species: 'H2O', state: 'l', volume_mL: 3 }],
    cond: { note_uz: "Reaksiyani tezlashtirish uchun suv ozgina iliqlashtiriladi." },
    eq: ['Al4C3 + 12H2O → 4Al(OH)3↓ + 3CH4↑'],
    mtype: 'gidroliz',
    steps: ["Alyuminiy karbiddagi uglerod C⁻⁴ holatda — u kuchli asos sifatida suvdan protonlarni tortib oladi.", "Har bir uglerod atomi to'rtta proton olib metan molekulasini hosil qiladi.", "Al³⁺ ionlari qolgan OH⁻ ionlari bilan oq iviqsimon Al(OH)₃ hosil qiladi."],
    ppt: ppt('Al(OH)3'),
    gas: gas('CH4'),
    heat: 'ekzotermik', effects: ['bubbles', 'turbidity'],
    text: "Sariq kulrang karbid bo'laklari yuzasidan gaz pufakchalari ajraladi, oq iviqsimon cho'kma hosil bo'ladi.",
    kin: 'sekin',
    app: ['probirka', 'gaz-naycha-egilgan', 'rezina-tiqin-1-teshikli-kichik', 'shtativ'],
    proc: ["Probirkaga ozroq alyuminiy karbid soling.", "Ustiga 3 ml iliq suv quying va gaz chiqarish naychali tiqin bilan berkiting.", "Gaz pufakchalari va cho'kmani kuzating; tozaligini tekshirgach gazni yondiring."],
    safety: "Ajraladigan metan yonuvchan: yaqin atrofda ochiq alanga bo'lmasin, yondirishdan oldin gaz tozaligini tekshiring.",
    expl: "Ion tuzilishli karbidlar suv bilan gidrolizlanib uglevodorod hosil qiladi: alyuminiy karbiddan metan, kalsiy karbiddan esa atsetilen olinadi. Qaysi uglevodorod hosil bo'lishi karbiddagi uglerod anionining tuzilishiga (C⁴⁻ yoki C₂²⁻) bog'liq.",
    q: ["Al₄C₃ va CaC₂ gidrolizi mahsulotlarini solishtiring.", "Al₄C₃ xlorid kislota bilan qanday reaksiyaga kirishadi?"],
  }),
  R({
    id: 'uglevod-0016', title: "Vyurs reaksiyasi: brometandan butan olish", level: 'litsey', topic: "Alkanlarni olish: Vyurs reaksiyasi",
    reactants: [{ species: 'C2H5Br', state: 'l', volume_mL: 1 }, { species: 'Na', state: 's', mass_g: 0.3, form: "bo'lak" }],
    cond: { note_uz: "Reaksiya quruq dietil efirda, mayda kesilgan natriy bilan o'tkaziladi." },
    eq: ['2C2H5Br + 2Na → C4H10↑ + 2NaBr'],
    tpl: 'SN2', params: { substrate: 'CH3–CH2Br', nucleophile: 'C2H5⁻ (C2H5Na)', leaving_group: 'Br⁻', product: 'CH3–CH2–CH2–CH3' },
    steps: ["Natriy atomi brometanga elektron berib, natriy bromid va etil radikali/etilnatriy C₂H₅Na hosil bo'ladi.", "Etilnatriydagi qutblangan C–Na bog'i tufayli etil guruhi kuchli nukleofil (karbanion) sifatida ta'sir qiladi.", "Karbanion ikkinchi brometan molekulasining uglerodiga hujum qiladi, Br⁻ ajralib chiqadi va yangi C–C bog'i hosil bo'ladi — butan."],
    gas: gas('C4H10'),
    heat: 'ekzotermik', effects: ['bubbles', 'turbidity'],
    text: "Natriy bo'laklari yuzasi xiralashadi, efirda oq NaBr cho'kmasi to'planadi, gaz (butan) ajraladi.",
    kin: 'sekin',
    app: ['dumaloq-tubli-kolba', 'sharikli-sovutgich', 'shtativ', 'qisqich-lapka'],
    proc: ["Kolbaga quruq dietil efir va mayda kesilgan natriy soling.", "Sovutgich orqali brometanni oz-ozdan qo'shing.", "Ajralayotgan gazni va kolbadagi oq cho'kmani kuzating."],
    safety: "Natriy suv bilan shiddatli reaksiyaga kirishadi — hamma idishlar quruq bo'lsin. Dietil efir juda oson alangalanadi: ochiq alanga yo'q joyda, faqat o'qituvchi namoyishi.",
    expl: "Galogenalkanlarga natriy metali ta'sir ettirilganda uglerod zanjiri ikki baravar uzayadi (Vyurs reaksiyasi). Bir xil galogenalkandan simmetrik alkan olinadi; ikki xil galogenalkan olinsa uch xil alkan aralashmasi hosil bo'ladi.",
    q: ["Brommetan va brometan aralashmasidan Vyurs reaksiyasida qaysi alkanlar hosil bo'ladi?", "Nima uchun reaksiya suvsiz sharoitda o'tkaziladi?"],
    conf: "o'rta",
  }),

  R({
    id: 'uglevod-x01', title: "Metanning termik parchalanishi — qurum va vodorod olish", level: '10-sinf', topic: "Alkanlar: termik parchalanish (piroliz)",
    reactants: [{ species: 'CH4', state: 'g' }],
    cond: { temp_min_C: 1000, note_uz: "Metan havosiz, ~1000 °C dan yuqori qizdirilgan naycha orqali o'tkaziladi." },
    eq: ['CH4 → C + 2H2↑'],
    mtype: 'termik-parchalanish',
    steps: ["Yuqori haroratda C–H bog'lari ketma-ket gomolitik uziladi.", "Hosil bo'lgan radikallar vodorod atomlarini yo'qotib, oxirida uglerod (qurum) to'planadi.", "Vodorod atomlari juftlashib H₂ molekulalarini hosil qiladi; jarayon kuchli endotermik."],
    gas: gas('H2', "rangsiz, yonuvchan gaz"),
    heat: 'endotermik', effects: ['deposit', 'smoke'],
    text: "Naycha devorlarida qora qurum qatlami to'planadi; chiqayotgan gaz (vodorod) rangsiz alanga bilan yonadi.",
    kin: "o'rtacha",
    app: ['gaz-naycha-togri', 'mufel-pechi', 'gaz-naycha-egilgan'],
    proc: ["Chinni yoki kvars naychani pechda ~1000 °C gacha qizdiring.", "Asbobdagi havoni siqib chiqargach, naycha orqali metan o'tkazing.", "Naycha ichidagi qurumni va chiqayotgan gazning yonishini kuzating."],
    safety: "Metan va vodorod havo bilan portlovchi aralashma hosil qiladi; bu yuqori haroratli jarayon faqat virtual tajriba yoki maxsus qurilmada o'tkaziladi.",
    expl: "Havosiz kuchli qizdirilganda metan uglerod va vodorodga parchalanadi; shu usulda qurum (bo'yoq va rezina uchun to'ldiruvchi) va vodorod olinadi. Taxminan 1500 °C da qisqa vaqt qizdirilsa, metandan atsetilen hosil bo'ladi: 2CH₄ → C₂H₂ + 3H₂.",
    q: ["Metanni parchalashdan olinadigan qurum qayerda ishlatiladi?", "Metandan atsetilen olish uchun sharoit qanday o'zgartiriladi?"],
  }),
  // ===================== ALKENLAR =====================
  R({
    id: 'uglevod-0018', title: "Etilenning kaliy permanganat eritmasi bilan oksidlanishi (Vagner reaksiyasi)", level: '10-sinf', topic: "Alkenlar: oksidlanish, to'yinmaganlikka sifat reaksiyasi",
    reactants: [{ species: 'CH2=CH2', state: 'g' }, { species: 'KMnO4', state: 'aq', conc_M: 0.02, volume_mL: 3 }],
    cond: { note_uz: "Etilen sovuq suyultirilgan KMnO₄ eritmasi orqali o'tkaziladi (neytral muhit)." },
    eq: ['3CH2=CH2 + 2KMnO4 + 4H2O → 3HOCH2CH2OH + 2MnO2↓ + 2KOH', '3CH2=CH2 + 2K⁺ + 2MnO4⁻ + 4H2O → 3HOCH2CH2OH + 2MnO2↓ + 2K⁺ + 2OH⁻', '3CH2=CH2 + 2MnO4⁻ + 4H2O → 3HOCH2CH2OH + 2MnO2↓ + 2OH⁻', ['2C⁻² − 2e⁻ = 2C⁻¹', 'Mn⁺⁷ + 3e⁻ = Mn⁺⁴']],
    tpl: 'oksidlanish', params: { substrate: 'CH2=CH2', oxidant: 'MnO4⁻ (KMnO4), H2O', product: 'HO–CH2–CH2–OH' },
    steps: ["Permanganat ioni π-bog'ga bir tomondan birikib siklik marganes efirini hosil qiladi (ikkala kislorod bir tomondan — sin-birikish).", "Siklik efir suv bilan gidrolizlanadi: har bir uglerod atomida OH guruhi qoladi — etilenglikol hosil bo'ladi.", "Mn⁺⁷ uchta elektron qabul qilib Mn⁺⁴ ga qaytariladi va qo'ng'ir MnO₂ cho'kmaga tushadi."],
    ppt: ppt('MnO2', 'kolloid'),
    color: [COL.kmno4, '#f4f0ec'],
    heat: 'sezilarsiz', effects: ['bubbles', 'turbidity'],
    text: "Binafsha rangli eritma rangsizlanadi va qo'ng'ir MnO₂ loyqasi hosil bo'ladi.",
    kin: 'tez',
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 3 ml suyultirilgan KMnO₄ eritmasidan quying.", "Gaz naychasini eritmaga tushirib etilen o'tkazing.", "Eritma rangining o'zgarishi va qo'ng'ir loyqani kuzating."],
    safety: SAFE.kmno4 + " Etilen yonuvchan — alangadan uzoqda ishlang.",
    expl: "Sovuq suyultirilgan permanganat eritmasi alkenlarni ikki atomli spirtlar (glikollar) gacha oksidlaydi — bu Vagner reaksiyasi. Binafsha rangning yo'qolishi va qo'ng'ir cho'kma hosil bo'lishi qo'shbog' borligining ikkinchi sifat belgisi hisoblanadi.",
    q: ["Bu reaksiyada oksidlovchi va qaytaruvchini ko'rsating, elektron balansini tuzing.", "Kislotali muhitda va qizdirilganda etilen KMnO₄ bilan qanday mahsulotlar beradi?"],
  }),
  R({
    id: 'uglevod-0019', title: "Etilenning nikel katalizatorida gidrogenlanishi", level: '10-sinf', topic: "Alkenlar: vodorod biriktirish (gidrogenlash)",
    reactants: [{ species: 'CH2=CH2', state: 'g' }, { species: 'H2', state: 'g' }],
    cond: { temp_min_C: 150, catalyst: 'Ni', note_uz: "Etilen va vodorod aralashmasi qizdirilgan nikel katalizatori ustidan o'tkaziladi." },
    eq: ['CH2=CH2 + H2 → CH3–CH3'],
    tpl: 'qaytarilish', params: { substrate: 'CH2=CH2', reductant: 'H2 (Ni)', product: 'CH3–CH3' },
    steps: ["Vodorod molekulalari nikel yuzasida adsorbsiyalanib atomlarga ajraladi.", "Etilen ham π-elektronlari hisobiga katalizator yuzasiga bog'lanadi.", "Vodorod atomlari ketma-ket qo'shbog' uglerodlariga birikadi, hosil bo'lgan etan yuzadan ajraladi."],
    heat: 'ekzotermik', effects: ['heat-haze'],
    text: "Tashqi ko'rinishda o'zgarish kam: gaz hajmi kamayadi (2 hajm → 1 hajm). Hosil bo'lgan gaz bromli suvni rangsizlantirmaydi.",
    kin: 'tez',
    app: ['u-simon-naycha', 'gaz-naycha-togri', 'spirt-lampasi', 'shtativ', 'probirka'],
    proc: ["Naychaga nikel katalizatorini joylashtirib qizdiring.", "Etilen va vodorod aralashmasini (1:1) katalizator ustidan o'tkazing.", "Chiqqan gazni bromli suv orqali o'tkazib, qo'shbog' yo'qolganini tekshiring."],
    safety: "Vodorod va etilen havo bilan portlovchi aralashma hosil qiladi: qizdirishdan oldin asbobdagi havoni to'liq siqib chiqaring; faqat o'qituvchi namoyishi.",
    expl: "Alkenlar metall katalizatorlar (Ni, Pt, Pd) ishtirokida vodorod biriktirib alkanlarga aylanadi. Bunda π-bog' uziladi va to'yinmagan birikma to'yingan birikmaga o'tadi; reaksiya hajm kamayishi bilan boradi.",
    q: ["Propen gidrogenlanganda qaysi modda hosil bo'ladi?", "Bosim oshirilsa bu reaksiya muvozanati qaysi tomonga siljiydi?"],
  }),
  R({
    id: 'uglevod-0020', title: "Etilenga xlorning birikishi (\"golland moyi\")", level: '10-sinf', topic: "Alkenlar: galogenlarning birikishi",
    reactants: [{ species: 'CH2=CH2', state: 'g' }, { species: 'Cl2', state: 'g' }],
    cond: { note_uz: "Etilen va xlor teng hajmlarda silindrda aralashtiriladi." },
    eq: ['CH2=CH2 + Cl2 → CH2Cl–CH2Cl'],
    tpl: 'AdE', params: { alkene: 'CH2=CH2', reagent: 'Cl–Cl', electrophile: 'Cl⁺', nucleophile: 'Cl⁻', intermediate: 'xloroniy ioni', product: 'CH2Cl–CH2Cl' },
    steps: ["Cl₂ molekulasi π-bog' elektronlari ta'sirida qutblanadi.", "Musbat qutblangan xlor atomi π-bog'ga birikib siklik xloroniy ionini hosil qiladi, Cl⁻ ajraladi.", "Cl⁻ ioni xloroniy ioniga qarama-qarshi tomondan hujum qilib 1,2-dixloretan hosil bo'ladi."],
    heat: 'ekzotermik', effects: ['condensate'],
    text: "Xlorning sarg'ish-yashil rangi yo'qoladi, silindr devorlarida moysimon rangsiz tomchilar (1,2-dixloretan) paydo bo'ladi.",
    kin: 'tez',
    app: ['gaz-silindri', 'soat-oynasi'],
    proc: ["Silindrni yarmigacha xlor bilan to'ldiring.", "Ustidan etilen yuborib silindrni yopib qo'ying.", "Gaz rangi va devordagi moysimon tomchilarni kuzating."],
    safety: "Xlor zaharli: faqat mo'rili shkafda, o'qituvchi namoyishi. Etilen yonuvchan.",
    expl: "Alkenlarga galogenlar oson birikadi; etilen va xlordan 1,2-dixloretan hosil bo'ladi, uni tarixan \"golland moyi\" deb atashgan — \"olefin\" (moy hosil qiluvchi) nomi shundan kelib chiqqan. Reaksiya elektrofil birikish mexanizmi bo'yicha, yorug'liksiz ham boradi.",
    q: ["\"Olefin\" so'zi qanday kelib chiqqan?", "Etilenning xlor bilan va etanning xlor bilan reaksiyalari mexanizmini solishtiring."],
  }),
  R({
    id: 'uglevod-0021', title: "Etilenning gidratlanishi — etanol olishning sanoat usuli", level: '10-sinf', topic: "Alkenlar: suv biriktirish (gidratlanish)",
    reactants: [{ species: 'CH2=CH2', state: 'g' }, { species: 'H2O', state: 'g' }],
    cond: { temp_min_C: 280, catalyst: 'H3PO4', note_uz: "Sanoatda etilen va suv bug'i aralashmasi ~280–300 °C da, bosim ostida, tashuvchiga shimdirilgan fosfat kislota ustidan o'tkaziladi." },
    eq: ['CH2=CH2 + H2O → CH3–CH2–OH'],
    tpl: 'AdE', params: { alkene: 'CH2=CH2', reagent: 'H–OH (H⁺)', electrophile: 'H⁺', nucleophile: 'H2O', intermediate: 'CH3–CH2⁺ (karbokation)', product: 'CH3–CH2–OH' },
    steps: ["Kislota katalizatorining protoni H⁺ π-bog' elektron jufti hisobiga uglerod atomiga birikadi — etil karbokationi hosil bo'ladi.", "Suv molekulasi kislorodning taqsimlanmagan elektron jufti bilan karbokationga hujum qiladi (oksoniy ioni).", "Oksoniy ioni protonni qaytarib beradi — etanol hosil bo'ladi va katalizator qayta tiklanadi."],
    heat: 'ekzotermik', effects: ['condensate'],
    text: "Reaktordan chiqqan bug'lar sovutilganda etanolning suvli eritmasi kondensatlanadi.",
    kin: "o'rtacha",
    app: ['gaz-naycha-togri', 'libix-sovutgichi', 'kolba-isitgich', 'termometr'],
    proc: ["Katalizator (fosfat kislota shimdirilgan tashuvchi) bilan to'ldirilgan naychani qizdiring.", "Etilen va suv bug'i aralashmasini katalizator ustidan o'tkazing.", "Chiqqan bug'larni sovutgichda kondensatlang va hosil bo'lgan suyuqlikni yodoform sinovi bilan tekshiring."],
    safety: "Etilen yonuvchan, fosfat kislota o'yuvchi; yuqori harorat va bosim tufayli bu jarayon faqat sanoat qurilmasida yoki virtual tajribada o'tkaziladi.",
    expl: "Kislota katalizatori ishtirokida alkenlarga suv birikadi va spirtlar hosil bo'ladi. Etilenning gidratlanishi etanol olishning asosiy sanoat usullaridan biri; reaksiya ekzotermik va hajm kamayishi bilan borgani uchun bosim ostida o'tkaziladi.",
    q: ["Propen gidratlanganda qaysi spirt hosil bo'ladi va nima uchun?", "Bu jarayonda fosfat kislota qanday vazifani bajaradi?"],
  }),
  R({
    id: 'uglevod-0022', title: "Propenning bromli suvni rangsizlantirishi", level: '10-sinf', topic: "Alkenlar: galogenlarning birikishi",
    reactants: [{ species: 'CH2=CHCH3', state: 'g' }, { species: 'bromli-suv', state: 'aq', volume_mL: 3 }],
    cond: { note_uz: "Propen bromli suv orqali o'tkaziladi." },
    eq: ['CH2=CHCH3 + Br2 → CH2Br–CHBr–CH3'],
    tpl: 'AdE', params: { alkene: 'CH2=CH–CH3', reagent: 'Br–Br', electrophile: 'Br⁺', nucleophile: 'Br⁻', intermediate: 'bromoniy ioni', product: 'CH2Br–CHBr–CH3' },
    steps: ["Br₂ molekulasi π-bog'ga yaqinlashganda qutblanadi.", "Br⁺ qo'shbog' uglerodlariga birikib siklik bromoniy ionini hosil qiladi, Br⁻ ajraladi.", "Br⁻ ioni bromoniy ioniga qarama-qarshi tomondan hujum qiladi va 1,2-dibrompropan hosil bo'ladi."],
    color: [COL.bromliSuv, COL.rangsiz],
    heat: 'sezilarsiz', effects: ['bubbles'],
    text: "Sariq-qo'ng'ir bromli suv tezda rangsizlanadi; probirka tubida og'ir moysimon tomchilar to'planishi mumkin.",
    kin: 'tez',
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 3 ml bromli suv quying.", "Gaz naychasi orqali propen o'tkazing.", "Eritma rangini kuzating."],
    safety: SAFE.brom,
    expl: "Propen ham etilen kabi to'yinmagan uglevodorod: brom qo'shbog' bo'yicha birikib rangsiz 1,2-dibrompropan hosil qiladi. Bromli suvning rangsizlanishi barcha alkenlar uchun umumiy sifat reaksiyasi.",
    q: ["Hosil bo'lgan mahsulotni nomlang.", "Buten-1 va buten-2 bromli suv bilan qanday mahsulotlar hosil qiladi?"],
  }),
  R({
    id: 'uglevod-0023', title: "Propenga vodorod bromidning birikishi (Markovnikov qoidasi)", level: '10-sinf', topic: "Alkenlar: vodorod galogenidlarning birikishi, Markovnikov qoidasi",
    reactants: [{ species: 'CH2=CHCH3', state: 'g' }, { species: 'HBr', state: 'aq', conc_M: 8.8, volume_mL: 3 }],
    cond: { note_uz: "Propen konsentrlangan (~48%) bromid kislota orqali o'tkaziladi; peroksidlar bo'lmasligi kerak." },
    eq: ['CH2=CHCH3 + HBr → CH3–CHBr–CH3', 'CH2=CHCH3 + H⁺ + Br⁻ → CH3–CHBr–CH3', 'CH2=CHCH3 + H⁺ + Br⁻ → CH3–CHBr–CH3'],
    tpl: 'AdE', params: { alkene: 'CH2=CH–CH3', reagent: 'H–Br', electrophile: 'H⁺', nucleophile: 'Br⁻', intermediate: 'CH3–CH⁺–CH3 (ikkilamchi karbokation)', product: 'CH3–CHBr–CH3' },
    steps: ["H⁺ protoni π-bog' elektron jufti hisobiga vodorodi ko'p bo'lgan chetki uglerod (CH₂=) ga birikadi.", "Natijada barqarorroq ikkilamchi karbokation CH₃–CH⁺–CH₃ hosil bo'ladi (metil guruhlar musbat zaryadni barqarorlashtiradi).", "Br⁻ ioni o'zining elektron jufti bilan karbokationga birikadi — 2-brompropan hosil bo'ladi."],
    heat: 'ekzotermik', effects: ['bubbles', 'layers'],
    text: "Propen kislota bilan yutiladi; eritma ustida (yoki tubida) suvda erimaydigan og'ir moysimon qatlam — 2-brompropan to'planadi.",
    kin: 'sekin',
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 3 ml konsentrlangan bromid kislota quying.", "Propenni sekin o'tkazing.", "Hosil bo'lgan moysimon qatlamni kuzating; mahsulot tuzilishini Markovnikov qoidasi asosida aniqlang."],
    safety: "Konsentrlangan bromid kislota terini kuydiradi va bo'g'uvchi bug'lar chiqaradi: mo'rili shkafda, ko'zoynak va qo'lqopda ishlang.",
    expl: "Nosimmetrik alkenlarga vodorod galogenidlar birikkanda vodorod atomi qo'shbog'dagi vodorodi ko'p uglerodga, galogen esa vodorodi kam uglerodga birikadi (Markovnikov qoidasi). Buning sababi — oraliq bosqichda barqarorroq ikkilamchi karbokation hosil bo'lishi. Peroksidlar ishtirokida HBr radikal mexanizm bo'yicha Markovnikov qoidasiga teskari birikadi.",
    q: ["Propenga HCl birikkanda qaysi mahsulot hosil bo'ladi?", "Markovnikov qoidasini karbokationlar barqarorligi asosida tushuntiring.", "Peroksid effekti (Xarash effekti) nima?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0024', title: "Propenning kaliy permanganat bilan oksidlanishi (propilenglikol hosil bo'lishi)", level: 'litsey', topic: "Alkenlar: Vagner reaksiyasi",
    reactants: [{ species: 'CH2=CHCH3', state: 'g' }, { species: 'KMnO4', state: 'aq', conc_M: 0.02, volume_mL: 3 }],
    cond: { note_uz: "Propen sovuq suyultirilgan KMnO₄ eritmasi orqali o'tkaziladi." },
    eq: ['3CH2=CHCH3 + 2KMnO4 + 4H2O → 3CH3CH(OH)CH2OH + 2MnO2↓ + 2KOH', '3CH2=CHCH3 + 2K⁺ + 2MnO4⁻ + 4H2O → 3CH3CH(OH)CH2OH + 2MnO2↓ + 2K⁺ + 2OH⁻', '3CH2=CHCH3 + 2MnO4⁻ + 4H2O → 3CH3CH(OH)CH2OH + 2MnO2↓ + 2OH⁻', ['C⁻² − 1e⁻ = C⁻¹', 'C⁻¹ − 1e⁻ = C⁰', 'Mn⁺⁷ + 3e⁻ = Mn⁺⁴']],
    tpl: 'oksidlanish', params: { substrate: 'CH2=CH–CH3', oxidant: 'MnO4⁻ (KMnO4), H2O', product: 'CH3–CH(OH)–CH2OH' },
    steps: ["MnO₄⁻ ioni qo'shbog'ga bir tomondan birikib siklik marganes efirini hosil qiladi.", "Efir gidrolizlanib, ikkala uglerod atomida OH guruhi qoladi — propandiol-1,2.", "Har bir propen molekulasi 2 elektron beradi, Mn⁺⁷ esa 3 elektron olib MnO₂ ga aylanadi."],
    ppt: ppt('MnO2', 'kolloid'),
    color: [COL.kmno4, '#f4f0ec'],
    heat: 'sezilarsiz', effects: ['bubbles', 'turbidity'],
    text: "Binafsha eritma rangsizlanadi, qo'ng'ir MnO₂ loyqasi hosil bo'ladi.",
    kin: 'tez',
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 3 ml suyultirilgan KMnO₄ eritmasidan quying.", "Propen o'tkazing.", "Rang o'zgarishini va qo'ng'ir cho'kmani kuzating."],
    safety: SAFE.kmno4,
    expl: "Barcha alkenlar sovuq neytral permanganat bilan glikollarga oksidlanadi. Propendan propandiol-1,2 (propilenglikol) hosil bo'ladi; reaksiya alkenlarni aniqlash uchun ishlatiladi.",
    q: ["Propenning permanganat bilan reaksiyasi uchun elektron balans tuzing.", "Buten-2 dan qanday glikol hosil bo'ladi?"],
  }),
  R({
    id: 'uglevod-0025', title: "Brometandan kaliy gidroksidning spirtli eritmasi ta'sirida etilen olish", level: 'litsey', topic: "Alkenlarni olish: degidrogalogenlash (E2)",
    reactants: [{ species: 'C2H5Br', state: 'l', volume_mL: 1 }, { species: 'KOH', state: 's', mass_g: 1 }],
    cond: { temp_min_C: 70, note_uz: "KOH ning etanoldagi (spirtli) eritmasi brometan bilan qizdiriladi; suv bo'lmasligi kerak (suvli ishqorda spirt hosil bo'ladi)." },
    eq: ['C2H5Br + KOH → CH2=CH2↑ + KBr↓ + H2O'],
    tpl: 'E2', params: { substrate: 'CH3–CH2Br', base: 'OH⁻ (KOH, spirtda)', leaving_group: 'Br⁻', product: 'CH2=CH2', byproduct: 'H2O' },
    steps: ["Kuchli asos OH⁻ β-uglerod atomidagi protonni tortib oladi.", "Bir vaqtning o'zida C–H bog'ining elektron jufti C=C π-bog'ini hosil qilishga o'tadi.", "C–Br bog'ining elektron jufti brom atomiga o'tadi va Br⁻ ajraladi — bitta bosqichli kelishilgan eliminirlanish (E2)."],
    ppt: ppt('KBr'),
    gas: gas('CH2=CH2'),
    heat: 'sezilarsiz', effects: ['bubbles', 'turbidity'],
    text: "Qizdirilganda gaz ajraladi, u bromli suvni rangsizlantiradi; spirtli eritmada oq KBr kristallari cho'kadi.",
    kin: "o'rtacha",
    app: ['probirka', 'rezina-tiqin-1-teshikli-kichik', 'gaz-naycha-egilgan', 'suv-hammomi', 'shtativ'],
    proc: ["Probirkaga KOH ning etanoldagi eritmasidan 3 ml quying va 1 ml brometan qo'shing.", "Probirkani gaz chiqarish naychali tiqin bilan berkitib, suv hammomida qizdiring.", "Ajralgan gazni bromli suv orqali o'tkazing."],
    safety: "KOH o'yuvchi, brometan va etanol yonuvchan: ochiq alangada emas, suv hammomida qizdiring; ko'zoynak taqing.",
    expl: "Galogenalkanlarga ishqorning spirtli eritmasi ta'sir etganda vodorod galogenid ajralib chiqadi va alken hosil bo'ladi (degidrogalogenlash). Suvli eritmada esa OH⁻ nukleofil sifatida galogen o'rnini oladi va spirt hosil bo'ladi; erituvchi reaksiya yo'nalishini belgilaydi.",
    q: ["2-brombutandan qaysi alken asosiy mahsulot bo'ladi (Zaysev qoidasi)?", "Brometanga KOH ning suvli va spirtli eritmalari ta'sirini solishtiring."],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-x02', title: "Izobutilenga vodorod xloridning birikishi (uchlamchi karbokation)", level: 'litsey', topic: "Alkenlar: Markovnikov qoidasi va karbokationlar barqarorligi",
    reactants: [{ species: '(CH3)2C=CH2', state: 'g' }, { species: 'HCl', state: 'aq', conc_M: 11.6, volume_mL: 3 }],
    cond: { note_uz: "Izobutilen konsentrlangan xlorid kislota orqali o'tkaziladi." },
    eq: ['(CH3)2C=CH2 + HCl → (CH3)3CCl', '(CH3)2C=CH2 + H⁺ + Cl⁻ → (CH3)3CCl', '(CH3)2C=CH2 + H⁺ + Cl⁻ → (CH3)3CCl'],
    tpl: 'AdE', params: { alkene: '(CH3)2C=CH2', reagent: 'H–Cl', electrophile: 'H⁺', nucleophile: 'Cl⁻', intermediate: '(CH3)3C⁺ (uchlamchi karbokation)', product: '(CH3)3C–Cl' },
    steps: ["H⁺ π-bog' elektron jufti hisobiga chetki CH₂= uglerodiga birikadi.", "Musbat zaryad uchta metil guruh bilan o'ralgan uglerodda qoladi — juda barqaror uchlamchi karbokation (CH₃)₃C⁺ hosil bo'ladi.", "Cl⁻ ioni karbokationga birikib 2-xlor-2-metilpropan hosil bo'ladi."],
    heat: 'ekzotermik', effects: ['bubbles', 'layers', 'turbidity'],
    text: "Gaz kislota bilan yutiladi, eritma loyqalanib, ustida suvda erimaydigan rangsiz moysimon qatlam (tret-butilxlorid) hosil bo'ladi.",
    kin: 'tez',
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 3 ml konsentrlangan xlorid kislota quying.", "Izobutilenni sekin o'tkazing.", "Hosil bo'lgan organik qatlamni kuzating va mahsulot tuzilishini Markovnikov qoidasi asosida aniqlang."],
    safety: "Konsentrlangan xlorid kislota bug'lari bo'g'uvchi va o'yuvchi; mo'rili shkafda ishlang. Izobutilen yonuvchan.",
    expl: "Izobutilenga HCl birikkanda uchlamchi karbokation hosil bo'ladi, u juda barqaror bo'lgani uchun reaksiya yengil boradi va vodorod Markovnikov qoidasiga muvofiq CH₂ guruhga birikadi. Karbokation qanchalik barqaror bo'lsa, elektrofil birikish shuncha oson ketadi.",
    q: ["Etilen, propen va izobutilenni HCl bilan reaksiya tezligi bo'yicha tartiblang.", "Hosil bo'lgan mahsulotni xalqaro nomenklatura bo'yicha nomlang."],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0026', title: "Siklogeksenning bromli suvni rangsizlantirishi", level: 'litsey', topic: "Sikloalkenlar: elektrofil birikish",
    reactants: [{ species: 'C6H10', state: 'l', volume_mL: 0.5 }, { species: 'bromli-suv', state: 'aq', volume_mL: 3 }],
    eq: ['C6H10 + Br2 → C6H10Br2'],
    tpl: 'AdE', params: { alkene: 'siklogeksen C6H10', reagent: 'Br–Br', electrophile: 'Br⁺', nucleophile: 'Br⁻', intermediate: 'siklik bromoniy ioni', product: 'trans-1,2-dibromsiklogeksan' },
    steps: ["Br₂ π-bog' ta'sirida qutblanadi va Br⁺ halqadagi qo'shbog'ga birikib bromoniy ionini hosil qiladi.", "Br⁻ ioni bromoniy ioniga qarama-qarshi tomondan hujum qiladi.", "Natijada brom atomlari halqaning ikki tomonida joylashgan trans-1,2-dibromsiklogeksan hosil bo'ladi (anti-birikish)."],
    color: [COL.bromliSuv, COL.rangsiz],
    heat: 'sezilarsiz', effects: ['layers'],
    text: "Chayqatilganda bromli suv tezda rangsizlanadi; organik qatlam ham rangsiz bo'lib qoladi.",
    kin: 'tez',
    app: ['probirka', 'tomizgich'],
    proc: ["Probirkaga 3 ml bromli suv quying.", "Tomizgich bilan 0,5 ml siklogeksen qo'shib chayqating.", "Ikkala qatlam rangini siklogeksan bilan o'tkazilgan tajriba bilan solishtiring."],
    safety: SAFE.brom + ' Siklogeksen yonuvchan.',
    expl: "Siklogeksen halqasida bitta qo'shbog' bor, shuning uchun u alkenlar kabi bromni biriktiradi. Geksan yoki siklogeksandan farqli o'laroq, bu yerda brom organik qatlamga o'tmaydi, balki kimyoviy bog'lanadi — ikkala qatlam ham rangsiz bo'ladi.",
    q: ["Nima uchun mahsulot trans-izomer ko'rinishida hosil bo'ladi?", "Siklogeksen va siklogeksanni qanday farqlash mumkin?"],
  }),
  R({
    id: 'uglevod-0027', title: "Siklogeksanning bromli suv bilan reaksiyaga kirishmasligi", level: 'litsey', topic: "Sikloalkanlar: to'yinganlik",
    no_reaction: true, match: ['C6H12', 'Br2'],
    reactants: [{ species: 'C6H12', state: 'l', volume_mL: 0.5 }, { species: 'bromli-suv', state: 'aq', volume_mL: 3 }],
    steps: ["Siklogeksan halqasi kuchlanishsiz va faqat σ-bog'lardan iborat — elektrofil birikish uchun π-bog' yo'q.", "Brom faqat organik qatlamga fizik o'tadi (ekstraksiya)."],
    effects: ['layers'],
    text: "Chayqatilgach suv qatlami rangsizlanadi, lekin yuqoridagi siklogeksan qatlami sariq-to'q sariq rangga kiradi — brom saqlanib qoladi.",
    kin: 'bir-zumda',
    app: ['probirka', 'tomizgich'],
    proc: ["Probirkaga 3 ml bromli suv quying.", "0,5 ml siklogeksan qo'shib chayqating.", "Qatlamlar rangini kuzating."],
    safety: SAFE.brom + ' Siklogeksan yonuvchan.',
    expl: "Siklogeksan C₆H₁₂ siklogeksenga izomer emas, balki uning gidrogenlangan hosilasi: unda qo'shbog' yo'q, shuning uchun brom birikmaydi. Kichik halqali sikloalkanlardan farqli ravishda (siklopropan) olti a'zoli halqa kuchlanishsiz va bromni biriktirmaydi.",
    q: ["Siklogeksan qaysi uglevodorodlar sinfiga izomer?", "Siklopropan bromli suvni rangsizlantiradimi?"],
  }),

  // ===================== ALKINLAR =====================
  R({
    id: 'uglevod-0029', title: "Atsetilenning bromli suvni rangsizlantirishi", level: '10-sinf', topic: "Alkinlar: galogenlarning bosqichli birikishi",
    reactants: [{ species: 'CH≡CH', state: 'g' }, { species: 'bromli-suv', state: 'aq', volume_mL: 3 }],
    cond: { note_uz: "Atsetilen bromli suv orqali o'tkaziladi." },
    eq: ['CH≡CH + 2Br2 → CHBr2–CHBr2'],
    tpl: 'AdE', params: { alkene: 'CH≡CH', reagent: 'Br–Br', electrophile: 'Br⁺', nucleophile: 'Br⁻', intermediate: 'CHBr=CHBr (1,2-dibrometen)', product: 'CHBr2–CHBr2' },
    steps: ["Birinchi Br₂ molekulasi uchbog'dagi bitta π-bog'ga elektrofil birikadi: oraliq bromli kation orqali 1,2-dibrometen CHBr=CHBr hosil bo'ladi.", "Hosil bo'lgan qo'shbog' elektronoakseptor brom atomlari tufayli sustroq, lekin ikkinchi Br₂ ni ham biriktiradi.", "Natijada 1,1,2,2-tetrabrometan hosil bo'ladi."],
    color: [COL.bromliSuv, COL.rangsiz],
    heat: 'sezilarsiz', effects: ['bubbles'],
    text: "Bromli suv rangsizlanadi; etilenga qaraganda sekinroq.",
    kin: "o'rtacha",
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 3 ml bromli suv quying.", "Atsetilenni gaz naychasi orqali o'tkazing.", "Rangsizlanish tezligini etilen bilan solishtiring."],
    safety: SAFE.brom + ' Atsetilen yonuvchan.',
    expl: "Alkinlar molekulasida ikkita π-bog' bo'lgani uchun brom bosqichma-bosqich, ikki molekula miqdorida birikadi. Bromli suvning rangsizlanishi alkinlar uchun ham to'yinmaganlik belgisi.",
    q: ["Atsetilenga brom bosqichli birikishining oraliq mahsulotini nomlang.", "1 mol atsetilen necha mol bromni biriktiradi?"],
  }),
  R({
    id: 'uglevod-0030', title: "Atsetilenning kaliy permanganat eritmasini rangsizlantirishi", level: '10-sinf', topic: "Alkinlar: oksidlanish",
    reactants: [{ species: 'CH≡CH', state: 'g' }, { species: 'KMnO4', state: 'aq', conc_M: 0.02, volume_mL: 3 }],
    cond: { note_uz: "Atsetilen neytral suyultirilgan KMnO₄ eritmasi orqali o'tkaziladi." },
    eq: ['3CH≡CH + 8KMnO4 → 3K2C2O4 + 8MnO2↓ + 2KOH + 2H2O', '3CH≡CH + 8K⁺ + 8MnO4⁻ → 6K⁺ + 3C2O4²⁻ + 8MnO2↓ + 2K⁺ + 2OH⁻ + 2H2O', '3CH≡CH + 8MnO4⁻ → 3C2O4²⁻ + 8MnO2↓ + 2OH⁻ + 2H2O', ['2C⁻¹ − 8e⁻ = 2C⁺³', 'Mn⁺⁷ + 3e⁻ = Mn⁺⁴']],
    tpl: 'oksidlanish', params: { substrate: 'CH≡CH', oxidant: 'MnO4⁻ (KMnO4)', product: '⁻OOC–COO⁻ (oksalat)' },
    steps: ["Permanganat uchbog'ga birikib, uglerod atomlarini ketma-ket oksidlaydi.", "Har bir uglerod atomi C⁻¹ dan C⁺³ gacha oksidlanadi — oksalat ioni ⁻OOC–COO⁻ hosil bo'ladi.", "Mn⁺⁷ uch elektron olib qo'ng'ir MnO₂ ga qaytariladi."],
    ppt: ppt('MnO2', 'kolloid'),
    color: [COL.kmno4, '#f4f0ec'],
    heat: 'sezilarsiz', effects: ['bubbles', 'turbidity'],
    text: "Binafsha rangli eritma rangsizlanadi va qo'ng'ir loyqa hosil bo'ladi.",
    kin: 'tez',
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 3 ml suyultirilgan KMnO₄ eritmasidan quying.", "Atsetilenni o'tkazing.", "Eritma rangi va loyqani kuzating."],
    safety: SAFE.kmno4,
    expl: "Alkinlar ham alkenlar kabi permanganat eritmasini rangsizlantiradi. Neytral muhitda atsetilen kaliy oksalatgacha oksidlanadi, kislotali muhitda esa CO₂ gacha oksidlanishi mumkin.",
    q: ["Bu reaksiya uchun elektron balans tuzing.", "Kislotali muhitda atsetilen permanganat bilan qanday mahsulot beradi?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0031', title: "Atsetilenning kumush oksidning ammiakli eritmasi bilan reaksiyasi (kumush atsetilenid)", level: '11-sinf', topic: "Alkinlar: uchbog'dagi vodorodning kislotali xossasi",
    reactants: [{ species: 'CH≡CH', state: 'g' }, { species: 'Tollens', state: 'aq', volume_mL: 5 }],
    cond: { note_uz: "Atsetilen yangi tayyorlangan kumush oksidning ammiakli eritmasi orqali o'tkaziladi." },
    eq: ['CH≡CH + 2[Ag(NH3)2]OH → AgC≡CAg↓ + 4NH3 + 2H2O', 'CH≡CH + 2[Ag(NH3)2]⁺ + 2OH⁻ → AgC≡CAg↓ + 4NH3 + 2H2O', 'CH≡CH + 2[Ag(NH3)2]⁺ + 2OH⁻ → AgC≡CAg↓ + 4NH3 + 2H2O'],
    tpl: 'SN2', params: { substrate: '[Ag(NH3)2]⁺', nucleophile: 'HC≡C⁻ (atsetilenid)', leaving_group: 'NH3', product: 'AgC≡CAg' },
    steps: ["sp-gibridlangan uglerod atomi elektromanfiyroq, shuning uchun ≡C–H bog'i qutblangan va vodorod proton sifatida ajralishi mumkin (kuchsiz kislota).", "Ishqoriy muhitda OH⁻ ioni protonni tortib oladi, atsetilenid anioni HC≡C⁻ hosil bo'ladi.", "Atsetilenid anioni diamminkumush ionidagi ammiak ligandlarini siqib chiqarib, kumush bilan bog'lanadi; ikkinchi proton ham shu tarzda almashinadi va erimaydigan AgC≡CAg cho'kadi."],
    ppt: ppt('AgC≡CAg'),
    heat: 'sezilarsiz', effects: ['bubbles', 'turbidity'],
    text: "Rangsiz eritmada sarg'ish-oq (kulrang tusli) cho'kma — kumush atsetilenid hosil bo'ladi.",
    kin: 'tez',
    app: ['probirka', 'gaz-naycha-egilgan'],
    proc: ["Probirkaga 2–3 ml yangi tayyorlangan kumush oksidning ammiakli eritmasidan quying.", "Atsetilenni o'tkazing va cho'kmani kuzating.", "Tajribadan so'ng cho'kmani quritmasdan darhol suyultirilgan xlorid kislota bilan parchalang."],
    safety: "Quruq kumush atsetilenid zarba va qizdirishdan portlaydi! Cho'kmani hech qachon quritmang va filtrlab saqlamang — tajribadan keyin darhol suyultirilgan HCl yoki HNO₃ bilan parchalab yo'q qiling. Faqat o'qituvchi namoyishi, oz miqdorda.",
    expl: "Uchbog' chetida joylashgan vodorod atomlari kuchsiz kislotali xossaga ega va metall atomlariga almashinishi mumkin. Kumush va mis(I) atsetilenidlarining hosil bo'lishi terminal alkinlarni (≡C–H guruhi bor) aniqlashning sifat reaksiyasi; buten-2-in kabi ichki alkinlar bu reaksiyani bermaydi.",
    q: ["Nima uchun etilen bu reaksiyani bermaydi?", "Propin va butin-2 ni qanday farqlash mumkin?", "Kumush atsetilenid bilan ishlashda qanday ehtiyot choralari ko'riladi?"],
  }),
  R({
    id: 'uglevod-x03', title: "Kumush atsetilenidning xlorid kislota bilan parchalanishi", level: '11-sinf', topic: "Alkinlar: atsetilenidlarning xossalari",
    reactants: [{ species: 'AgC≡CAg', state: 's', mass_g: 0.05 }, { species: 'HCl', state: 'aq', conc_M: 2, volume_mL: 3 }],
    cond: { note_uz: "Nam kumush atsetilenid cho'kmasi ustiga darhol suyultirilgan xlorid kislota quyiladi." },
    eq: ['AgC≡CAg + 2HCl → CH≡CH↑ + 2AgCl↓', 'AgC≡CAg + 2H⁺ + 2Cl⁻ → CH≡CH↑ + 2AgCl↓', 'AgC≡CAg + 2H⁺ + 2Cl⁻ → CH≡CH↑ + 2AgCl↓'],
    mtype: 'ion-almashinish',
    steps: ["Atsetilen juda kuchsiz kislota, shuning uchun uning tuzi (atsetilenid) kuchli kislota ta'sirida parchalanadi.", "Kislota protonlari atsetilenid ioniga o'tadi va atsetilen gaz holida ajraladi.", "Ag⁺ ionlari Cl⁻ bilan oq suzmasimon AgCl cho'kmasini hosil qiladi."],
    ppt: ppt('AgCl'),
    gas: gas('CH≡CH'),
    heat: 'sezilarsiz', effects: ['bubbles'],
    text: "Sarg'ish cho'kma oq suzmasimon AgCl ga aylanadi va mayda gaz pufakchalari (atsetilen) ajraladi.",
    kin: 'tez',
    app: ['probirka', 'tomizgich'],
    proc: ["Atsetilenid hosil qilingan probirkadagi cho'kmani quritmasdan qoldiring.", "Ustiga tomizgich bilan 3 ml suyultirilgan xlorid kislota qo'shing.", "Gaz ajralishi va cho'kma rangining o'zgarishini kuzating."],
    safety: "Kumush atsetilenid quruq holda portlaydi: u faqat nam holda, oz miqdorda kislota bilan parchalanadi. Kumush tuzlari chiqindisi alohida idishga yig'iladi.",
    expl: "Kuchli kislotalar kuchsiz kislota — atsetilenni uning tuzlaridan siqib chiqaradi. Bu reaksiya kumush atsetilenidni xavfsiz yo'q qilish usuli bo'lib, terminal alkinlarni ajratib olish va tozalashda ham qo'llaniladi.",
    q: ["Nima uchun atsetilenni kuchsiz kislota deyish mumkin?", "Kumush atsetilenidni nima uchun quritib bo'lmaydi?"],
  }),
  R({
    id: 'uglevod-0033', title: "Kucherov reaksiyasi: atsetilenning gidratlanishi", level: '10-sinf', topic: "Alkinlar: suv biriktirish (Kucherov reaksiyasi)",
    reactants: [{ species: 'CH≡CH', state: 'g' }, { species: 'H2O', state: 'l', volume_mL: 5 }],
    cond: { temp_min_C: 70, catalyst: ['HgSO4', 'H2SO4'], note_uz: "Atsetilen simob(II) sulfat qo'shilgan iliq suyultirilgan sulfat kislota orqali o'tkaziladi." },
    eq: ['CH≡CH + H2O → CH3CHO'],
    tpl: 'AdE', params: { alkene: 'CH≡CH', reagent: 'H–OH (Hg²⁺, H⁺)', electrophile: 'Hg²⁺ / H⁺', nucleophile: 'H2O', intermediate: 'CH2=CH–OH (vinil spirt, enol)', product: 'CH3–CHO' },
    steps: ["Hg²⁺ ioni uchbog' π-elektronlari bilan kompleks hosil qilib, uni elektrofil hujumga faollashtiradi.", "Suv molekulasi uglerodga birikadi, proton ajraladi; Hg protonga almashib, beqaror vinil spirt (enol) CH₂=CH–OH hosil bo'ladi.", "Enol tez izomerlanadi: O–H dagi proton qo'shbog' uglerodiga ko'chadi va C=O guruhi hosil bo'ladi — atsetaldegid (keto-enol tautomeriya)."],
    heat: 'ekzotermik', effects: ['bubbles'],
    text: "Atsetilen kislota eritmasi bilan yutiladi; eritmadan o'tkir hidli (chirigan olma hidi) atsetaldegid bug'lari chiqadi, ular kumush ko'zgu reaksiyasini beradi.",
    kin: "o'rtacha",
    app: ['probirka-yon-naychali', 'gaz-naycha-egilgan', 'suv-hammomi', 'termometr'],
    proc: ["Probirkaga 5 ml suyultirilgan sulfat kislota quying va ozgina simob(II) sulfat qo'shing.", "Probirkani suv hammomida ~70–80 °C gacha isiting.", "Atsetilenni eritma orqali o'tkazing.", "Chiqayotgan bug'larni kumush oksidning ammiakli eritmasi bilan tekshiring."],
    safety: "Simob tuzlari o'ta zaharli: tajriba faqat o'qituvchi tomonidan mo'rili shkafda namoyish qilinadi, chiqindilar alohida yig'iladi. Sulfat kislota o'yuvchi.",
    expl: "Simob(II) tuzlari ishtirokida alkinlarga suv birikadi; atsetilendan oraliq vinil spirt orqali atsetaldegid, boshqa alkinlardan esa ketonlar hosil bo'ladi (M.G. Kucherov, 1881). Enollar beqaror bo'lib, darhol karbonil birikmaga izomerlanadi.",
    q: ["Propinning gidratlanishidan qaysi modda hosil bo'ladi?", "Nima uchun vinil spirtni ajratib olib bo'lmaydi?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0034', title: "Atsetilenga vodorod xloridning birikishi — vinilxlorid olish", level: '10-sinf', topic: "Alkinlar: vodorod galogenidlarning birikishi",
    reactants: [{ species: 'CH≡CH', state: 'g' }, { species: 'HCl', state: 'g' }],
    cond: { temp_min_C: 150, catalyst: 'HgCl2', note_uz: "Quruq atsetilen va vodorod xlorid aralashmasi faollangan ko'mirga shimdirilgan HgCl₂ katalizatori ustidan ~150–180 °C da o'tkaziladi." },
    eq: ['CH≡CH + HCl → CH2=CHCl'],
    tpl: 'AdE', params: { alkene: 'CH≡CH', reagent: 'H–Cl', electrophile: 'H⁺', nucleophile: 'Cl⁻', intermediate: 'CH2=CH⁺ (vinil kation, Hg²⁺ ishtirokida)', product: 'CH2=CHCl' },
    steps: ["Katalizator (Hg²⁺) uchbog'ni faollashtiradi; H⁺ π-bog' elektron jufti hisobiga bir uglerodga birikadi.", "Ikkinchi uglerod atomiga Cl⁻ birikadi — vinilxlorid hosil bo'ladi.", "Hosil bo'lgan qo'shbog'ga HCl ning keyingi birikishi sekin; sharoit tanlash orqali vinilxlorid ajratib olinadi."],
    heat: 'ekzotermik', effects: [],
    text: "Tashqi o'zgarish kam; chiqayotgan gaz bromli suvni rangsizlantiradi (qo'shbog' saqlanadi).",
    kin: "o'rtacha",
    app: ['gaz-naycha-togri', 'kolba-isitgich', 'termometr'],
    proc: ["Katalizator solingan naychani ~150 °C gacha qizdiring.", "Quruq atsetilen va vodorod xlorid aralashmasini (1:1) o'tkazing.", "Chiqqan gazni bromli suv orqali o'tkazib tekshiring."],
    safety: "Simob(II) xlorid o'ta zaharli, vinilxlorid kanserogen, HCl o'yuvchi: bu sanoat jarayoni bo'lib, faqat virtual tajriba yoki o'qituvchi namoyishi sifatida ko'riladi.",
    expl: "Atsetilenga HCl birikkanda vinilxlorid hosil bo'ladi — undan polivinilxlorid (PVX) olinadi. Uchbog'ga bitta HCl molekulasi birikadi, ikkinchisi esa Markovnikov qoidasi bo'yicha 1,1-dixloretan hosil qiladi.",
    q: ["Vinilxloridga yana bir molekula HCl birikkanda qaysi mahsulot hosil bo'ladi?", "Vinilxloriddan qanday polimer olinadi?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0035', title: "Atsetilenning nikel katalizatorida to'liq gidrogenlanishi", level: '10-sinf', topic: "Alkinlar: vodorod biriktirish",
    reactants: [{ species: 'CH≡CH', state: 'g' }, { species: 'H2', state: 'g' }],
    cond: { temp_min_C: 150, catalyst: 'Ni', note_uz: "Atsetilen va ortiqcha vodorod qizdirilgan nikel ustidan o'tkaziladi." },
    eq: ['CH≡CH + 2H2 → CH3–CH3'],
    tpl: 'qaytarilish', params: { substrate: 'CH≡CH', reductant: '2H2 (Ni)', product: 'CH3–CH3' },
    steps: ["Vodorod nikel yuzasida atomlarga ajraladi, atsetilen ham yuzaga adsorbsiyalanadi.", "Birinchi H₂ molekulasi birikib oraliq mahsulot — etilen hosil bo'ladi.", "Ikkinchi H₂ molekulasi birikib etan hosil bo'ladi (nikelda reaksiyani etilen bosqichida to'xtatish qiyin)."],
    heat: 'ekzotermik', effects: ['heat-haze'],
    text: "Gaz hajmi kamayadi (3 hajm → 1 hajm); hosil bo'lgan gaz bromli suvni rangsizlantirmaydi.",
    kin: 'tez',
    app: ['gaz-naycha-togri', 'spirt-lampasi', 'shtativ', 'probirka'],
    proc: ["Nikel katalizatori solingan naychani qizdiring.", "Atsetilen va vodorod aralashmasini (1:2 dan ortiq vodorod bilan) o'tkazing.", "Chiqqan gazni bromli suv orqali o'tkazing."],
    safety: "Vodorod va atsetilen havo bilan portlovchi aralashma hosil qiladi: asbobdagi havoni oldindan siqib chiqaring; o'qituvchi namoyishi.",
    expl: "Alkinlar ikki bosqichda vodorod biriktiradi: avval alkenga, so'ng alkanga. Nikel yoki platinada reaksiya oxirigacha — alkangacha boradi; alkenda to'xtatish uchun faolligi pasaytirilgan (Lindlar) palladiy katalizatori ishlatiladi.",
    q: ["1 mol atsetilen to'liq gidrogenlanishi uchun necha mol vodorod kerak?", "Atsetilendan etilen olish uchun qanday katalizator kerak?"],
  }),
  R({
    id: 'uglevod-0036', title: "Atsetilenning trimerlanishi — benzol olish (Zelinskiy reaksiyasi)", level: '10-sinf', topic: "Arenlarni olish: atsetilen trimerizatsiyasi",
    reactants: [{ species: 'CH≡CH', state: 'g' }],
    cond: { temp_min_C: 600, catalyst: 'C', note_uz: "Atsetilen ~600 °C gacha qizdirilgan faollangan ko'mir solingan naycha orqali o'tkaziladi." },
    eq: ['3CH≡CH → C6H6'],
    mtype: 'birikish',
    steps: ["Faollangan ko'mir yuzasida atsetilen molekulalari adsorbsiyalanadi va π-bog'lari faollashadi.", "Uchta atsetilen molekulasi siklik birikib, olti a'zoli halqa hosil qiladi (siklotrimerlanish).", "Hosil bo'lgan halqada oltita π-elektron yagona aromatik tizimni hosil qiladi — benzol."],
    heat: 'kuchli-ekzotermik', effects: ['condensate'],
    text: "Naychadan chiqqan bug'lar sovutilganda o'ziga xos hidli rangsiz suyuqlik — benzol tomchilari kondensatlanadi.",
    kin: "o'rtacha",
    app: ['gaz-naycha-togri', 'kolba-isitgich', 'libix-sovutgichi', 'termometr'],
    proc: ["Faollangan ko'mir solingan kvars naychani ~600 °C gacha qizdiring.", "Quruq atsetilenni sekin o'tkazing.", "Chiqqan bug'larni sovutgichda kondensatlab, suyuqlikni yig'ing."],
    safety: SAFE.benzol + " Atsetilen portlovchi aralashmalar hosil qiladi — bu jarayon faqat virtual tajriba sifatida ko'riladi.",
    expl: "N.D. Zelinskiy atsetilenni faollangan ko'mir ustida qizdirib benzol olgan. Bu reaksiya alifatik uglevodorodlardan aromatik birikmalar olish mumkinligini ko'rsatadi va benzolning C₆H₆ formulasi uchta atsetilen molekulasiga mos kelishini tasdiqlaydi.",
    q: ["Propindan shu usulda qanday aromatik uglevodorod hosil bo'ladi?", "78 g benzol olish uchun (n.sh.da) qancha hajm atsetilen kerak?"],
    conf: "o'rta",
  }),

  // ===================== ARENLAR =====================
  R({
    id: 'uglevod-0037', title: "Benzolning bromli suvni rangsizlantirmasligi", level: '10-sinf', topic: "Arenlar: aromatik tizimning barqarorligi",
    no_reaction: true, match: ['C6H6', 'Br2'],
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 0.5 }, { species: 'bromli-suv', state: 'aq', volume_mL: 3 }],
    steps: ["Benzoldagi oltita π-elektron butun halqa bo'ylab teng taqsimlangan yagona aromatik tizim hosil qiladi.", "Brom birikishi aromatiklikni buzgani uchun energetik jihatdan noqulay; katalizatorsiz o'rin olish ham ketmaydi.", "Brom faqat benzol qatlamiga fizik o'tadi."],
    effects: ['layers'],
    text: "Chayqatilgach suv qatlami rangsizlanadi, ammo yuqoridagi benzol qatlami sariq-to'q sariq rangga bo'yaladi — brom reaksiyaga kirishmagan.",
    kin: 'bir-zumda',
    app: ['probirka', 'tomizgich'],
    proc: ["Probirkaga 3 ml bromli suv quying.", "0,5 ml benzol qo'shib chayqating.", "Qatlamlar rangini siklogeksen bilan o'tkazilgan tajriba natijasi bilan solishtiring."],
    safety: SAFE.benzol + ' ' + SAFE.brom,
    expl: "Benzol formulasi bo'yicha to'yinmagan bo'lsa ham, alkenlardan farqli ravishda bromli suvni rangsizlantirmaydi: yagona aromatik π-tizim juda barqaror. Benzol uchun birikish emas, balki katalizator ishtirokidagi elektrofil o'rin olish reaksiyalari xos.",
    q: ["Nima uchun benzol alkenlardan farqli ravishda bromni biriktirmaydi?", "Qanday sharoitda benzol brom bilan reaksiyaga kirishadi?"],
  }),
  R({
    id: 'uglevod-0038', title: "Benzolning kaliy permanganat eritmasini rangsizlantirmasligi", level: '10-sinf', topic: "Arenlar: oksidlovchilarga chidamlilik",
    no_reaction: true, match: ['C6H6', 'MnO4⁻'],
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 0.5 }, { species: 'KMnO4', state: 'aq', conc_M: 0.02, volume_mL: 2 }],
    steps: ["Aromatik halqaning π-elektron tizimi barqaror, permanganat uni odatdagi sharoitda oksidlay olmaydi.", "Benzol suvda erimay alohida qatlam hosil qiladi."],
    effects: ['layers'],
    text: "Ikki qatlam hosil bo'ladi; qizdirilsa ham binafsha rang saqlanib qoladi.",
    kin: 'bir-zumda',
    app: ['probirka', 'tomizgich'],
    proc: ["Probirkaga 2 ml suyultirilgan KMnO₄ eritmasidan quying.", "0,5 ml benzol qo'shib chayqating.", "Rang o'zgarmaganini toluol bilan o'tkazilgan tajriba bilan solishtiring."],
    safety: SAFE.benzol + ' ' + SAFE.kmno4,
    expl: "Benzol halqasi oksidlovchilarga juda chidamli; shuning uchun benzol KMnO₄ eritmasini rangsizlantirmaydi. Benzol gomologlarida (toluol) esa oksidlanishga yon zanjir uchraydi, halqa saqlanib qoladi.",
    q: ["Benzol va toluolni KMnO₄ yordamida qanday farqlash mumkin?", "Benzol va geksenni qanday farqlash mumkin?"],
  }),
  R({
    id: 'uglevod-0039', title: "Benzolning temir(III) bromid ishtirokida bromlanishi", level: '10-sinf', topic: "Arenlar: elektrofil o'rin olish (S_EAr)",
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 1 }, { species: 'Br2', state: 'l', volume_mL: 0.5 }],
    cond: { catalyst: 'FeBr3', note_uz: "Katalizator — temir qirindisi (u brom bilan FeBr₃ hosil qiladi) yoki tayyor FeBr₃." },
    eq: ['C6H6 + Br2 → C6H5Br + HBr↑'],
    tpl: 'SEAr', params: { arene: 'C6H6', reagent: 'Br–Br', catalyst: 'FeBr3', electrophile: 'Br⁺ (Br–Br···FeBr3)', sigma_complex: '[C6H6Br]⁺ (σ-kompleks)', product: 'C6H5Br', byproduct: 'HBr' },
    steps: ["FeBr₃ (Lyuis kislotasi) Br₂ molekulasini qutblaydi: Br^δ+–Br···FeBr₃^δ– kompleksi hosil bo'lib, kuchli elektrofil yuzaga keladi.", "Benzol halqasining π-elektronlari elektrofil Br⁺ ga hujum qiladi — aromatiklik vaqtincha buziladi va σ-kompleks (areniy kationi) hosil bo'ladi.", "FeBr₄⁻ ioni σ-kompleksdan protonni tortib oladi: aromatik halqa tiklanadi, HBr ajraladi va katalizator qayta hosil bo'ladi."],
    gas: gas('HBr', "nam havoda oq tuman hosil qiladi"),
    heat: 'ekzotermik', effects: ['bubbles', 'fog'],
    text: "Brom rangi asta-sekin yo'qoladi, aralashma isiydi va HBr gazi ajralib, nam havoda oq tuman hosil qiladi; naycha uchiga tutilgan nam ko'k lakmus qizaradi.",
    kin: "o'rtacha",
    app: ['probirka', 'gaz-naycha-egilgan', 'rezina-tiqin-1-teshikli-kichik', 'shtativ'],
    proc: ["Probirkaga 1 ml benzol va ozgina temir qirindisi soling.", "0,5 ml brom qo'shing va probirkani gaz chiqarish naychali tiqin bilan berkiting.", "Ajralayotgan gazga nam ko'k lakmus qog'ozini tuting.", "Reaksiya tugagach aralashmani suvga quyib, og'ir brombenzol qatlamini kuzating."],
    safety: SAFE.benzol + ' ' + SAFE.brom,
    expl: "Benzol katalizator (FeBr₃, AlCl₃) ishtirokida galogenlar bilan o'rin olish reaksiyasiga kirishadi va aromatik halqa saqlanib qoladi. Katalizator galogen molekulasini qutblab kuchli elektrofil hosil qiladi; ajralgan HBr reaksiya birikish emas, o'rin olish ekanini isbotlaydi.",
    q: ["Bu reaksiyada katalizatorning vazifasi nimadan iborat?", "HBr ajralishi reaksiya turini qanday isbotlaydi?", "Toluol bromlanganda qaysi izomerlar hosil bo'ladi?"],
  }),
  R({
    id: 'uglevod-0040', title: "Benzolning nitrolanishi — nitrobenzol olish", level: '10-sinf', topic: "Arenlar: nitrolash (S_EAr)",
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 1 }, { species: 'HNO3', state: 'l', volume_mL: 1 }],
    cond: { temp_min_C: 50, catalyst: 'H2SO4', note_uz: "Nitrolovchi aralashma (kons. HNO₃ + kons. H₂SO₄) ga benzol oz-ozdan qo'shiladi; harorat 50–60 °C da ushlab turiladi (yuqorida dinitrobenzol hosil bo'ladi)." },
    eq: ['C6H6 + HNO3 → C6H5NO2 + H2O', 'C6H6 + H⁺ + NO3⁻ → C6H5NO2 + H2O', 'C6H6 + H⁺ + NO3⁻ → C6H5NO2 + H2O'],
    tpl: 'SEAr', params: { arene: 'C6H6', reagent: 'HO–NO2', catalyst: 'H2SO4 (kons.)', electrophile: 'NO2⁺ (nitroniy kationi)', sigma_complex: '[C6H6NO2]⁺ (σ-kompleks)', product: 'C6H5NO2', byproduct: 'H2O' },
    steps: ["Konsentrlangan sulfat kislota nitrat kislotani protonlaydi; suv ajralib, kuchli elektrofil — nitroniy kationi NO₂⁺ hosil bo'ladi.", "Benzolning π-elektronlari NO₂⁺ ga hujum qilib σ-kompleks hosil qiladi.", "HSO₄⁻ ioni σ-kompleksdan protonni tortib oladi va aromatik halqa tiklanadi — nitrobenzol hosil bo'ladi."],
    heat: 'ekzotermik', effects: ['layers'],
    text: "Aralashma isiydi; sovuq suvga quyilganda tubiga sarg'ish, achchiq bodom hidli og'ir moysimon suyuqlik — nitrobenzol cho'kadi.",
    kin: "o'rtacha",
    app: ['probirka', 'suv-hammomi', 'termometr', 'tomizgich', 'kimyoviy-stakan'],
    proc: ["Probirkaga 1 ml konsentrlangan nitrat kislota quyib, sovitib turib ehtiyotkorlik bilan 1,5 ml konsentrlangan sulfat kislota qo'shing.", "Aralashmani sovitib, chayqatib turgan holda 1 ml benzolni tomchilab qo'shing.", "Probirkani 50–60 °C li suv hammomida 5–10 daqiqa ushlang.", "Aralashmani sovuq suvli stakanga quyib, tubga cho'kkan nitrobenzolni kuzating."],
    safety: SAFE.benzol + " Konsentrlangan nitrat va sulfat kislotalar terini kuchli kuydiradi; nitrobenzol zaharli va teri orqali so'riladi. Haroratni 60 °C dan oshirmang.",
    expl: "Benzol konsentrlangan nitrat va sulfat kislotalar aralashmasi bilan nitrolanadi; sulfat kislota suvni bog'lab, faol elektrofil NO₂⁺ hosil bo'lishini ta'minlaydi. Nitrobenzol anilin olishda boshlang'ich modda sifatida ishlatiladi.",
    q: ["Nitrolashda sulfat kislotaning vazifasi nima?", "Nitrobenzoldan anilin qanday olinadi?", "Nima uchun haroratni 60 °C dan oshirmaslik kerak?"],
  }),
  R({
    id: 'uglevod-0041', title: "Benzolga yorug'likda xlorning birikishi — geksaxlorsiklogeksan", level: '10-sinf', topic: "Arenlar: radikal birikish (Ad_R)",
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 1 }, { species: 'Cl2', state: 'g' }],
    cond: { light: true, note_uz: "Xlor benzol orqali kuchli UB nuri ostida, katalizatorsiz o'tkaziladi." },
    eq: ['C6H6 + 3Cl2 → C6H6Cl6'],
    tpl: 'AdR', params: { alkene: 'C6H6', reagent: 'Cl–Cl', initiator: 'hν (UB nuri)', radical: 'Cl•', product: 'C6H6Cl6' },
    steps: ["UB nuri Cl₂ molekulalarini radikallarga ajratadi: Cl₂ → 2Cl•.", "Cl• radikali benzol halqasiga birikib, aromatiklikni buzadi va siklogeksadienil radikali hosil bo'ladi.", "Radikal zanjir davom etib, halqadagi uchala \"qo'shbog'\" ga oltita xlor atomi birikadi — geksaxlorsiklogeksan."],
    ppt: ppt('C6H6Cl6', 'kristall'),
    heat: 'ekzotermik', effects: ['bubbles', 'crystals'],
    text: "Xlor rangi yo'qoladi, idishda oq kristall modda — geksaxlorsiklogeksan hosil bo'ladi.",
    kin: 'sekin',
    app: ['probirka', 'gaz-naycha-egilgan', 'yoritgich', 'shtativ'],
    proc: ["Probirkaga 1 ml benzol quying.", "Xlorni naycha orqali o'tkazib, probirkani UB lampa bilan yoriting.", "Hosil bo'lgan oq kristallarni kuzating."],
    safety: SAFE.benzol + " Xlor va geksaxlorsiklogeksan zaharli; faqat mo'rili shkafda, o'qituvchi namoyishi.",
    expl: "Qattiq yorug'likda va katalizatorsiz benzol radikal mexanizm bo'yicha uch molekula xlorni biriktiradi; bu benzolning to'yinmaganligini ko'rsatadi. Geksaxlorsiklogeksan ilgari insektitsid (geksaxloran) sifatida ishlatilgan, hozir zaharliligi sababli taqiqlangan.",
    q: ["Benzolning xlor bilan katalizatorli va yorug'likdagi reaksiyalarini solishtiring.", "Benzol vodorod bilan qanday sharoitda reaksiyaga kirishadi?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0042', title: "Benzolning katalizator ishtirokida xlorlanishi — xlorbenzol", level: '10-sinf', topic: "Arenlar: galogenlash (S_EAr)",
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 1 }, { species: 'Cl2', state: 'g' }],
    cond: { catalyst: 'FeCl3', note_uz: "Xlor qorong'ida, FeCl₃ (yoki AlCl₃) katalizatori ishtirokida benzol orqali o'tkaziladi." },
    eq: ['C6H6 + Cl2 → C6H5Cl + HCl↑'],
    tpl: 'SEAr', params: { arene: 'C6H6', reagent: 'Cl–Cl', catalyst: 'FeCl3', electrophile: 'Cl⁺ (Cl–Cl···FeCl3)', sigma_complex: '[C6H6Cl]⁺ (σ-kompleks)', product: 'C6H5Cl', byproduct: 'HCl' },
    steps: ["FeCl₃ xlor molekulasini qutblaydi: Cl^δ+–Cl···FeCl₃^δ– — elektrofil hosil bo'ladi.", "Benzol π-elektronlari elektrofilga hujum qilib σ-kompleks hosil qiladi.", "FeCl₄⁻ σ-kompleksdan protonni oladi: HCl ajraladi, aromatik halqa tiklanadi, katalizator qayta hosil bo'ladi."],
    gas: gas('HCl'),
    heat: 'ekzotermik', effects: ['bubbles', 'fog'],
    text: "Xlor yutiladi, chiqayotgan gaz nam havoda tutaydi (HCl) va nam ko'k lakmusni qizartiradi.",
    kin: "o'rtacha",
    app: ['probirka', 'gaz-naycha-egilgan', 'shtativ'],
    proc: ["Probirkaga 1 ml benzol va ozgina suvsiz FeCl₃ soling.", "Qorong'ida xlorni sekin o'tkazing.", "Ajralayotgan gazni nam lakmus qog'ozi bilan tekshiring."],
    safety: SAFE.benzol + " Xlor zaharli — mo'rili shkafda ishlang.",
    expl: "Lyuis kislotalari (FeCl₃, AlCl₃) ishtirokida benzol xlor bilan o'rin olish reaksiyasiga kirishib xlorbenzol hosil qiladi. Bir xil reagentlar sharoitga qarab turli mahsulot beradi: katalizator bilan — o'rin olish (S_EAr), yorug'likda katalizatorsiz — birikish (Ad_R).",
    q: ["Bu reaksiya va benzolning yorug'likdagi xlorlanishi mahsulotlarini solishtiring.", "Xlorbenzol qayerda ishlatiladi?"],
  }),
  R({
    id: 'uglevod-x04', title: "Benzolning xlormetan bilan alkillanishi (Fridel–Krafts reaksiyasi)", level: 'litsey', topic: "Arenlar: alkillash (S_EAr)",
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 1 }, { species: 'CH3Cl', state: 'g' }],
    cond: { catalyst: 'AlCl3', note_uz: "Xlormetan suvsiz AlCl₃ qo'shilgan benzol orqali o'tkaziladi." },
    eq: ['C6H6 + CH3Cl → C6H5CH3 + HCl↑'],
    tpl: 'SEAr', params: { arene: 'C6H6', reagent: 'CH3–Cl', catalyst: 'AlCl3', electrophile: 'CH3⁺ (CH3–Cl···AlCl3)', sigma_complex: '[C6H6CH3]⁺ (σ-kompleks)', product: 'C6H5–CH3', byproduct: 'HCl' },
    steps: ["AlCl₃ (Lyuis kislotasi) xlormetandagi xlor atomi bilan kompleks hosil qilib C–Cl bog'ini qutblaydi — elektrofil CH₃^δ+ hosil bo'ladi.", "Benzol π-elektronlari elektrofilga hujum qilib σ-kompleks hosil qiladi.", "AlCl₄⁻ σ-kompleksdan protonni oladi: HCl ajraladi, aromatik halqa tiklanadi, toluol hosil bo'ladi."],
    gas: gas('HCl'),
    heat: 'ekzotermik', effects: ['bubbles', 'fog'],
    text: "Gaz benzol bilan yutiladi, chiqish naychasidan HCl ajralib nam havoda tutaydi.",
    kin: "o'rtacha",
    app: ['dumaloq-tubli-kolba', 'gaz-naycha-egilgan', 'sharikli-sovutgich', 'shtativ'],
    proc: ["Kolbaga benzol va suvsiz AlCl₃ soling.", "Xlormetanni naycha orqali sekin o'tkazing.", "Ajralayotgan HCl ni nam lakmus qog'ozi bilan aniqlang."],
    safety: SAFE.benzol + " Suvsiz AlCl₃ nam havoda HCl ajratadi; xlormetan zaharli. Faqat o'qituvchi namoyishi.",
    expl: "Fridel–Krafts reaksiyasida benzol AlCl₃ ishtirokida galogenalkanlar bilan alkillanadi va benzol gomologlari hosil bo'ladi. Alkil guruh halqani faollashtirgani uchun mahsulot qayta alkillanishga moyil — aralashmada ksilollar ham hosil bo'ladi.",
    q: ["Benzoldan etilbenzol qanday olinadi?", "Nima uchun alkillashda poli-alkilbenzollar ham hosil bo'ladi?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0043', title: 'Benzolning yonishi', level: '10-sinf', topic: "Arenlar: yonish reaksiyasi",
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 0.5 }, { species: 'O2', state: 'g' }],
    cond: { ignition: true, ignition_C: 500, note_uz: "Chinni kosachadagi bir necha tomchi benzol mo'rili shkafda yondiriladi." },
    eq: ['2C6H6 + 15O2 → 12CO2↑ + 6H2O'],
    tpl: 'oksidlanish', params: { substrate: 'C6H6', oxidant: 'O2', product: 'CO2 + H2O (va qurum)' },
    steps: ["Benzol bug'lari alangada parchalanadi; uglerod ulushi yuqori (~92%) bo'lgani uchun kislorod yetishmaydi.", "Uglerodning bir qismi qurum holida ajraladi — alanga qattiq tutaydi.", "To'liq yonganda uglerod CO₂ ga, vodorod H₂O ga aylanadi."],
    gas: gas('CO2'),
    heat: 'kuchli-ekzotermik', flame: { color: '#ff9a20', desc_uz: "sarg'ish, ko'p qora tutun (qurum) chiqaradigan alanga" },
    effects: ['flame', 'smoke'],
    text: "Benzol sarg'ish, juda ko'p qora tutun chiqaradigan alanga bilan yonadi; kosacha ustida tutilgan sovuq jism qurum bilan qoplanadi.",
    kin: 'bir-zumda',
    app: ['chinni-kosacha', 'gugurt'],
    proc: ["Chinni kosachaga 3–5 tomchi benzol tomizing (mo'rili shkafda).", "Uzun cho'p yoki gugurt bilan yondiring.", "Alanga va tutunni kuzating, uni geksan alangasi bilan solishtiring."],
    safety: SAFE.benzol + " Yonish mahsulotlari (qurum) ham zararli; faqat o'qituvchi namoyishi, juda oz miqdorda.",
    expl: "Arenlarda uglerodning massa ulushi katta bo'lgani uchun ular havoda to'liq yonmaydi va qurum ajratadi. Tutaydigan alanga aromatik va ko'p to'yinmagan birikmalarni alkanlardan farqlash belgisi bo'la oladi.",
    q: ["Benzol va geksanning yonishini solishtiring; farqni tushuntiring.", "Benzolning to'liq yonish tenglamasini tuzing."],
  }),
  R({
    id: 'uglevod-0044', title: "Benzolning nikel katalizatorida gidrogenlanishi — siklogeksan olish", level: '10-sinf', topic: "Arenlar: vodorod biriktirish",
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 1 }, { species: 'H2', state: 'g' }],
    cond: { temp_min_C: 180, catalyst: 'Ni', note_uz: "Benzol bug'i va vodorod qizdirilgan nikel katalizatori ustidan bosim ostida o'tkaziladi." },
    eq: ['C6H6 + 3H2 → C6H12'],
    tpl: 'qaytarilish', params: { substrate: 'C6H6', reductant: '3H2 (Ni)', product: 'C6H12 (siklogeksan)' },
    steps: ["Vodorod nikel yuzasida atomlarga ajraladi, benzol π-tizimi bilan yuzaga adsorbsiyalanadi.", "Aromatik tizim barqaror bo'lgani uchun reaksiya alkenlarnikiga qaraganda og'irroq sharoitda (yuqori harorat va bosim) boradi.", "Uch molekula vodorod ketma-ket birikib, to'yingan siklogeksan hosil bo'ladi."],
    heat: 'ekzotermik', effects: ['condensate'],
    text: "Kondensatlangan mahsulot (siklogeksan) bromli suv va KMnO₄ eritmasini rangsizlantirmaydi.",
    kin: "o'rtacha",
    app: ['gaz-naycha-togri', 'kolba-isitgich', 'libix-sovutgichi', 'termometr'],
    proc: ["Nikel katalizatori solingan naychani qizdiring.", "Benzol bug'i va ortiqcha vodorod aralashmasini o'tkazing.", "Kondensatni yig'ib, bromli suv bilan sinab ko'ring."],
    safety: SAFE.benzol + " Vodorod portlovchi aralashma hosil qiladi; jarayon bosim ostida sanoat qurilmasida o'tkaziladi.",
    expl: "Benzol oddiy sharoitda birikish reaksiyalariga kirishmaydi, lekin katalizator ishtirokida va qizdirilganda uch molekula vodorodni biriktirib siklogeksanga aylanadi. Bu reaksiya benzolning olti a'zoli siklik tuzilishini tasdiqlaydi; siklogeksan kaprolaktam va neylon ishlab chiqarishda ishlatiladi.",
    q: ["Benzolni gidrogenlash uchun nima uchun etilenga qaraganda og'irroq sharoit kerak?", "Siklogeksan va benzolni qanday farqlash mumkin?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-x05', title: "Siklogeksanning platina ustida degidrogenlanishi — benzol olish", level: 'litsey', topic: "Arenlarni olish: sikloalkanlarni degidrogenlash (Zelinskiy)",
    reactants: [{ species: 'C6H12', state: 'l', volume_mL: 1 }],
    cond: { temp_min_C: 300, catalyst: 'Pt', note_uz: "Siklogeksan bug'lari ~300 °C gacha qizdirilgan platina katalizatori ustidan o'tkaziladi." },
    eq: ['C6H12 → C6H6↑ + 3H2↑'],
    tpl: 'oksidlanish', params: { substrate: 'C6H12 (siklogeksan)', oxidant: 'Pt, t° (degidrogenlash, −3H2)', product: 'C6H6' },
    steps: ["Siklogeksan molekulasi platina yuzasida adsorbsiyalanadi, C–H bog'lari faollashadi.", "Vodorod atomlari ketma-ket ajralib, halqada qo'shbog'lar paydo bo'ladi.", "Uch molekula vodorod ajralgach barqaror aromatik tizim — benzol hosil bo'ladi (gidrogenlashga teskari jarayon)."],
    gas: gas('H2'),
    heat: 'endotermik', effects: ['condensate'],
    text: "Chiqayotgan gaz (vodorod) yonadi; kondensat bromli suvni rangsizlantirmaydi, lekin benzolning o'ziga xos hidiga ega.",
    kin: "o'rtacha",
    app: ['gaz-naycha-togri', 'kolba-isitgich', 'libix-sovutgichi', 'termometr'],
    proc: ["Platina katalizatori solingan naychani ~300 °C gacha qizdiring.", "Siklogeksan bug'larini katalizator ustidan o'tkazing.", "Kondensatni yig'ing va ajralgan gazni sinab ko'ring."],
    safety: SAFE.benzol + " Vodorod portlovchi aralashma hosil qiladi; jarayon faqat virtual tajriba sifatida ko'riladi.",
    expl: "N.D. Zelinskiy olti a'zoli sikloalkanlar platina yoki palladiy ustida qizdirilganda vodorod ajratib arenlarga aylanishini ko'rsatgan. Bu reaksiya neftni qayta ishlashda (riforming) aromatik uglevodorodlar olishning asosi.",
    q: ["Metilsiklogeksan degidrogenlansa qaysi aren hosil bo'ladi?", "Bu reaksiya benzolni gidrogenlash reaksiyasi bilan qanday bog'liq?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0045', title: "Benzolning sulfolanishi — benzolsulfokislota olish", level: 'litsey', topic: "Arenlar: sulfolash (S_EAr)",
    reactants: [{ species: 'C6H6', state: 'l', volume_mL: 1 }, { species: 'H2SO4', state: 'aq', conc_M: 18, volume_mL: 2, conc_min_M: 15 }],
    cond: { temp_min_C: 80, note_uz: "Benzol konsentrlangan (yoki tutovchi) sulfat kislota bilan chayqatilib qizdiriladi." },
    eq: ['C6H6 + H2SO4 → C6H5SO3H + H2O'],
    tpl: 'SEAr', params: { arene: 'C6H6', reagent: 'H2SO4 (kons.)', catalyst: 'H2SO4', electrophile: 'SO3 (HSO3⁺)', sigma_complex: '[C6H6SO3H]⁺ (σ-kompleks)', product: 'C6H5SO3H', byproduct: 'H2O' },
    steps: ["Konsentrlangan sulfat kislotada oz miqdorda SO₃ (va HSO₃⁺) hosil bo'ladi — u elektrofil.", "Benzol π-elektronlari SO₃ dagi oltingugurt atomiga hujum qilib σ-kompleks hosil qiladi.", "Proton ajralib aromatik halqa tiklanadi — benzolsulfokislota hosil bo'ladi; reaksiya qaytar."],
    heat: 'ekzotermik', effects: ['dissolve'],
    text: "Chayqatib qizdirilganda benzol qatlami asta-sekin yo'qoladi — hosil bo'lgan sulfokislota sulfat kislotada eriydi va bir jinsli aralashma hosil bo'ladi.",
    kin: 'sekin',
    app: ['probirka', 'suv-hammomi', 'shtativ'],
    proc: ["Probirkaga 2 ml konsentrlangan sulfat kislota quying.", "1 ml benzol qo'shib, probirkani qaynoq suv hammomida chayqatib turib qizdiring.", "Benzol qatlamining yo'qolishini kuzating."],
    safety: SAFE.benzol + " Konsentrlangan sulfat kislota terini kuydiradi — ko'zoynak va qo'lqopda ishlang.",
    expl: "Benzol konsentrlangan sulfat kislota bilan qizdirilganda vodorod atomi sulfoguruh –SO₃H ga almashadi. Sulfokislotalar suvda yaxshi eriydigan kuchli kislotalar; ular yuvish vositalari va bo'yoqlar olishda ishlatiladi.",
    q: ["Sulfolashda elektrofil vazifasini qaysi zarracha bajaradi?", "Nima uchun benzol qatlami yo'qoladi?"],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0046', title: "Toluolning kaliy permanganat bilan qizdirilganda oksidlanishi", level: '10-sinf', topic: "Arenlar: benzol gomologlarining yon zanjiri bo'yicha oksidlanishi",
    reactants: [{ species: 'C6H5CH3', state: 'l', volume_mL: 0.5 }, { species: 'KMnO4', state: 'aq', conc_M: 0.05, volume_mL: 3 }],
    cond: { temp_min_C: 90, note_uz: "Aralashma qaynoq suv hammomida (yoki qaytar sovutgich bilan) qizdiriladi; muhit neytral." },
    eq: ['C6H5CH3 + 2KMnO4 → C6H5COOK + 2MnO2↓ + KOH + H2O', 'C6H5CH3 + 2K⁺ + 2MnO4⁻ → C6H5COO⁻ + K⁺ + 2MnO2↓ + K⁺ + OH⁻ + H2O', 'C6H5CH3 + 2MnO4⁻ → C6H5COO⁻ + 2MnO2↓ + OH⁻ + H2O', ['C⁻³ − 6e⁻ = C⁺³', 'Mn⁺⁷ + 3e⁻ = Mn⁺⁴']],
    tpl: 'oksidlanish', params: { substrate: 'C6H5–CH3', oxidant: 'MnO4⁻ (KMnO4)', product: 'C6H5–COO⁻ (benzoat)' },
    steps: ["Aromatik halqaga bog'langan metil guruhi (benzil holati) faollashgan: C–H bog'lari oson oksidlanadi.", "Permanganat metil guruhini bosqichma-bosqich spirt → aldegid → karboksil guruhgacha oksidlaydi (C⁻³ → C⁺³).", "Neytral muhitda kaliy benzoat hosil bo'ladi, Mn⁺⁷ esa MnO₂ ga qaytariladi; halqa o'zgarmaydi."],
    ppt: ppt('MnO2', 'kolloid'),
    color: [COL.kmno4, '#f4f0ec'],
    heat: 'ekzotermik', effects: ['turbidity', 'boil'],
    text: "Qizdirilganda binafsha rang asta-sekin yo'qoladi va qo'ng'ir MnO₂ cho'kmasi hosil bo'ladi. Filtratga xlorid kislota qo'shilsa, oq benzoy kislota kristallari cho'kadi.",
    kin: 'sekin',
    app: ['probirka', 'suv-hammomi', 'probirka-qisqichi', 'tomizgich'],
    proc: ["Probirkaga 3 ml KMnO₄ eritmasi va 0,5 ml toluol quying.", "Probirkani qaynoq suv hammomida chayqatib turib 5–10 daqiqa qizdiring.", "Rang o'zgarishini benzol bilan o'tkazilgan tajriba natijasi bilan solishtiring.", "Filtratga xlorid kislota qo'shib, benzoy kislota cho'kishini kuzating."],
    safety: "Toluol yonuvchan va zararli: ochiq alangada qizdirmang, mo'rili shkafda ishlang. " + SAFE.kmno4,
    expl: "Benzol halqasi oksidlanmaydi, lekin uning gomologlarida halqaga bog'langan alkil guruhi oksidlanib karboksil guruhga aylanadi. Shu sababli toluol permanganat eritmasini rangsizlantiradi, benzol esa yo'q — bu ularni farqlash usuli.",
    q: ["Etilbenzol oksidlanganda qaysi kislota hosil bo'ladi?", "Bu reaksiya uchun elektron balans tuzing.", "Benzol va toluolni qanday farqlash mumkin?"],
  }),
  R({
    id: 'uglevod-0047', title: "Toluolning kislotali muhitda kaliy permanganat bilan oksidlanishi — benzoy kislota", level: 'litsey', topic: "Arenlar: oksidlanish, oksidlanish-qaytarilish tenglamalarini tuzish",
    reactants: [{ species: 'C6H5CH3', state: 'l', volume_mL: 0.5 }, { species: 'KMnO4', state: 'aq', conc_M: 0.05, volume_mL: 3 }, { species: 'H2SO4', state: 'aq', conc_M: 1, volume_mL: 2 }],
    cond: { temp_min_C: 90, medium: 'kislotali', note_uz: "Aralashma sulfat kislota bilan kislotalanib qaynoq suv hammomida qizdiriladi." },
    eq: ['5C6H5CH3 + 6KMnO4 + 9H2SO4 → 5C6H5COOH + 6MnSO4 + 3K2SO4 + 14H2O', '5C6H5CH3 + 6K⁺ + 6MnO4⁻ + 18H⁺ + 9SO4²⁻ → 5C6H5COOH + 6Mn²⁺ + 6SO4²⁻ + 6K⁺ + 3SO4²⁻ + 14H2O', '5C6H5CH3 + 6MnO4⁻ + 18H⁺ → 5C6H5COOH + 6Mn²⁺ + 14H2O', ['C⁻³ − 6e⁻ = C⁺³', 'Mn⁺⁷ + 5e⁻ = Mn⁺²']],
    tpl: 'oksidlanish', params: { substrate: 'C6H5–CH3', oxidant: 'MnO4⁻, H⁺', product: 'C6H5–COOH' },
    steps: ["Metil guruhidagi uglerod (C⁻³) olti elektron berib karboksil uglerodiga (C⁺³) oksidlanadi.", "Kislotali muhitda Mn⁺⁷ besh elektron qabul qilib rangsiz Mn²⁺ ga qaytariladi.", "Elektronlar tenglashtiriladi: 5 molekula toluol 30 e⁻ beradi, 6 ta MnO₄⁻ 30 e⁻ oladi."],
    color: [COL.kmno4, '#ffffff'],
    heat: 'ekzotermik', effects: ['crystals'],
    text: "Qizdirilganda binafsha eritma rangsizlanadi; sovitilganda eritmadan oq ignasimon benzoy kislota kristallari ajralishi mumkin.",
    kin: 'sekin',
    app: ['probirka', 'suv-hammomi', 'probirka-qisqichi', 'tomizgich'],
    proc: ["Probirkaga 3 ml KMnO₄ eritmasi va 2 ml suyultirilgan sulfat kislota quying.", "0,5 ml toluol qo'shing.", "Qaynoq suv hammomida chayqatib turib qizdiring va rang o'zgarishini kuzating.", "Probirkani sovuq suvda sovitib kristallarni kuzating."],
    safety: "Toluol yonuvchan va zararli; sulfat kislota o'yuvchi. Ochiq alangada qizdirmang, ko'zoynak taqing.",
    expl: "Kislotali muhitda permanganat kuchliroq oksidlovchi bo'lib, Mn²⁺ gacha qaytariladi va eritma butunlay rangsizlanadi. Toluoldan benzoy kislota hosil bo'ladi; yon zanjir har qancha uzun bo'lsa ham halqaga yaqin uglerod karboksil guruhga aylanadi.",
    q: ["Neytral va kislotali muhitda reaksiya mahsulotlari qanday farq qiladi?", "Elektron-ion balans usulida tenglamani tenglashtiring."],
    conf: "o'rta",
  }),
  R({
    id: 'uglevod-0048', title: "Toluolning yorug'likda yon zanjir bo'yicha xlorlanishi", level: 'litsey', topic: "Arenlar: yon zanjirda radikal o'rin olish",
    reactants: [{ species: 'C6H5CH3', state: 'l', volume_mL: 1 }, { species: 'Cl2', state: 'g' }],
    cond: { light: true, note_uz: "Xlor qaynab turgan toluol orqali UB nuri ostida, katalizatorsiz o'tkaziladi." },
    eq: ['C6H5CH3 + Cl2 → C6H5CH2Cl + HCl↑'],
    tpl: 'SR', params: { substrate: 'C6H5–CH3', reagent: 'Cl–Cl', radical: 'Cl•', alkyl_radical: 'C6H5–•CH2 (benzil radikali)', product: 'C6H5–CH2Cl', byproduct: 'HCl' },
    steps: ["Yorug'lik Cl₂ ni Cl• radikallariga ajratadi.", "Cl• metil guruhidan vodorod atomini tortib oladi; hosil bo'lgan benzil radikali C₆H₅•CH₂ halqa bilan tutashganligi (rezonans) sababli barqaror.", "Benzil radikali Cl₂ dan xlor atomini olib benzilxlorid va yangi Cl• hosil qiladi."],
    gas: gas('HCl'),
    heat: 'ekzotermik', effects: ['bubbles', 'fog'],
    text: "Xlor rangi yo'qoladi, HCl ajralib nam havoda tutaydi; ko'zni achishtiradigan benzilxlorid hosil bo'ladi.",
    kin: "o'rtacha",
    app: ['dumaloq-tubli-kolba', 'sharikli-sovutgich', 'gaz-naycha-egilgan', 'yoritgich'],
    proc: ["Kolbaga toluol quyib, qaytar sovutgich o'rnating va qaynaguncha qizdiring.", "Xlorni naycha orqali o'tkazib, kolbani UB lampa bilan yoriting.", "Ajralayotgan HCl ni nam lakmus qog'ozi bilan aniqlang."],
    safety: "Xlor zaharli, benzilxlorid ko'zni kuchli achishtiradi (lakrimator); toluol yonuvchan. Faqat mo'rili shkafda, o'qituvchi namoyishi.",
    expl: "Sharoit reaksiya yo'nalishini belgilaydi: yorug'likda va qizdirilganda toluol yon zanjir bo'yicha radikal xlorlanadi, katalizator (FeCl₃) ishtirokida va qorong'ida esa halqaga o'rin olish ketadi. Benzil radikalining barqarorligi yon zanjirdagi vodorodlarning faolligini tushuntiradi.",
    q: ["Toluolning FeCl₃ ishtirokida xlorlanishidan qanday mahsulotlar hosil bo'ladi?", "Nima uchun benzil radikali barqaror?"],
  }),
  R({
    id: 'uglevod-0049', title: "Toluolning temir(III) bromid ishtirokida bromlanishi (orto- va para-yo'nalish)", level: 'litsey', topic: "Arenlar: o'rinbosarlarning yo'naltiruvchi ta'siri",
    reactants: [{ species: 'C6H5CH3', state: 'l', volume_mL: 1 }, { species: 'Br2', state: 'l', volume_mL: 0.5 }],
    cond: { catalyst: 'FeBr3', note_uz: "Reaksiya qorong'ida temir qirindisi (FeBr₃) ishtirokida o'tkaziladi." },
    eq: ['C6H5CH3 + Br2 → C6H4BrCH3 + HBr↑'],
    tpl: 'SEAr', params: { arene: 'C6H5–CH3', reagent: 'Br–Br', catalyst: 'FeBr3', electrophile: 'Br⁺ (Br–Br···FeBr3)', sigma_complex: '[CH3C6H5Br]⁺ (o-/p-σ-kompleks)', product: 'o- va p-CH3C6H4Br', byproduct: 'HBr' },
    steps: ["FeBr₃ bromni qutblab elektrofil Br⁺ hosil qiladi.", "Metil guruh elektronodonor (I-orinbosar): u halqadagi elektron zichligini oshiradi, ayniqsa orto- va para-holatlarda — hujum shu holatlarga yo'naladi.", "σ-kompleksdan proton ajralib, o-bromtoluol va p-bromtoluol aralashmasi hosil bo'ladi; toluol benzoldan tezroq reaksiyaga kirishadi."],
    gas: gas('HBr'),
    heat: 'ekzotermik', effects: ['bubbles', 'fog'],
    text: "Brom rangi benzolga qaraganda tezroq yo'qoladi, HBr ajralib nam havoda tutaydi.",
    kin: 'tez',
    app: ['probirka', 'gaz-naycha-egilgan', 'rezina-tiqin-1-teshikli-kichik', 'shtativ'],
    proc: ["Probirkaga 1 ml toluol va ozgina temir qirindisi soling.", "0,5 ml brom qo'shing va gaz chiqarish naychali tiqin bilan berkiting.", "Brom rangining yo'qolish tezligini benzol bilan solishtiring; ajralgan gazni nam lakmus bilan tekshiring."],
    safety: "Brom zaharli va kuydiradi, toluol yonuvchan: mo'rili shkafda, ko'zoynak va qo'lqopda ishlang.",
    expl: "Benzol halqasidagi o'rinbosarlar keyingi o'rin olishning tezligi va yo'nalishiga ta'sir qiladi. Metil guruh birinchi tur (orto-, para-) yo'naltiruvchi va halqani faollashtiruvchi; shuning uchun toluol benzolga nisbatan osonroq bromlanadi va asosan o- hamda p-bromtoluol hosil bo'ladi.",
    q: ["Birinchi va ikkinchi tur o'rinbosarlarga misollar keltiring.", "Nitrobenzol bromlanganda brom qaysi holatga birikadi?"],
  }),
  R({
    id: 'uglevod-0050', title: "Stirolning bromli suvni rangsizlantirishi", level: '10-sinf', topic: "Arenlar: yon zanjirdagi qo'shbog'ning reaksiyalari",
    reactants: [{ species: 'C6H5CH=CH2', state: 'l', volume_mL: 0.5 }, { species: 'bromli-suv', state: 'aq', volume_mL: 3 }],
    eq: ['C6H5CH=CH2 + Br2 → C6H5CHBrCH2Br'],
    tpl: 'AdE', params: { alkene: 'C6H5–CH=CH2', reagent: 'Br–Br', electrophile: 'Br⁺', nucleophile: 'Br⁻', intermediate: 'bromoniy ioni / benzil kationi', product: 'C6H5–CHBr–CH2Br' },
    steps: ["Bromning elektrofil hujumi aromatik halqaga emas, yon zanjirdagi faol qo'shbog'ga yo'naladi.", "Br⁺ birikib bromoniy ioni (yoki halqa bilan barqarorlashgan benzil kationi) hosil bo'ladi.", "Br⁻ ioni birikib 1,2-dibrom-1-feniletan hosil bo'ladi; benzol halqasi o'zgarmaydi."],
    color: [COL.bromliSuv, COL.rangsiz],
    heat: 'sezilarsiz', effects: ['layers'],
    text: "Chayqatilganda bromli suv tez rangsizlanadi (benzoldan farqli o'laroq).",
    kin: 'tez',
    app: ['probirka', 'tomizgich'],
    proc: ["Probirkaga 3 ml bromli suv quying.", "0,5 ml stirol qo'shib chayqating.", "Natijani benzol bilan o'tkazilgan tajriba bilan solishtiring."],
    safety: SAFE.brom + ' Stirol yonuvchan va zararli bug\'lar chiqaradi.',
    expl: "Stirol molekulasida aromatik halqa va yon zanjirda alken tipidagi qo'shbog' bor. Brom halqaga emas, qo'shbog'ga birikadi, shuning uchun stirol alkenlar kabi bromli suvni rangsizlantiradi; bu qo'shbog' stirolning polimerlanishida ham ishtirok etadi.",
    q: ["Stirol KMnO₄ eritmasini rangsizlantiradimi?", "Stirol va etilbenzolni qanday farqlash mumkin?"],
  }),
];

// Ishga tushirilganda faylni yozish (boshqa skriptlar faqat yordamchilarni import qiladi)
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const path = join(DATA, 'reactions', `${CAT}.json`);
  const keep = existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')).reactions.filter((r) => r.id === 'uglevod-0001') : [];
  records.forEach((r, i) => { r.id = `uglevod-${String(i + 2).padStart(4, '0')}`; });
  writeCategory(CAT, records, keep);
}
