// Moddalar bazasi uchun boshlang'ich ma'lumot. Tuzlar kation x anion jadvalidan avtomatik yasaladi,
// qolgan moddalar shu yerda qo'lda yozilgan. Natija: frontend/lab/data/substances.json
//
// Qisqa maydonlar:
//   f — formula (tenglamalarda shu ko'rinishda yoziladi), n — o'zbekcha nomi, c — sinf, st — standart holat (s/l/g/aq)
//   col — tashqi rang, form — ko'rinish shakli, d — zichlik (g/sm³; gaz uchun yo'q), mp/bp — °C (ma'lum bo'lsa)
//   hz — xavf belgilari, sto — saqlash, sol — eritmalar [konsentratsiya M, darajasi], diss — eritmadagi ionlar
//   tag — izomer belgisi (bir xil formulali moddalarni farqlash: "C6H12O6(fruktoza)")

export const METALS = [
  { f: 'Li', n: 'litiy', col: '#c9c9c4', form: 'bo\'lak', d: 0.534, mp: 180.5, hz: ['yonuvchan', 'korroziv'], sto: 'kerosin-ostida', forms: ['bo\'lak'], desc: 'yumshoq kumushrang-oq metall' },
  { f: 'Na', n: 'natriy', col: '#cfcfca', form: 'bo\'lak', d: 0.968, mp: 97.8, hz: ['yonuvchan', 'korroziv'], sto: 'kerosin-ostida', forms: ['bo\'lak'], desc: 'pichoq bilan kesiladigan yumshoq kumushrang metall' },
  { f: 'K', n: 'kaliy', col: '#c8c8c2', form: 'bo\'lak', d: 0.862, mp: 63.5, hz: ['yonuvchan', 'korroziv'], sto: 'kerosin-ostida', forms: ['bo\'lak'], desc: 'juda yumshoq kumushrang metall' },
  { f: 'Ca', n: 'kalsiy', col: '#bdbdb6', form: 'bo\'lak', d: 1.55, mp: 842, hz: ['yonuvchan'], sto: 'germetik-idish', forms: ['bo\'lak', 'qirindi'], desc: 'kulrang-oq metall' },
  { f: 'Mg', n: 'magniy', col: '#bfc3c7', form: 'lenta', d: 1.74, mp: 650, hz: ['yonuvchan'], sto: 'tiqinli-sklyanka', forms: ['lenta', 'qirindi', 'kukun'], desc: 'kumushrang-oq yengil metall' },
  { f: 'Al', n: 'alyuminiy', col: '#c4c8cc', form: 'qirindi', d: 2.70, mp: 660.3, hz: [], sto: 'tiqinli-sklyanka', forms: ['qirindi', 'kukun', 'plastinka', 'sim'], desc: 'kumushrang-oq yengil metall' },
  { f: 'Zn', n: 'rux', col: '#a9adb1', form: 'granula', d: 7.14, mp: 419.5, hz: [], sto: 'tiqinli-sklyanka', forms: ['granula', 'kukun', 'plastinka'], desc: 'ko\'kimtir-kulrang metall' },
  { f: 'Fe', n: 'temir', col: '#8a8d90', form: 'mix', d: 7.87, mp: 1538, hz: [], sto: 'tiqinli-sklyanka', forms: ['mix', 'qirindi', 'kukun', 'sim'], desc: 'kulrang metall' },
  { f: 'Cu', n: 'mis', col: '#c27a4a', form: 'sim', d: 8.96, mp: 1085, hz: [], sto: 'tiqinli-sklyanka', forms: ['sim', 'plastinka', 'qirindi'], desc: 'qizg\'ish metall' },
  { f: 'Ag', n: 'kumush', col: '#d8d8d8', form: 'sim', d: 10.49, mp: 961.8, hz: [], sto: 'tiqinli-sklyanka', forms: ['sim'], desc: 'yaltiroq oq metall' },
  { f: 'Pb', n: 'qo\'rg\'oshin', col: '#7d8189', form: 'plastinka', d: 11.34, mp: 327.5, hz: ['zaharli', 'atrof-muhit'], sto: 'tiqinli-sklyanka', forms: ['plastinka', 'granula'], desc: 'og\'ir ko\'kimtir-kulrang yumshoq metall' },
  { f: 'Sn', n: 'qalay', col: '#c8c8c0', form: 'granula', d: 7.29, mp: 231.9, hz: [], sto: 'tiqinli-sklyanka', forms: ['granula', 'plastinka'], desc: 'kumushrang-oq metall' },
  { f: 'Ni', n: 'nikel', col: '#b5b2a8', form: 'plastinka', d: 8.91, mp: 1455, hz: ['zararli'], sto: 'tiqinli-sklyanka', forms: ['plastinka', 'kukun'], desc: 'kumushrang metall' },
  { f: 'Cr', n: 'xrom', col: '#b8bcc4', form: 'bo\'lak', d: 7.19, mp: 1907, hz: [], sto: 'tiqinli-sklyanka', forms: ['bo\'lak', 'kukun'], desc: 'ko\'kimtir-oq qattiq metall' },
  { f: 'Mn', n: 'marganes', col: '#a8a49c', form: 'bo\'lak', d: 7.21, mp: 1246, hz: [], sto: 'tiqinli-sklyanka', forms: ['bo\'lak', 'kukun'], desc: 'kulrang-oq mo\'rt metall' },
  { f: 'Co', n: 'kobalt', col: '#a8a8b0', form: 'bo\'lak', d: 8.9, mp: 1495, hz: ['zararli'], sto: 'tiqinli-sklyanka', forms: ['bo\'lak'], desc: 'kumushrang metall', reagent: false },
  { f: 'Pt', n: 'platina', col: '#d4d4d0', form: 'sim', d: 21.45, mp: 1768, hz: [], sto: 'tiqinli-sklyanka', forms: ['sim'], desc: 'inert oq metall (elektrod)', reagent: false },
  { f: 'Hg', n: 'simob', st: 'l', col: '#c8ccd0', form: 'suyuqlik', d: 13.53, mp: -38.8, bp: 356.7, hz: ['zaharli', 'atrof-muhit'], sto: 'shlif-tiqinli-sklyanka', desc: 'suyuq kumushrang metall', reagent: false },
];

export const NONMETALS = [
  { f: 'H2', n: 'vodorod', st: 'g', col: null, hz: ['yonuvchan', 'bosim'], sto: 'ballon', gas: { ws: 'kam' }, desc: 'rangsiz, hidsiz, eng yengil gaz' },
  { f: 'O2', n: 'kislorod', st: 'g', col: null, hz: ['oksidlovchi', 'bosim'], sto: 'ballon', gas: { ws: 'kam' }, desc: 'rangsiz, hidsiz gaz; yonishni quvvatlaydi' },
  { f: 'N2', n: 'azot', st: 'g', col: null, hz: ['bosim'], sto: 'ballon', gas: { ws: 'kam' }, desc: 'rangsiz, hidsiz, inert gaz' },
  { f: 'Cl2', n: 'xlor', st: 'g', col: '#cfd65a', hz: ['zaharli', 'oksidlovchi', 'atrof-muhit'], sto: 'ballon', gas: { ws: 'o\'rtacha', smell: 'bo\'g\'uvchi o\'tkir hid', toxic: true }, desc: 'sarg\'ish-yashil, bo\'g\'uvchi zaharli gaz', aq: { col: '#e8ecb0', ref: 0.05 } },
  { f: 'Br2', n: 'brom', st: 'l', col: '#8a2a12', d: 3.12, mp: -7.2, bp: 58.8, hz: ['zaharli', 'korroziv', 'atrof-muhit'], sto: 'shlif-tiqinli-sklyanka', gas: { ws: 'o\'rtacha', smell: 'o\'tkir bo\'g\'uvchi hid', toxic: true, col: '#b84a20' }, desc: 'qizil-qo\'ng\'ir og\'ir suyuqlik, tez bug\'lanadi', aq: { col: '#e8a040', ref: 0.02 }, miscible: false },
  { f: 'I2', n: 'yod', st: 's', col: '#3a2a4a', form: 'kristall', d: 4.93, mp: 113.7, hz: ['zararli', 'atrof-muhit'], sto: 'qoramtir-sklyanka', gas: { col: '#8a3ab0', toxic: true }, desc: 'to\'q binafsha-kulrang yaltiroq kristallar, qizdirilganda sublimatlanadi', aq: { col: '#b0682a', ref: 0.002 } },
  { f: 'S', n: 'oltingugurt', st: 's', col: '#f2dc3a', form: 'kukun', d: 2.07, mp: 115.2, bp: 444.6, hz: ['yonuvchan'], sto: 'tiqinli-sklyanka', desc: 'sariq kukun' },
  { f: 'P', n: 'qizil fosfor', st: 's', col: '#a8322a', form: 'kukun', d: 2.34, hz: ['yonuvchan'], sto: 'tiqinli-sklyanka', desc: 'to\'q qizil kukun' },
  { f: 'C', n: 'ko\'mir', st: 's', col: '#1e1e1e', form: 'bo\'lak', d: 1.8, hz: ['yonuvchan'], sto: 'tiqinli-sklyanka', desc: 'qora g\'ovak modda (pista ko\'mir)' },
  { f: 'C', tag: 'grafit', n: 'grafit', st: 's', col: '#3a3a3e', form: 'bo\'lak', d: 2.26, hz: [], sto: 'tiqinli-sklyanka', desc: 'kulrang-qora yaltiroq, elektr o\'tkazuvchi', index: false },
  { f: 'Si', n: 'kremniy', st: 's', col: '#5a5e66', form: 'kukun', d: 2.33, mp: 1414, hz: [], sto: 'tiqinli-sklyanka', desc: 'to\'q kulrang yaltiroq kristall modda' },
];

// o: oksid turi (asosli/kislotali/amfoter/befarq), hyd: suv bilan hosil qiladigan modda
export const OXIDES = [
  { f: 'Na2O', n: 'natriy oksid', col: '#f4f4ee', form: 'kukun', o: 'asosli', hyd: 'NaOH', hz: ['korroziv'], sto: 'germetik-idish' },
  { f: 'K2O', n: 'kaliy oksid', col: '#f4f4ee', form: 'kukun', o: 'asosli', hyd: 'KOH', hz: ['korroziv'], sto: 'germetik-idish' },
  { f: 'CaO', n: 'kalsiy oksid (so\'ndirilmagan ohak)', col: '#f2f2ec', form: 'bo\'lak', d: 3.34, o: 'asosli', hyd: 'Ca(OH)2', hz: ['korroziv'], sto: 'germetik-idish' },
  { f: 'MgO', n: 'magniy oksid', col: '#f6f6f2', form: 'kukun', d: 3.58, o: 'asosli', hyd: 'Mg(OH)2', hyd_slow: true, hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'BaO', n: 'bariy oksid', col: '#f0f0ea', form: 'kukun', o: 'asosli', hyd: 'Ba(OH)2', hz: ['zaharli', 'korroziv'], sto: 'germetik-idish' },
  { f: 'Al2O3', n: 'alyuminiy oksid', col: '#f6f6f2', form: 'kukun', d: 3.95, o: 'amfoter', hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'ZnO', n: 'rux oksid', col: '#f6f6f0', form: 'kukun', d: 5.61, o: 'amfoter', hz: ['atrof-muhit'], sto: 'tiqinli-sklyanka', desc: 'oq kukun, qizdirilganda sarg\'ayadi' },
  { f: 'FeO', n: 'temir(II) oksid', col: '#1c1c1a', form: 'kukun', o: 'asosli', hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'Fe2O3', n: 'temir(III) oksid', col: '#8e2f1c', form: 'kukun', d: 5.24, o: 'amfoter', hz: [], sto: 'tiqinli-sklyanka', desc: 'qizil-qo\'ng\'ir kukun' },
  { f: 'Fe3O4', n: 'temir(II,III) oksid (temir kuyindisi)', col: '#222220', form: 'kukun', d: 5.17, o: 'aralash', hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'CuO', n: 'mis(II) oksid', col: '#1a1a1a', form: 'kukun', d: 6.31, o: 'asosli', hz: ['zararli', 'atrof-muhit'], sto: 'tiqinli-sklyanka' },
  { f: 'Cu2O', n: 'mis(I) oksid', col: '#b8321e', form: 'kukun', d: 6.0, o: 'asosli', hz: ['zararli'], sto: 'tiqinli-sklyanka', desc: 'qizil kukun' },
  { f: 'MnO2', n: 'marganes(IV) oksid', col: '#2a2420', form: 'kukun', d: 5.03, o: 'amfoter', hz: ['zararli', 'oksidlovchi'], sto: 'tiqinli-sklyanka', redox: 'oksidlovchi' },
  { f: 'Cr2O3', n: 'xrom(III) oksid', col: '#3f7a3a', form: 'kukun', d: 5.22, o: 'amfoter', hz: [], sto: 'tiqinli-sklyanka', desc: 'yashil kukun' },
  { f: 'CrO3', n: 'xrom(VI) oksid', col: '#8a1410', form: 'kristall', d: 2.7, o: 'kislotali', hyd: 'H2CrO4', hz: ['zaharli', 'oksidlovchi', 'korroziv', 'kanserogen'], sto: 'shlif-tiqinli-sklyanka', redox: 'oksidlovchi', desc: 'to\'q qizil igna kristallar' },
  { f: 'PbO', n: 'qo\'rg\'oshin(II) oksid', col: '#e8b830', form: 'kukun', d: 9.53, o: 'amfoter', hz: ['zaharli', 'atrof-muhit'], sto: 'tiqinli-sklyanka' },
  { f: 'PbO2', n: 'qo\'rg\'oshin(IV) oksid', col: '#3a2a1e', form: 'kukun', d: 9.38, o: 'amfoter', hz: ['zaharli', 'oksidlovchi'], sto: 'tiqinli-sklyanka', redox: 'oksidlovchi' },
  { f: 'HgO', n: 'simob(II) oksid', col: '#d8541a', form: 'kukun', d: 11.14, o: 'asosli', hz: ['zaharli', 'atrof-muhit'], sto: 'tiqinli-sklyanka', desc: 'to\'q sariq-qizil kukun' },
  { f: 'Ag2O', n: 'kumush(I) oksid', col: '#3a2a20', form: 'kukun', d: 7.14, o: 'asosli', hz: ['oksidlovchi'], sto: 'qoramtir-sklyanka', desc: 'qo\'ng\'ir-qora kukun' },
  { f: 'SiO2', n: 'kremniy(IV) oksid (qum)', col: '#f0ece0', form: 'kukun', d: 2.65, o: 'kislotali', hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'P2O5', n: 'fosfor(V) oksid', col: '#f8f8f6', form: 'kukun', d: 2.39, o: 'kislotali', hyd: 'H3PO4', hz: ['korroziv'], sto: 'germetik-idish', desc: 'oq gigroskopik kukun' },
  { f: 'CO', n: 'uglerod(II) oksid (is gazi)', st: 'g', o: 'befarq', hz: ['zaharli', 'yonuvchan'], sto: 'ballon', gas: { ws: 'kam', toxic: true } },
  { f: 'CO2', n: 'uglerod(IV) oksid (karbonat angidrid)', st: 'g', o: 'kislotali', hyd: 'H2CO3', hz: [], sto: 'ballon', gas: { ws: 'o\'rtacha' }, desc: 'rangsiz, hidsiz gaz; yonishni quvvatlamaydi' },
  { f: 'SO2', n: 'oltingugurt(IV) oksid (sulfit angidrid)', st: 'g', o: 'kislotali', hyd: 'H2SO3', hz: ['zaharli'], sto: 'ballon', gas: { ws: 'yaxshi', smell: 'yongan oltingugurtning o\'tkir hidi', toxic: true } },
  { f: 'SO3', n: 'oltingugurt(VI) oksid (sulfat angidrid)', st: 's', col: '#f6f6f2', form: 'kristall', mp: 16.9, bp: 45, o: 'kislotali', hyd: 'H2SO4', hz: ['korroziv'], sto: 'germetik-idish', reagent: false },
  { f: 'NO', n: 'azot(II) oksid', st: 'g', o: 'befarq', hz: ['zaharli', 'oksidlovchi'], sto: 'ballon', gas: { ws: 'kam', toxic: true }, desc: 'rangsiz gaz, havoda qo\'ng\'ir NO₂ ga aylanadi', reagent: false },
  { f: 'NO2', n: 'azot(IV) oksid', st: 'g', o: 'kislotali', hz: ['zaharli', 'oksidlovchi'], sto: 'ballon', gas: { ws: 'reaksiya', smell: 'o\'tkir hid', toxic: true, col: '#a8461c' }, desc: 'qo\'ng\'ir zaharli gaz ("tulki dumi")', reagent: false },
  { f: 'H2O', n: 'suv', st: 'l', col: null, form: 'suyuqlik', d: 0.998, mp: 0, bp: 100, hz: [], sto: 'yuvgich', o: 'befarq', desc: 'distillangan suv' },
  { f: 'H2O2', n: 'vodorod peroksid', st: 'aq', col: null, form: 'suyuqlik', d: 1.01, hz: ['oksidlovchi', 'korroziv'], sto: 'qoramtir-sklyanka', redox: 'ikkalasi', sol: [[0.88, 'suyultirilgan', '3%'], [9.8, 'konsentrlangan', '30%']] },
];

// Kislotalar. sol: [konsentratsiya M, daraja, yorliq]
export const ACIDS = [
  { f: 'HCl', n: 'xlorid kislota', st: 'aq', hz: ['korroziv'], sto: 'shlif-tiqinli-sklyanka', strong: true, sol: [[0.1, 'suyultirilgan', '0,1 M'], [1, 'suyultirilgan', '1 M'], [2, 'suyultirilgan', '2 M'], [11.6, 'konsentrlangan', '36%']], conc_from: 6, gas: { ws: 'juda-yaxshi', smell: 'o\'tkir bo\'g\'uvchi hid', toxic: true }, desc: 'rangsiz suyuqlik; konsentrlangani havoda "tutaydi"' },
  { f: 'H2SO4', n: 'sulfat kislota', st: 'l', d: 1.84, bp: 337, hz: ['korroziv'], sto: 'shlif-tiqinli-sklyanka', sol: [[0.05, 'suyultirilgan', '0,05 M'], [0.5, 'suyultirilgan', '0,5 M'], [1, 'suyultirilgan', '1 M'], [18, 'konsentrlangan', '96%']], conc_from: 12, heat_dil: 'kuchli-ekzotermik', redox: 'oksidlovchi', desc: 'rangsiz moysimon og\'ir suyuqlik' },
  { f: 'HNO3', n: 'nitrat kislota', st: 'l', d: 1.39, bp: 83, hz: ['korroziv', 'oksidlovchi'], sto: 'qoramtir-sklyanka', strong: true, sol: [[0.1, 'suyultirilgan', '0,1 M'], [2, 'suyultirilgan', '2 M'], [6, 'o\'rtacha', '30%'], [14.4, 'konsentrlangan', '65%']], conc_from: 10, redox: 'oksidlovchi', desc: 'rangsiz suyuqlik, yorug\'likda sarg\'ayadi' },
  { f: 'H3PO4', n: 'fosfat (ortofosfat) kislota', st: 's', d: 1.88, hz: ['korroziv'], sto: 'tiqinli-sklyanka', sol: [[0.1, 'suyultirilgan', '0,1 M'], [1, 'suyultirilgan', '1 M'], [14.7, 'konsentrlangan', '85%']] },
  { f: 'H2CO3', n: 'karbonat kislota', st: 'aq', hz: [], reagent: false, desc: 'faqat eritmada mavjud, beqaror' },
  { f: 'H2SO3', n: 'sulfit kislota', st: 'aq', hz: ['korroziv'], sto: 'shlif-tiqinli-sklyanka', sol: [[0.5, 'suyultirilgan', '~5%']], redox: 'qaytaruvchi', desc: 'SO₂ ning suvdagi eritmasi, o\'tkir hidli' },
  { f: 'H2S', n: 'vodorod sulfid', st: 'g', hz: ['zaharli', 'yonuvchan'], sto: 'kipp-apparati', gas: { ws: 'o\'rtacha', smell: 'palag\'da tuxum hidi', toxic: true }, sol: [[0.1, 'suyultirilgan', 'vodorod sulfidli suv']], redox: 'qaytaruvchi' },
  { f: 'HF', n: 'ftorid kislota', st: 'aq', hz: ['zaharli', 'korroziv'], sto: 'polietilen-idish', reagent: false, desc: 'shishani yemiradi, faqat polietilen idishda saqlanadi' },
  { f: 'HBr', n: 'bromid kislota', st: 'aq', hz: ['korroziv'], sto: 'shlif-tiqinli-sklyanka', strong: true, sol: [[1, 'suyultirilgan', '1 M']], gas: { ws: 'juda-yaxshi', toxic: true }, redox: 'qaytaruvchi' },
  { f: 'HI', n: 'yodid kislota', st: 'aq', hz: ['korroziv'], sto: 'qoramtir-sklyanka', strong: true, sol: [[1, 'suyultirilgan', '1 M']], redox: 'qaytaruvchi' },
  { f: 'HClO', n: 'gipoxlorit kislota', st: 'aq', hz: ['oksidlovchi'], reagent: false, redox: 'oksidlovchi', desc: 'xlorli suvda hosil bo\'ladi, oqartiradi' },
  { f: 'HClO4', n: 'perxlorat kislota', st: 'l', hz: ['korroziv', 'oksidlovchi'], strong: true, reagent: false },
  { f: 'H2SiO3', n: 'silikat kislota', st: 's', col: '#f2f2ee', form: 'iviqsimon', hz: [], reagent: false, desc: 'suvda erimaydigan iviqsimon modda' },
  { f: 'HNO2', n: 'nitrit kislota', st: 'aq', hz: ['zaharli'], reagent: false, desc: 'faqat sovuq suyultirilgan eritmada mavjud' },
  { f: 'H2CrO4', n: 'xromat kislota', st: 'aq', hz: ['zaharli', 'kanserogen', 'oksidlovchi'], reagent: false },
];

export const BASES = [
  { f: 'NaOH', diss: { 'Na^+': 1, 'OH^-': 1 }, s: 1090, n: 'natriy gidroksid (o\'yuvchi natriy)', st: 's', col: '#f8f8f6', form: 'granula', d: 2.13, mp: 318, hz: ['korroziv'], sto: 'rezina-tiqinli-sklyanka', sol: [[0.1, 'suyultirilgan', '0,1 M'], [1, 'suyultirilgan', '1 M'], [2, 'suyultirilgan', '2 M'], [10, 'konsentrlangan', '30%']], heat_dil: 'ekzotermik' },
  { f: 'KOH', diss: { 'K^+': 1, 'OH^-': 1 }, s: 1120, n: 'kaliy gidroksid (o\'yuvchi kaliy)', st: 's', col: '#f8f8f6', form: 'granula', d: 2.12, mp: 360, hz: ['korroziv'], sto: 'rezina-tiqinli-sklyanka', sol: [[0.1, 'suyultirilgan', '0,1 M'], [1, 'suyultirilgan', '1 M'], [2, 'suyultirilgan', '2 M']], heat_dil: 'ekzotermik' },
  { f: 'LiOH', diss: { 'Li^+': 1, 'OH^-': 1 }, s: 128, n: 'litiy gidroksid', st: 's', col: '#f8f8f6', form: 'kukun', hz: ['korroziv'], sto: 'rezina-tiqinli-sklyanka', sol: [[0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'NH3·H2O', aliases: ['NH4OH'], n: 'ammiakli suv (ammoniy gidroksid)', st: 'aq', hz: ['korroziv', 'atrof-muhit'], sto: 'shlif-tiqinli-sklyanka', sol: [[2, 'suyultirilgan', '2 M'], [13.3, 'konsentrlangan', '25%']], diss_mol: { NH3: 1, H2O: 1 }, desc: 'ammiakning suvdagi eritmasi, o\'tkir hidli' },
  { f: 'NH3', n: 'ammiak', st: 'g', hz: ['zaharli', 'korroziv'], sto: 'ballon', gas: { ws: 'juda-yaxshi', smell: 'o\'tkir (novshadil) hid', toxic: true } },
];

// Tuzlar uchun qattiq holatdagi ranglar va cho'kma ko'rinishlari (kation x anion jadvalidan yasalganlarga qo'shimcha)
// tex: suzmasimon | iviqsimon | mayda-kristall | kristall | kukunsimon | oltin-yomg'ir | kolloid
export const SALT_APPEARANCE = {
  // gidroksidlar
  'Mg(OH)2': ['#f6f6f2', 'iviqsimon'], 'Ca(OH)2': ['#f6f6f2', 'kukunsimon'], 'Sr(OH)2': ['#f6f6f2', 'kukunsimon'],
  'Al(OH)3': ['#f2f4f4', 'iviqsimon'], 'Cr(OH)3': ['#6f8f6a', 'iviqsimon'], 'Fe(OH)2': ['#c8d8b0', 'iviqsimon'],
  'Fe(OH)3': ['#9a4a1c', 'iviqsimon'], 'Zn(OH)2': ['#f4f6f6', 'iviqsimon'], 'Mn(OH)2': ['#f0e2dc', 'iviqsimon'],
  'Ni(OH)2': ['#7ec27a', 'iviqsimon'], 'Co(OH)2': ['#d97a9a', 'iviqsimon'], 'Cu(OH)2': ['#4a9be0', 'iviqsimon'],
  'Pb(OH)2': ['#f4f4f0', 'iviqsimon'], 'Sn(OH)2': ['#f4f4f0', 'iviqsimon'],
  // galogenidlar
  AgCl: ['#f8f8f4', 'suzmasimon'], AgBr: ['#f2ecc0', 'suzmasimon'], AgI: ['#f2df5a', 'suzmasimon'],
  PbCl2: ['#f6f6f2', 'kristall'], PbBr2: ['#f6f6f2', 'kristall'], PbI2: ['#ffd21a', 'oltin-yomg\'ir'], SnI2: ['#e0702a', 'mayda-kristall'],
  CaF2: ['#f6f6f2', 'kukunsimon'], SrF2: ['#f6f6f2', 'kukunsimon'], MgF2: ['#f6f6f2', 'kukunsimon'], BaF2: ['#f6f6f2', 'kukunsimon'],
  // sulfidlar
  CuS: ['#151515', 'kukunsimon'], PbS: ['#151515', 'kukunsimon'], Ag2S: ['#151515', 'kukunsimon'], FeS: ['#1a1a18', 'kukunsimon'],
  ZnS: ['#f4f4ee', 'kukunsimon'], MnS: ['#e8b7a0', 'kukunsimon'], NiS: ['#151515', 'kukunsimon'], CoS: ['#151515', 'kukunsimon'],
  SnS: ['#5a3a20', 'kukunsimon'], CaS: ['#f2f2ec', 'kukunsimon'],
  // sulfitlar, sulfatlar
  BaSO3: ['#f6f6f2', 'mayda-kristall'], CaSO3: ['#f6f6f2', 'mayda-kristall'], SrSO3: ['#f6f6f2', 'mayda-kristall'], MgSO3: ['#f6f6f2', 'mayda-kristall'],
  FeSO3: ['#e2e8d8', 'mayda-kristall'], ZnSO3: ['#f6f6f2', 'mayda-kristall'], MnSO3: ['#f2e6e2', 'mayda-kristall'], NiSO3: ['#b8deb0', 'mayda-kristall'],
  CoSO3: ['#e8b0c0', 'mayda-kristall'], Ag2SO3: ['#f6f6f2', 'mayda-kristall'], PbSO3: ['#f6f6f2', 'mayda-kristall'],
  BaSO4: ['#f4f4ee', 'mayda-kristall'], SrSO4: ['#f6f6f2', 'mayda-kristall'], CaSO4: ['#f6f6f2', 'mayda-kristall'], PbSO4: ['#f6f6f2', 'mayda-kristall'], Ag2SO4: ['#f6f6f2', 'kristall'],
  AgNO2: ['#f2eac0', 'kristall'],
  // karbonatlar
  BaCO3: ['#f6f6f2', 'mayda-kristall'], CaCO3: ['#f6f6f2', 'mayda-kristall'], SrCO3: ['#f6f6f2', 'mayda-kristall'], MgCO3: ['#f6f6f2', 'kukunsimon'],
  FeCO3: ['#d8dcc8', 'kukunsimon'], ZnCO3: ['#f6f6f2', 'kukunsimon'], MnCO3: ['#f2dcd6', 'kukunsimon'], NiCO3: ['#8cc88c', 'kukunsimon'],
  CoCO3: ['#e09ab0', 'kukunsimon'], Ag2CO3: ['#f0e8c8', 'kukunsimon'], PbCO3: ['#f6f6f2', 'kukunsimon'], Li2CO3: ['#f6f6f2', 'kukunsimon'],
  // fosfatlar
  'Ba3(PO4)2': ['#f6f6f2', 'mayda-kristall'], 'Ca3(PO4)2': ['#f6f6f2', 'iviqsimon'], 'Sr3(PO4)2': ['#f6f6f2', 'mayda-kristall'], 'Mg3(PO4)2': ['#f6f6f2', 'mayda-kristall'],
  AlPO4: ['#f4f6f6', 'iviqsimon'], CrPO4: ['#7a8f9a', 'iviqsimon'], 'Fe3(PO4)2': ['#d8e0d0', 'iviqsimon'], FePO4: ['#f0e6c0', 'iviqsimon'],
  'Zn3(PO4)2': ['#f6f6f2', 'mayda-kristall'], 'Mn3(PO4)2': ['#f2e0e0', 'mayda-kristall'], 'Ni3(PO4)2': ['#9ad09a', 'mayda-kristall'],
  'Co3(PO4)2': ['#c87ab8', 'mayda-kristall'], 'Cu3(PO4)2': ['#6fb3e0', 'iviqsimon'], Ag3PO4: ['#f2d23a', 'mayda-kristall'],
  'Pb3(PO4)2': ['#f6f6f2', 'mayda-kristall'], 'Sn3(PO4)2': ['#f6f6f2', 'mayda-kristall'], Li3PO4: ['#f6f6f2', 'mayda-kristall'],
  CaHPO4: ['#f6f6f2', 'mayda-kristall'], BaHPO4: ['#f6f6f2', 'mayda-kristall'], SrHPO4: ['#f6f6f2', 'mayda-kristall'], MgHPO4: ['#f6f6f2', 'mayda-kristall'],
  // silikatlar
  BaSiO3: ['#f6f6f2', 'iviqsimon'], CaSiO3: ['#f6f6f2', 'iviqsimon'], SrSiO3: ['#f6f6f2', 'iviqsimon'], MgSiO3: ['#f6f6f2', 'iviqsimon'],
  ZnSiO3: ['#f6f6f2', 'iviqsimon'], MnSiO3: ['#f0dcd8', 'iviqsimon'], FeSiO3: ['#c8d0b8', 'iviqsimon'], NiSiO3: ['#8cc88c', 'iviqsimon'],
  CoSiO3: ['#5a6ad0', 'iviqsimon'], CuSiO3: ['#5aaad8', 'iviqsimon'], PbSiO3: ['#f6f6f2', 'iviqsimon'],
  // oksalatlar va atsetatlar
  CaC2O4: ['#f6f6f2', 'mayda-kristall'], BaC2O4: ['#f6f6f2', 'mayda-kristall'], SrC2O4: ['#f6f6f2', 'mayda-kristall'], MgC2O4: ['#f6f6f2', 'mayda-kristall'],
  FeC2O4: ['#f2d23a', 'mayda-kristall'], ZnC2O4: ['#f6f6f2', 'mayda-kristall'], MnC2O4: ['#f4e4e4', 'mayda-kristall'], NiC2O4: ['#b8e0b0', 'mayda-kristall'],
  CoC2O4: ['#f0b8c8', 'mayda-kristall'], CuC2O4: ['#8ec8e8', 'mayda-kristall'], Ag2C2O4: ['#f6f6f2', 'mayda-kristall'], PbC2O4: ['#f6f6f2', 'mayda-kristall'],
  CH3COOAg: ['#f6f6f2', 'kristall'],
  // ftoridlar
  LiF: ['#f6f6f2', 'kukunsimon'], AlF3: ['#f6f6f2', 'kukunsimon'], CrF3: ['#7aa07a', 'kukunsimon'], FeF2: ['#e8ecd8', 'kukunsimon'], FeF3: ['#f0ece0', 'kukunsimon'],
  ZnF2: ['#f6f6f2', 'kukunsimon'], MnF2: ['#f2e0e0', 'kukunsimon'], NiF2: ['#b8e0b0', 'kukunsimon'], CoF2: ['#f0b8c8', 'kukunsimon'], CuF2: ['#d8ecf4', 'kukunsimon'], PbF2: ['#f6f6f2', 'kukunsimon'],
};

// Eriydigan tuzlarning qattiq holatdagi rangi (kristallogidratlar odatdagi ko'rinishi bilan)
export const SALT_SOLID_COLOR = {
  'Fe^2+': '#b4d8a8', 'Fe^3+': '#a8641e', 'Cu^2+': '#3a8fd6', 'Ni^2+': '#4caf50', 'Co^2+': '#c8507a', 'Mn^2+': '#f3c6cf', 'Cr^3+': '#3d6b4f',
};
export const SALT_SOLID_OVERRIDE = {
  CuSO4: ['#f2f2ee', 'oq kukun (suvsiz); suv yutib ko\'karadi'], CuCl2: ['#3aa88a', 'ko\'kimtir-yashil kristallar'], FeCl3: ['#7a3a12', 'to\'q qo\'ng\'ir kristallar'],
  CoCl2: ['#2f4fc0', "ko'k kukun (suvsiz); namlikda pushtilanadi"], FeSO4: ['#eeeee4', "oq-kulrang kukun (suvsiz)"], 'Fe2(SO4)3': ['#e8d8a8', 'och sarg\'ish kukun'], 'Cr2(SO4)3': ['#5a4a8a', 'binafsha kristallar'],
  CrCl3: ['#3d6b4f', 'to\'q yashil kristallar'], 'Fe(NO3)3': ['#d8c8e0', 'och binafsha kristallar'], 'Co(NO3)2': ['#c02a3a', 'qizil kristallar'],
};

// Jadvaldan tashqari noorganik moddalar
export const SPECIAL_INORGANIC = [
  { f: 'KMnO4', n: 'kaliy permanganat', col: '#3a0a3a', form: 'kristall', d: 2.7, hz: ['oksidlovchi', 'zararli', 'atrof-muhit'], sto: 'qoramtir-sklyanka', redox: 'oksidlovchi', diss: { 'K^+': 1, 'MnO4^-': 1 }, s: 64, sol: [[0.002, 'suyultirilgan', '0,002 M'], [0.02, 'suyultirilgan', '0,02 M'], [0.05, 'suyultirilgan', '0,05 M']], desc: 'to\'q binafsha, deyarli qora yaltiroq kristallar' },
  { f: 'K2MnO4', n: 'kaliy manganat', col: '#1a3a1a', form: 'kristall', hz: ['oksidlovchi'], diss: { 'K^+': 2, 'MnO4^2-': 1 }, redox: 'oksidlovchi', reagent: false },
  { f: 'K2Cr2O7', n: 'kaliy dixromat', col: '#e8661a', form: 'kristall', d: 2.68, hz: ['zaharli', 'oksidlovchi', 'kanserogen', 'atrof-muhit'], sto: 'tiqinli-sklyanka', redox: 'oksidlovchi', diss: { 'K^+': 2, 'Cr2O7^2-': 1 }, s: 123, sol: [[0.05, 'suyultirilgan', '0,05 M'], [0.1, 'suyultirilgan', '0,1 M']], desc: 'to\'q sariq-qizil (zarg\'aldoq) kristallar' },
  { f: 'K2CrO4', n: 'kaliy xromat', col: '#f2d020', form: 'kristall', d: 2.73, hz: ['zaharli', 'oksidlovchi', 'kanserogen'], sto: 'tiqinli-sklyanka', redox: 'oksidlovchi', diss: { 'K^+': 2, 'CrO4^2-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'Na2CrO4', n: 'natriy xromat', col: '#f2d020', form: 'kristall', hz: ['zaharli', 'kanserogen'], diss: { 'Na^+': 2, 'CrO4^2-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'Na2Cr2O7', n: 'natriy dixromat', col: '#e8661a', form: 'kristall', hz: ['zaharli', 'oksidlovchi', 'kanserogen'], diss: { 'Na^+': 2, 'Cr2O7^2-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: '(NH4)2Cr2O7', n: 'ammoniy dixromat', col: '#e8661a', form: 'kristall', d: 2.15, hz: ['zaharli', 'oksidlovchi', 'kanserogen'], sto: 'tiqinli-sklyanka', redox: 'ikkalasi', diss: { 'NH4^+': 2, 'Cr2O7^2-': 1 }, desc: 'zarg\'aldoq-qizil kristallar' },
  { f: 'KClO3', n: 'kaliy xlorat (Bertolle tuzi)', col: '#f8f8f6', form: 'kristall', d: 2.32, mp: 356, hz: ['oksidlovchi', 'zararli'], sto: 'tiqinli-sklyanka', redox: 'oksidlovchi', diss: { 'K^+': 1, 'ClO3^-': 1 }, s: 73 },
  { f: 'NaClO', n: 'natriy gipoxlorit', st: 'aq', hz: ['korroziv', 'oksidlovchi'], sto: 'qoramtir-sklyanka', redox: 'oksidlovchi', diss: { 'Na^+': 1, 'ClO^-': 1 }, sol: [[0.7, 'suyultirilgan', '5%']] },
  { f: 'Na2S2O3', n: 'natriy tiosulfat', col: '#f6f6f2', form: 'kristall', hz: [], sto: 'tiqinli-sklyanka', redox: 'qaytaruvchi', diss: { 'Na^+': 2, 'S2O3^2-': 1 }, sol: [[0.05, 'suyultirilgan', '0,05 M'], [0.1, 'suyultirilgan', '0,1 M'], [0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'KSCN', n: 'kaliy tiotsianat (rodanid)', col: '#f6f6f2', form: 'kristall', hz: ['zararli'], sto: 'tiqinli-sklyanka', diss: { 'K^+': 1, 'SCN^-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'NH4SCN', n: 'ammoniy tiotsianat (rodanid)', col: '#f6f6f2', form: 'kristall', hz: ['zararli'], sto: 'tiqinli-sklyanka', diss: { 'NH4^+': 1, 'SCN^-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'K4[Fe(CN)6]', n: 'kaliy geksatsianoferrat(II) (sariq qon tuzi)', col: '#f2d84a', form: 'kristall', hz: [], sto: 'tiqinli-sklyanka', diss: { 'K^+': 4, '[Fe(CN)6]^4-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'K3[Fe(CN)6]', n: 'kaliy geksatsianoferrat(III) (qizil qon tuzi)', col: '#c8321e', form: 'kristall', hz: [], sto: 'qoramtir-sklyanka', diss: { 'K^+': 3, '[Fe(CN)6]^3-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'CaC2', n: 'kalsiy karbid', col: '#4a4a4e', form: 'bo\'lak', d: 2.22, hz: ['yonuvchan'], sto: 'germetik-idish', desc: 'kulrang bo\'laklar, suv bilan atsetilen beradi' },
  { f: 'Al4C3', n: 'alyuminiy karbid', col: '#e8d8a0', form: 'kukun', d: 2.36, hz: ['yonuvchan'], sto: 'germetik-idish', desc: 'sariq kukun, suv bilan metan beradi' },
  { f: '(CuOH)2CO3', aliases: ['Cu2(OH)2CO3'], n: 'mis(II) gidroksokarbonat (malaxit)', col: '#3fa36b', form: 'kukun', d: 4.0, hz: ['zararli', 'atrof-muhit'], sto: 'tiqinli-sklyanka', tex: 'iviqsimon', acid: 'kuchsiz', desc: 'yashil kukun' },
  { f: 'KAl(SO4)2·12H2O', n: 'achchiqtosh (kaliy-alyuminiyli achchiqtosh)', col: '#f6f6f2', form: 'kristall', d: 1.76, hz: [], sto: 'tiqinli-sklyanka', diss: { 'K^+': 1, 'Al^3+': 1, 'SO4^2-': 2, H2O: 12 }, s: 114, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'CuSO4·5H2O', n: 'mis kuporosi (mis(II) sulfat pentagidrat)', col: '#2f7fd8', form: 'kristall', d: 2.28, hz: ['zararli', 'atrof-muhit'], sto: 'tiqinli-sklyanka', diss: { 'Cu^2+': 1, 'SO4^2-': 1, H2O: 5 }, dehyd: 'CuSO4' },
  { f: 'FeSO4·7H2O', n: 'temir kuporosi (temir(II) sulfat geptagidrat)', col: '#9fd4b0', form: 'kristall', d: 1.9, hz: ['zararli'], sto: 'tiqinli-sklyanka', diss: { 'Fe^2+': 1, 'SO4^2-': 1, H2O: 7 }, dehyd: 'FeSO4' },
  { f: 'CoCl2·6H2O', n: 'kobalt(II) xlorid geksagidrat', col: '#c8466e', form: 'kristall', d: 1.92, hz: ['zaharli', 'kanserogen'], sto: 'tiqinli-sklyanka', diss: { 'Co^2+': 1, 'Cl^-': 2, H2O: 6 }, dehyd: 'CoCl2', desc: 'pushti-qizil kristallar; suvsizlanganda ko\'karadi' },
  { f: 'Na2CO3·10H2O', n: 'kristall soda (natriy karbonat dekagidrat)', col: '#f8f8f6', form: 'kristall', d: 1.46, hz: ['zararli'], sto: 'tiqinli-sklyanka', diss: { 'Na^+': 2, 'CO3^2-': 1, H2O: 10 }, dehyd: 'Na2CO3' },
  { f: '(NH4)2Fe(SO4)2·6H2O', n: 'Mor tuzi', col: '#b8dcc0', form: 'kristall', d: 1.86, hz: [], sto: 'tiqinli-sklyanka', diss: { 'NH4^+': 2, 'Fe^2+': 1, 'SO4^2-': 2, H2O: 6 }, sol: [[0.05, 'suyultirilgan', '0,05 M']] },
  { f: 'Na2B4O7·10H2O', n: 'bura (natriy tetraborat dekagidrat)', col: '#f8f8f6', form: 'kristall', d: 1.73, hz: ['zararli'], sto: 'tiqinli-sklyanka', sol: [[0.05, 'suyultirilgan', '0,05 M']], weak_base: true, desc: 'titrlashda boshlang\'ich modda' },
  { f: 'NaHSO4', n: 'natriy gidrosulfat', col: '#f6f6f2', form: 'kristall', hz: ['korroziv'], diss: { 'Na^+': 1, 'HSO4^-': 1 }, sol: [[0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'KHSO4', n: 'kaliy gidrosulfat', col: '#f6f6f2', form: 'kristall', hz: ['korroziv'], diss: { 'K^+': 1, 'HSO4^-': 1 }, reagent: false },
  { f: 'NaH2PO4', n: 'natriy digidrofosfat', col: '#f6f6f2', form: 'kristall', hz: [], diss: { 'Na^+': 1, 'H2PO4^-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'KH2PO4', n: 'kaliy digidrofosfat', col: '#f6f6f2', form: 'kristall', hz: [], diss: { 'K^+': 1, 'H2PO4^-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'NH4H2PO4', n: 'ammoniy digidrofosfat (ammofos)', col: '#f6f6f2', form: 'kristall', hz: [], diss: { 'NH4^+': 1, 'H2PO4^-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'Ca(H2PO4)2', n: 'kalsiy digidrofosfat (qo\'shsuperfosfat)', col: '#f2f0e8', form: 'kukun', hz: [], diss: { 'Ca^2+': 1, 'H2PO4^-': 2 }, reagent: false },
  { f: 'NaHSO3', n: 'natriy gidrosulfit', col: '#f6f6f2', form: 'kristall', hz: ['zararli'], diss: { 'Na^+': 1, 'HSO3^-': 1 }, redox: 'qaytaruvchi', sol: [[0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'NaHS', n: 'natriy gidrosulfid', col: '#f6f6ea', form: 'kristall', hz: ['korroziv', 'zaharli'], diss: { 'Na^+': 1, 'HS^-': 1 }, reagent: false },
  { f: 'Na[Al(OH)4]', n: 'natriy tetragidroksoalyuminat', st: 'aq', hz: ['korroziv'], diss: { 'Na^+': 1, '[Al(OH)4]^-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']] },
  { f: 'K[Al(OH)4]', n: 'kaliy tetragidroksoalyuminat', st: 'aq', hz: ['korroziv'], diss: { 'K^+': 1, '[Al(OH)4]^-': 1 }, reagent: false },
  { f: 'Na2[Zn(OH)4]', n: 'natriy tetragidroksosinkat', st: 'aq', hz: ['korroziv'], diss: { 'Na^+': 2, '[Zn(OH)4]^2-': 1 }, reagent: false },
  { f: 'K2[Zn(OH)4]', n: 'kaliy tetragidroksosinkat', st: 'aq', hz: ['korroziv'], diss: { 'K^+': 2, '[Zn(OH)4]^2-': 1 }, reagent: false },
  { f: 'Na3[Cr(OH)6]', n: 'natriy geksagidroksoxromat(III)', st: 'aq', hz: ['korroziv'], diss: { 'Na^+': 3, '[Cr(OH)6]^3-': 1 }, reagent: false },
  { f: 'K3[Cr(OH)6]', n: 'kaliy geksagidroksoxromat(III)', st: 'aq', hz: ['korroziv'], diss: { 'K^+': 3, '[Cr(OH)6]^3-': 1 }, reagent: false },
  { f: 'Na2[Pb(OH)4]', n: 'natriy tetragidroksoplyumbat(II)', st: 'aq', hz: ['zaharli'], diss: { 'Na^+': 2, '[Pb(OH)4]^2-': 1 }, reagent: false },
  { f: 'Na2[Sn(OH)4]', n: 'natriy tetragidroksostannat(II)', st: 'aq', hz: ['korroziv'], diss: { 'Na^+': 2, '[Sn(OH)4]^2-': 1 }, reagent: false },
  { f: 'NaAlO2', n: 'natriy metaalyuminat', col: '#f6f6f2', form: 'kukun', hz: ['korroziv'], reagent: false, desc: 'qotishmada hosil bo\'ladi' },
  { f: '[Cu(NH3)4]SO4', n: 'tetraamminmis(II) sulfat', st: 'aq', hz: ['zararli'], diss: { '[Cu(NH3)4]^2+': 1, 'SO4^2-': 1 }, reagent: false },
  { f: '[Cu(NH3)4](OH)2', n: 'tetraamminmis(II) gidroksid', st: 'aq', hz: ['zararli'], diss: { '[Cu(NH3)4]^2+': 1, 'OH^-': 2 }, reagent: false },
  { f: '[Ag(NH3)2]OH', n: 'diamminkumush gidroksid', st: 'aq', hz: ['korroziv'], diss: { '[Ag(NH3)2]^+': 1, 'OH^-': 1 }, reagent: false },
  { f: '[Ag(NH3)2]Cl', n: 'diamminkumush xlorid', st: 'aq', hz: [], diss: { '[Ag(NH3)2]^+': 1, 'Cl^-': 1 }, reagent: false },
  { f: '[Zn(NH3)4](OH)2', n: 'tetraamminrux gidroksid', st: 'aq', hz: [], diss: { '[Zn(NH3)4]^2+': 1, 'OH^-': 2 }, reagent: false },
  { f: '[Zn(NH3)4]SO4', n: 'tetraamminrux sulfat', st: 'aq', hz: [], diss: { '[Zn(NH3)4]^2+': 1, 'SO4^2-': 1 }, reagent: false },
  { f: '[Ni(NH3)6](OH)2', n: 'geksaamminnikel(II) gidroksid', st: 'aq', hz: [], diss: { '[Ni(NH3)6]^2+': 1, 'OH^-': 2 }, reagent: false },
  { f: '[Ni(NH3)6]SO4', n: 'geksaamminnikel(II) sulfat', st: 'aq', hz: [], diss: { '[Ni(NH3)6]^2+': 1, 'SO4^2-': 1 }, reagent: false },
  { f: '[Ni(NH3)6]Cl2', n: 'geksaamminnikel(II) xlorid', st: 'aq', hz: [], diss: { '[Ni(NH3)6]^2+': 1, 'Cl^-': 2 }, reagent: false },
  { f: '[Cu(NH3)4]Cl2', n: 'tetraamminmis(II) xlorid', st: 'aq', hz: [], diss: { '[Cu(NH3)4]^2+': 1, 'Cl^-': 2 }, reagent: false },
  { f: '[Zn(NH3)4]Cl2', n: 'tetraamminrux xlorid', st: 'aq', hz: [], diss: { '[Zn(NH3)4]^2+': 1, 'Cl^-': 2 }, reagent: false },
  { f: 'Fe4[Fe(CN)6]3', n: 'Berlin lazuri (temir(III) geksatsianoferrat(II))', col: '#123a8a', form: 'kukun', hz: [], tex: 'kolloid', reagent: false, desc: 'to\'q ko\'k cho\'kma' },
  { f: 'Fe3[Fe(CN)6]2', n: 'Turnbul ko\'ki (temir(II) geksatsianoferrat(III))', col: '#163a8a', form: 'kukun', hz: [], tex: 'kolloid', reagent: false, desc: 'to\'q ko\'k cho\'kma' },
  { f: 'KFe[Fe(CN)6]', n: 'eruvchan Berlin lazuri', col: '#1a4aa0', form: 'kukun', hz: [], tex: 'kolloid', reagent: false },
  { f: 'Cu2[Fe(CN)6]', n: 'mis(II) geksatsianoferrat(II)', col: '#7a2a14', form: 'kukun', hz: [], tex: 'iviqsimon', reagent: false, desc: 'qizil-qo\'ng\'ir cho\'kma' },
  { f: 'Zn2[Fe(CN)6]', n: 'rux geksatsianoferrat(II)', col: '#f4f4ee', form: 'kukun', hz: [], tex: 'iviqsimon', reagent: false },
  { f: 'K2Zn3[Fe(CN)6]2', n: 'kaliy-rux geksatsianoferrat(II)', col: '#f4f4ee', form: 'kukun', hz: [], tex: 'iviqsimon', reagent: false },
  { f: 'Fe(SCN)3', n: 'temir(III) tiotsianat', st: 'aq', hz: [], reagent: false, aq: { col: '#b3101a', ref: 0.002 }, desc: 'qon-qizil rangli eritma' },
  { f: 'Ni(C4H7N2O2)2', n: 'nikel dimetilglioksimat', col: '#d81e4a', form: 'kukun', hz: [], tex: 'suzmasimon', reagent: false, desc: 'qizil-pushti (malina rang) cho\'kma' },
  { f: 'K2[HgI4]', n: 'kaliy tetrayodomerkurat(II)', col: '#f2e060', form: 'kristall', hz: ['zaharli', 'atrof-muhit'], diss: { 'K^+': 2, '[HgI4]^2-': 1 }, reagent: false },
  { f: '[OHg2NH2]I', n: 'oksodimerkurammoniy yodid (Nessler cho\'kmasi)', col: '#8a4a1a', form: 'kukun', hz: ['zaharli'], tex: 'iviqsimon', reagent: false, desc: 'qizil-qo\'ng\'ir cho\'kma' },
  { f: 'HgI2', n: 'simob(II) yodid', col: '#e0301e', form: 'kukun', hz: ['zaharli'], tex: 'mayda-kristall', reagent: false },
  { f: 'CuI', n: 'mis(I) yodid', col: '#f2eee0', form: 'kukun', hz: ['zararli'], tex: 'kukunsimon', reagent: false },
  { f: 'CuCl', n: 'mis(I) xlorid', col: '#f2f2ee', form: 'kukun', hz: ['zararli'], tex: 'kukunsimon', reagent: false },
  { f: 'BaCrO4', n: 'bariy xromat', col: '#f5d31a', form: 'kukun', hz: ['zaharli', 'kanserogen'], tex: 'mayda-kristall', acid: 'kuchli', reagent: false },
  { f: 'PbCrO4', n: 'qo\'rg\'oshin xromat (xrom sariq)', col: '#f7c400', form: 'kukun', hz: ['zaharli', 'kanserogen'], tex: 'mayda-kristall', acid: 'kuchli', reagent: false },
  { f: 'Ag2CrO4', n: 'kumush xromat', col: '#a8321e', form: 'kukun', hz: ['zaharli'], tex: 'mayda-kristall', acid: 'kuchli', reagent: false },
  { f: 'SrCrO4', n: 'stronsiy xromat', col: '#f2d830', form: 'kukun', hz: ['zaharli'], tex: 'mayda-kristall', acid: 'kuchli', reagent: false },
  { f: 'AgSCN', n: 'kumush tiotsianat', col: '#f6f6f2', form: 'kukun', hz: [], tex: 'suzmasimon', reagent: false },
  { f: 'Ag2S2O3', n: 'kumush tiosulfat', col: '#f6f6f2', form: 'kukun', hz: [], tex: 'kukunsimon', reagent: false },
  { f: 'Na3[Ag(S2O3)2]', n: 'natriy ditiosulfatoargentat(I)', st: 'aq', hz: [], diss: { 'Na^+': 3, '[Ag(S2O3)2]^3-': 1 }, reagent: false },
  { f: 'Na2S4O6', n: 'natriy tetrationat', st: 'aq', hz: [], diss: { 'Na^+': 2, 'S4O6^2-': 1 }, reagent: false },
  { f: 'CaOCl2', n: 'xlorli ohak', col: '#f2f2ea', form: 'kukun', hz: ['korroziv', 'oksidlovchi'], sto: 'germetik-idish', redox: 'oksidlovchi', desc: 'xlor hidli oq kukun' },
  { f: 'Ca(ClO)2', n: 'kalsiy gipoxlorit', col: '#f2f2ea', form: 'kukun', hz: ['korroziv', 'oksidlovchi'], reagent: false },
  { f: 'KClO4', n: 'kaliy perxlorat', col: '#f6f6f2', form: 'kristall', hz: ['oksidlovchi'], reagent: false },
  { f: 'KNO3', n: 'kaliy nitrat (kaliyli selitra)', col: '#f6f6f2', form: 'kristall', d: 2.11, mp: 334, hz: ['oksidlovchi'], sto: 'tiqinli-sklyanka', diss: { 'K^+': 1, 'NO3^-': 1 }, s: 316, sol: [[0.1, 'suyultirilgan', '0,1 M'], [1, 'suyultirilgan', '1 M']], redox: 'oksidlovchi', custom: true },
  { f: 'MnSO4', n: 'marganes(II) sulfat', col: '#f3c6cf', form: 'kristall', hz: ['zararli'], diss: { 'Mn^2+': 1, 'SO4^2-': 1 }, sol: [[0.1, 'suyultirilgan', '0,1 M']], custom: true },
  { f: 'Cr2(SO4)3', n: 'xrom(III) sulfat', col: '#5a4a8a', form: 'kristall', hz: ['zararli'], diss: { 'Cr^3+': 2, 'SO4^2-': 3 }, sol: [[0.05, 'suyultirilgan', '0,05 M']], custom: true },
  { f: 'S4O6^2-', ion_only: true },
  { f: 'MnO(OH)2', n: 'marganes(IV) gidroksid (oksid-gidrat)', col: '#3a2418', form: 'kukun', hz: [], tex: 'iviqsimon', reagent: false },
  { f: 'MnO(OH)', aliases: [], n: 'marganes(III) oksid-gidroksid', col: '#4a2c1a', form: 'kukun', hz: [], tex: 'iviqsimon', reagent: false },
  { f: 'Na2[CaC10H12N2O8]', n: 'natriy kalsiy-etilendiamintetraatsetat (CaY²⁻ kompleksi)', st: 'aq', diss: { 'Na^+': 2, '[CaC10H12N2O8]^2-': 1 }, hz: [], reagent: false },
  { f: 'Na2[MgC10H12N2O8]', n: 'natriy magniy-etilendiamintetraatsetat (MgY²⁻ kompleksi)', st: 'aq', diss: { 'Na^+': 2, '[MgC10H12N2O8]^2-': 1 }, hz: [], reagent: false },
  { f: 'AlOHCl2', n: 'alyuminiy gidroksoxlorid', st: 'aq', diss: { 'AlOH^2+': 1, 'Cl^-': 2 }, hz: [], reagent: false },
  { f: 'AlOHSO4', n: 'alyuminiy gidroksosulfat', st: 'aq', diss: { 'AlOH^2+': 1, 'SO4^2-': 1 }, hz: [], reagent: false },
  { f: 'FeOHCl2', n: 'temir(III) gidroksoxlorid', st: 'aq', diss: { 'FeOH^2+': 1, 'Cl^-': 2 }, hz: [], reagent: false },
  { f: '(CuOH)2SO4', n: 'mis(II) gidroksosulfat', st: 'aq', diss: { 'CuOH^+': 2, 'SO4^2-': 1 }, hz: [], reagent: false },
  { f: '(ZnOH)2SO4', n: 'rux gidroksosulfat', st: 'aq', diss: { 'ZnOH^+': 2, 'SO4^2-': 1 }, hz: [], reagent: false },
  { f: 'NaH', n: 'natriy gidrid', col: '#e8e8e0', form: 'kukun', hz: ['yonuvchan'], reagent: false },
  { f: 'CaH2', n: 'kalsiy gidrid', col: '#e8e8e0', form: 'kukun', hz: ['yonuvchan'], reagent: false },
  { f: 'Mg3N2', n: 'magniy nitrid', col: '#e8e0b0', form: 'kukun', hz: [], reagent: false },
  { f: 'Li3N', n: 'litiy nitrid', col: '#8a4a3a', form: 'kukun', hz: ['korroziv'], reagent: false },
  { f: 'Na2O2', n: 'natriy peroksid', col: '#f2e6b0', form: 'kukun', hz: ['oksidlovchi', 'korroziv'], sto: 'germetik-idish', redox: 'oksidlovchi' },
  { f: 'KO2', n: 'kaliy superoksid', col: '#f2c84a', form: 'kukun', hz: ['oksidlovchi', 'korroziv'], reagent: false },
  { f: 'BaO2', n: 'bariy peroksid', col: '#f2f2ea', form: 'kukun', hz: ['oksidlovchi', 'zaharli'], reagent: false },
  { f: 'Mg2Si', n: 'magniy silitsid', col: '#5a6a7a', form: 'kukun', hz: ['yonuvchan'], reagent: false },
  { f: 'SiH4', n: 'silan', st: 'g', hz: ['yonuvchan'], gas: { ws: 'kam' }, reagent: false },
  { f: 'PH3', n: 'fosfin', st: 'g', hz: ['zaharli', 'yonuvchan'], gas: { ws: 'kam', toxic: true }, reagent: false },
  { f: 'PCl5', n: 'fosfor(V) xlorid', col: '#f2f0d8', form: 'kristall', hz: ['korroziv'], reagent: false },
  { f: 'PCl3', n: 'fosfor(III) xlorid', st: 'l', hz: ['korroziv', 'zaharli'], reagent: false },
  { f: 'AlCl3', n: 'alyuminiy xlorid', custom_skip: true },
  { f: 'FeCl3', n: 'temir(III) xlorid', custom_skip: true },
  { f: 'HgCl2', n: 'simob(II) xlorid', col: '#f6f6f2', form: 'kristall', hz: ['zaharli', 'atrof-muhit'], diss: { 'Hg^2+': 1, 'Cl^-': 2 }, reagent: false },
  { f: 'Hg(NO3)2', n: 'simob(II) nitrat', col: '#f6f6f2', form: 'kristall', hz: ['zaharli', 'atrof-muhit'], diss: { 'Hg^2+': 1, 'NO3^-': 2 }, reagent: false },
  { f: 'HgS', n: 'simob(II) sulfid', col: '#151515', form: 'kukun', hz: ['zaharli'], tex: 'kukunsimon', reagent: false },
  { f: 'NH4NO2', n: 'ammoniy nitrit', custom_skip: true },
  { f: 'NaCN', skip: true },
  { f: 'N2O', n: 'azot(I) oksid', st: 'g', hz: ['oksidlovchi'], gas: { ws: 'o\'rtacha' }, reagent: false },
  { f: 'N2O5', n: 'azot(V) oksid', col: '#f6f6f2', form: 'kristall', hz: ['oksidlovchi', 'korroziv'], reagent: false },
  { f: 'Cl2O7', skip: true },
  { f: 'Fe(OH)3', custom_skip: true },
  { f: 'FeO(OH)', n: 'temir(III) metagidroksid', col: '#a85a20', form: 'kukun', hz: [], tex: 'iviqsimon', reagent: false },
  { f: 'Na2SiO3', custom_skip: true },
  { f: 'CaCl2', custom_skip: true },
  { f: 'H2SnO2', skip: true },
  { f: 'O3', n: 'ozon', st: 'g', hz: ['oksidlovchi', 'zaharli'], gas: { ws: 'kam', smell: 'yangilik (momaqaldiroq) hidi', toxic: true }, reagent: false },
  { f: 'Ca3P2', skip: true },
  { f: 'Zn3P2', skip: true },
  { f: 'S8', skip: true },
];

// Organik moddalar
export const ORGANIC = [
  // alkanlar
  { f: 'CH4', n: 'metan', st: 'g', c: 'alkan', hz: ['yonuvchan', 'bosim'], gas: { ws: 'kam' } },
  { f: 'C2H6', aliases: ['CH3–CH3'], n: 'etan', st: 'g', c: 'alkan', hz: ['yonuvchan', 'bosim'], gas: { ws: 'kam' } },
  { f: 'C3H8', aliases: ['CH3–CH2–CH3'], n: 'propan', st: 'g', c: 'alkan', hz: ['yonuvchan', 'bosim'], gas: { ws: 'kam' } },
  { f: 'C4H10', n: 'butan', st: 'g', c: 'alkan', hz: ['yonuvchan', 'bosim'], gas: { ws: 'kam' } },
  { f: 'C6H14', n: 'geksan', st: 'l', c: 'alkan', d: 0.655, bp: 68.7, hz: ['yonuvchan', 'zararli', 'atrof-muhit'], miscible: false, sto: 'tiqinli-sklyanka' },
  { f: 'C5H12', n: 'pentan', st: 'l', c: 'alkan', d: 0.626, bp: 36.1, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: 'C8H18', n: 'oktan', st: 'l', c: 'alkan', d: 0.703, bp: 125.7, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: 'C10H22', n: 'dekan', st: 'l', c: 'alkan', d: 0.73, bp: 174, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: 'C16H34', n: 'geksadekan', st: 'l', c: 'alkan', d: 0.77, bp: 287, hz: [], miscible: false, reagent: false },
  { f: 'C6H12', n: 'siklogeksan', st: 'l', c: 'sikloalkan', d: 0.779, bp: 80.7, hz: ['yonuvchan'], miscible: false, reagent: false },
  // galogenalkanlar
  { f: 'CH3Cl', n: 'xlormetan', st: 'g', c: 'galogenalkan', hz: ['yonuvchan', 'zararli'], gas: { ws: 'kam' }, reagent: false },
  { f: 'CH2Cl2', n: 'dixlormetan', st: 'l', c: 'galogenalkan', d: 1.33, bp: 39.6, hz: ['zararli'], miscible: false, reagent: false },
  { f: 'CHCl3', n: 'xloroform (trixlormetan)', st: 'l', c: 'galogenalkan', d: 1.49, bp: 61.2, hz: ['zararli', 'kanserogen'], miscible: false, sto: 'qoramtir-sklyanka' },
  { f: 'CCl4', n: 'tetraxlormetan', st: 'l', c: 'galogenalkan', d: 1.59, bp: 76.7, hz: ['zaharli', 'atrof-muhit'], miscible: false, reagent: false },
  { f: 'C2H5Cl', aliases: ['CH3CH2Cl', 'CH3–CH2Cl', 'CH3–CH2–Cl'], n: 'xloretan', st: 'g', c: 'galogenalkan', bp: 12.3, hz: ['yonuvchan'], gas: { ws: 'kam' }, sto: 'ampula' },
  { f: 'C2H5Br', aliases: ['CH3CH2Br', 'CH3–CH2Br', 'CH3–CH2–Br'], n: 'brometan', st: 'l', c: 'galogenalkan', d: 1.46, bp: 38.4, hz: ['zararli', 'yonuvchan'], miscible: false, sto: 'qoramtir-sklyanka' },
  { f: 'C2H5I', n: 'yodetan', st: 'l', c: 'galogenalkan', d: 1.95, bp: 72.3, hz: ['zararli'], miscible: false, reagent: false },
  { f: 'CH3Br', n: 'brommetan', st: 'g', c: 'galogenalkan', hz: ['zaharli'], gas: { ws: 'kam' }, reagent: false },
  { f: 'CH3CHBrCH3', aliases: ['CH3–CHBr–CH3'], n: '2-brompropan', st: 'l', c: 'galogenalkan', d: 1.31, bp: 59.4, hz: ['yonuvchan', 'zararli'], miscible: false },
  { f: 'CH3CH2CH2Br', aliases: ['CH3–CH2–CH2Br', 'CH3–CH2–CH2–Br'], n: '1-brompropan', st: 'l', c: 'galogenalkan', d: 1.35, bp: 71, hz: ['yonuvchan', 'zararli'], miscible: false, reagent: false },
  { f: '(CH3)3CCl', n: 'tret-butilxlorid (2-xlor-2-metilpropan)', st: 'l', c: 'galogenalkan', d: 0.84, bp: 51, hz: ['yonuvchan'], miscible: false },
  { f: '(CH3)3CBr', n: 'tret-butilbromid', st: 'l', c: 'galogenalkan', d: 1.22, bp: 73, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: 'CH2BrCH2Br', aliases: ['CH2Br–CH2Br'], n: '1,2-dibrometan', st: 'l', c: 'galogenalkan', d: 2.18, bp: 131, hz: ['zaharli'], miscible: false, reagent: false },
  { f: 'CH2BrCHBrCH3', aliases: ['CH2Br–CHBr–CH3'], n: '1,2-dibrompropan', st: 'l', c: 'galogenalkan', d: 1.93, bp: 141, hz: ['zararli'], miscible: false, reagent: false },
  { f: 'CHBr2CHBr2', aliases: ['CHBr2–CHBr2'], n: '1,1,2,2-tetrabrometan', st: 'l', c: 'galogenalkan', d: 2.97, bp: 244, hz: ['zaharli'], miscible: false, reagent: false },
  { f: 'CH2ClCH2Cl', aliases: ['CH2Cl–CH2Cl'], n: '1,2-dixloretan', st: 'l', c: 'galogenalkan', d: 1.25, bp: 83.5, hz: ['zaharli', 'yonuvchan'], miscible: false, reagent: false },
  { f: 'CH2=CHCl', n: 'vinilxlorid (xloreten)', st: 'g', c: 'galogenalken', hz: ['yonuvchan', 'kanserogen'], gas: { ws: 'kam' }, reagent: false },
  { f: 'CH2=CHBr', n: 'vinilbromid', st: 'g', c: 'galogenalken', hz: ['yonuvchan'], gas: { ws: 'kam' }, reagent: false },
  { f: 'CF2=CF2', n: 'tetraftoreten', st: 'g', c: 'galogenalken', hz: ['bosim'], gas: { ws: 'kam' }, reagent: false },
  // alkenlar, alkinlar, dienlar
  { f: 'CH2=CH2', aliases: ['C2H4'], n: 'etilen (eten)', st: 'g', c: 'alken', hz: ['yonuvchan', 'bosim'], gas: { ws: 'kam', smell: 'kuchsiz shirinroq hid' } },
  { f: 'CH2=CH–CH3', aliases: ['C3H6', 'CH2=CHCH3'], n: 'propen (propilen)', st: 'g', c: 'alken', hz: ['yonuvchan', 'bosim'], gas: { ws: 'kam' } },
  { f: 'CH2=CH–CH2–CH3', aliases: ['CH2=CHCH2CH3'], n: 'buten-1', st: 'g', c: 'alken', hz: ['yonuvchan'], gas: { ws: 'kam' }, reagent: false },
  { f: 'CH3–CH=CH–CH3', aliases: ['CH3CH=CHCH3'], n: 'buten-2', st: 'g', c: 'alken', hz: ['yonuvchan'], gas: { ws: 'kam' }, reagent: false },
  { f: '(CH3)2C=CH2', n: 'izobutilen (2-metilpropen)', st: 'g', c: 'alken', hz: ['yonuvchan'], gas: { ws: 'kam' }, reagent: false },
  { f: 'C6H10', n: 'siklogeksen', st: 'l', c: 'alken', d: 0.81, bp: 83, hz: ['yonuvchan'], miscible: false },
  { f: 'CH≡CH', aliases: ['C2H2'], n: 'atsetilen (etin)', st: 'g', c: 'alkin', hz: ['yonuvchan', 'bosim'], gas: { ws: 'kam', smell: 'karbiddan olinganda o\'ziga xos hid (aralashmalar)' } },
  { f: 'CH≡C–CH3', aliases: ['C3H4'], n: 'propin', st: 'g', c: 'alkin', hz: ['yonuvchan'], gas: { ws: 'kam' }, reagent: false },
  { f: 'CH2=CH–CH=CH2', aliases: ['C4H6'], n: 'butadien-1,3', st: 'g', c: 'dien', hz: ['yonuvchan', 'kanserogen'], gas: { ws: 'kam' }, reagent: false },
  { f: 'CH2=C(CH3)–CH=CH2', aliases: ['C5H8'], n: 'izopren (2-metilbutadien-1,3)', st: 'l', c: 'dien', d: 0.681, bp: 34, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: 'CHBr=CHBr', n: '1,2-dibrometen', st: 'l', c: 'galogenalken', d: 2.25, bp: 110, hz: ['zararli'], miscible: false, reagent: false },
  { f: 'CH≡C–Ag', skip: true },
  { f: 'AgC≡CAg', aliases: ['Ag2C2'], n: 'kumush atsetilenid', col: '#e8e0d0', form: 'kukun', st: 's', c: 'organik-tuz', hz: ['portlash-xavfi'], tex: 'kukunsimon', reagent: false, desc: 'och sarg\'ish-oq cho\'kma; quruq holda portlaydi' },
  { f: 'CuC≡CCu', aliases: ['Cu2C2'], n: 'mis(I) atsetilenid', col: '#8a2a1a', form: 'kukun', st: 's', c: 'organik-tuz', hz: ['portlash-xavfi'], tex: 'kukunsimon', reagent: false, desc: 'qizil-qo\'ng\'ir cho\'kma; quruq holda portlaydi' },
  // arenlar
  { f: 'C6H6', n: 'benzol', st: 'l', c: 'aren', d: 0.877, mp: 5.5, bp: 80.1, hz: ['yonuvchan', 'kanserogen', 'zaharli'], miscible: false, sto: 'tiqinli-sklyanka', desc: 'o\'ziga xos hidli rangsiz suyuqlik' },
  { f: 'C6H5CH3', aliases: ['C7H8', 'C6H5–CH3'], n: 'toluol (metilbenzol)', st: 'l', c: 'aren', d: 0.867, bp: 110.6, hz: ['yonuvchan', 'zararli'], miscible: false, sto: 'tiqinli-sklyanka' },
  { f: 'C6H5CH=CH2', aliases: ['C8H8', 'C6H5–CH=CH2'], n: 'stirol (vinilbenzol)', st: 'l', c: 'aren', d: 0.906, bp: 145, hz: ['yonuvchan', 'zararli'], miscible: false, sto: 'qoramtir-sklyanka' },
  { f: 'C6H5Br', n: 'brombenzol', st: 'l', c: 'aren', d: 1.50, bp: 156, hz: ['zararli', 'atrof-muhit'], miscible: false, reagent: false },
  { f: 'C6H5Cl', n: 'xlorbenzol', st: 'l', c: 'aren', d: 1.11, bp: 131.7, hz: ['zararli', 'yonuvchan'], miscible: false, reagent: false },
  { f: 'C6H5NO2', n: 'nitrobenzol', st: 'l', c: 'aren', d: 1.20, bp: 210.9, hz: ['zaharli'], miscible: false, reagent: false, desc: 'achchiq bodom hidli och sariq moysimon suyuqlik' },
  { f: 'C6H6Cl6', n: 'geksaxlorsiklogeksan', st: 's', c: 'galogenalkan', col: '#f6f6f2', form: 'kristall', hz: ['zaharli', 'atrof-muhit'], reagent: false },
  { f: 'C6H5CH2Cl', n: 'benzilxlorid', st: 'l', c: 'aren', d: 1.1, bp: 179, hz: ['zaharli'], miscible: false, reagent: false },
  { f: 'C6H4BrCH3', n: '2-bromtoluol (o- va p-bromtoluol aralashmasi)', st: 'l', c: 'aren', d: 1.42, hz: ['zararli'], miscible: false, reagent: false },
  { f: 'C6H5CHBrCH2Br', aliases: ['C6H5–CHBr–CH2Br'], n: '1,2-dibrom-1-feniletan', st: 's', c: 'aren', col: '#f6f6f2', form: 'kristall', hz: ['zararli'], reagent: false },
  { f: 'C6H12', tag: 'siklogeksan', skip: true },
  { f: 'C6H5SO3H', n: 'benzolsulfokislota', st: 's', c: 'aren', col: '#f6f6f2', form: 'kristall', hz: ['korroziv'], reagent: false },
  { f: 'C10H8', n: 'naftalin', st: 's', c: 'aren', col: '#f8f8f6', form: 'kristall', mp: 80.3, hz: ['zararli', 'atrof-muhit'], reagent: true, desc: 'o\'tkir hidli oq kristallar, oson sublimatlanadi' },
  // spirtlar, fenollar, efirlar
  { f: 'CH3OH', n: 'metanol (metil spirti)', st: 'l', c: 'spirt', d: 0.792, bp: 64.7, hz: ['zaharli', 'yonuvchan'], miscible: true, sto: 'tiqinli-sklyanka' },
  { f: 'C2H5OH', aliases: ['CH3CH2OH', 'CH3–CH2–OH', 'CH3–CH2OH'], n: 'etanol (etil spirti)', st: 'l', c: 'spirt', d: 0.789, bp: 78.4, hz: ['yonuvchan'], miscible: true, sto: 'tiqinli-sklyanka' },
  { f: 'CH3CH2CH2OH', aliases: ['CH3–CH2–CH2–OH', 'C3H7OH'], n: 'propanol-1', st: 'l', c: 'spirt', d: 0.803, bp: 97.2, hz: ['yonuvchan', 'zararli'], miscible: true, sto: 'tiqinli-sklyanka' },
  { f: 'CH3CH(OH)CH3', aliases: ['CH3–CH(OH)–CH3', '(CH3)2CHOH'], n: 'propanol-2 (izopropil spirti)', st: 'l', c: 'spirt', d: 0.786, bp: 82.6, hz: ['yonuvchan', 'zararli'], miscible: true, sto: 'tiqinli-sklyanka' },
  { f: 'CH3(CH2)3OH', aliases: ['C4H9OH', 'CH3CH2CH2CH2OH'], n: 'butanol-1', st: 'l', c: 'spirt', d: 0.81, bp: 117.7, hz: ['yonuvchan', 'zararli'], miscible: false, sto: 'tiqinli-sklyanka' },
  { f: '(CH3)3COH', n: 'tret-butanol (2-metilpropanol-2)', st: 'l', c: 'spirt', d: 0.78, mp: 25.5, bp: 82.4, hz: ['yonuvchan', 'zararli'], miscible: true, sto: 'tiqinli-sklyanka' },
  { f: 'C5H11OH', n: 'izoamil spirti', st: 'l', c: 'spirt', d: 0.81, bp: 131, hz: ['yonuvchan', 'zararli'], miscible: false, sto: 'tiqinli-sklyanka' },
  { f: 'HOCH2CH2OH', aliases: ['C2H4(OH)2', 'HO–CH2–CH2–OH', 'CH2(OH)–CH2(OH)'], n: 'etilenglikol (etandiol-1,2)', st: 'l', c: 'spirt', d: 1.113, bp: 197.3, hz: ['zararli'], miscible: true, sto: 'tiqinli-sklyanka' },
  { f: 'C3H5(OH)3', aliases: ['CH2(OH)–CH(OH)–CH2(OH)', 'HOCH2CH(OH)CH2OH'], n: 'glitserin (propantriol-1,2,3)', st: 'l', c: 'spirt', d: 1.261, bp: 290, hz: [], miscible: true, sto: 'tiqinli-sklyanka', desc: 'shirin ta\'mli quyuq rangsiz suyuqlik' },
  { f: 'C6H5OH', n: 'fenol', st: 's', c: 'fenol', col: '#f6eeee', form: 'kristall', d: 1.07, mp: 40.5, bp: 181.7, hz: ['zaharli', 'korroziv'], sto: 'qoramtir-sklyanka', sol: [[0.5, 'suyultirilgan', '~5% (fenolli suv)']], desc: 'o\'ziga xos hidli, havoda pushtilanadigan kristallar' },
  { f: 'C6H5ONa', n: 'natriy fenolyat', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kristall', hz: ['korroziv'], diss: { 'Na^+': 1, 'C6H5O^-': 1 }, reagent: false },
  { f: 'C6H2Br3OH', n: '2,4,6-tribromfenol', st: 's', c: 'fenol', col: '#f6f6f0', form: 'kukun', hz: ['zararli'], tex: 'suzmasimon', reagent: false, desc: 'oq cho\'kma' },
  { f: 'C2H5ONa', n: 'natriy etilat', st: 's', c: 'alkogolyat', col: '#f2f0e8', form: 'kukun', hz: ['korroziv', 'yonuvchan'], reagent: false },
  { f: 'CH3ONa', n: 'natriy metilat', st: 's', c: 'alkogolyat', col: '#f2f0e8', form: 'kukun', hz: ['korroziv', 'yonuvchan'], reagent: false },
  { f: 'C2H5OK', n: 'kaliy etilat', st: 's', c: 'alkogolyat', col: '#f2f0e8', form: 'kukun', hz: ['korroziv'], reagent: false },
  { f: 'C3H5(ONa)3', skip: true },
  { f: 'C2H5OC2H5', aliases: ['(C2H5)2O', 'C2H5–O–C2H5'], n: 'dietil efir', st: 'l', c: 'oddiy-efir', d: 0.713, bp: 34.6, hz: ['yonuvchan', 'zararli'], miscible: false, sto: 'qoramtir-sklyanka', desc: 'juda uchuvchan, oson alangalanuvchi suyuqlik' },
  { f: 'CH3OCH3', n: 'dimetil efir', st: 'g', c: 'oddiy-efir', hz: ['yonuvchan'], gas: { ws: 'yaxshi' }, reagent: false },
  { f: 'Cu(C3H7O3)2', n: 'mis(II) glitserat', st: 'aq', c: 'kompleks', hz: [], reagent: false, aq: { col: '#2a3fb8', ref: 0.05 }, desc: 'to\'q ko\'k (ko\'k-binafsha) eritma' },
  { f: 'Cu(C2H5O2)2', n: 'mis(II) etilenglikolyat', st: 'aq', c: 'kompleks', hz: [], reagent: false, aq: { col: '#2a3fb8', ref: 0.05 } },
  { f: 'C6H12O6·Cu', skip: true },
  // aldegid va ketonlar
  { f: 'HCHO', aliases: ['CH2O', 'H–CHO'], n: 'formaldegid (metanal)', st: 'g', c: 'aldegid', hz: ['zaharli', 'kanserogen'], gas: { ws: 'juda-yaxshi', smell: 'o\'tkir hid' }, sol: [[13.3, 'konsentrlangan', 'formalin 40%'], [1.3, 'suyultirilgan', '4%']] },
  { f: 'CH3CHO', aliases: ['CH3–CHO', 'C2H4O'], n: 'atsetaldegid (etanal)', st: 'l', c: 'aldegid', d: 0.784, bp: 20.2, hz: ['yonuvchan', 'zararli'], miscible: true, sto: 'shlif-tiqinli-sklyanka', sol: [[1, 'suyultirilgan', '~5%']], desc: 'chirigan olma hidli uchuvchan suyuqlik' },
  { f: 'CH3CH2CHO', aliases: ['C2H5CHO', 'C2H5–CHO'], n: 'propanal', st: 'l', c: 'aldegid', d: 0.81, bp: 48, hz: ['yonuvchan'], miscible: true, reagent: false },
  { f: 'CH3COCH3', aliases: ['(CH3)2CO', 'CH3–CO–CH3'], n: 'aseton (propanon)', st: 'l', c: 'keton', d: 0.784, bp: 56, hz: ['yonuvchan', 'zararli'], miscible: true, sto: 'tiqinli-sklyanka' },
  { f: 'C6H5CHO', n: 'benzaldegid', st: 'l', c: 'aldegid', d: 1.044, bp: 178.1, hz: ['zararli'], miscible: false, sto: 'qoramtir-sklyanka', desc: 'achchiq bodom hidli suyuqlik' },
  { f: 'CH3CH(OH)CH2CHO', n: '3-gidroksibutanal (aldol)', st: 'l', c: 'aldegid', d: 1.1, hz: ['zararli'], miscible: true, reagent: false },
  { f: 'CH3CH=CHCHO', n: 'kroton aldegid (buten-2-al)', st: 'l', c: 'aldegid', d: 0.85, bp: 104, hz: ['zaharli', 'yonuvchan'], miscible: true, reagent: false },
  { f: 'CHI3', n: 'yodoform', st: 's', c: 'galogenalkan', col: '#f2d23a', form: 'kristall', hz: ['zararli'], tex: 'mayda-kristall', reagent: false, desc: 'o\'ziga xos hidli sariq kristallar' },
  { f: 'CH3CH(OH)CN', n: 'atsetaldegid sianogidrini (laktonitril)', st: 'l', c: 'nitril', hz: ['zaharli'], reagent: false },
  { f: 'CH3CH(OH)SO3Na', n: 'atsetaldegidning gidrosulfitli birikmasi', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kristall', hz: [], tex: 'mayda-kristall', reagent: false },
  { f: '(CH3)2C(OH)SO3Na', n: 'asetonning gidrosulfitli birikmasi', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kristall', hz: [], tex: 'mayda-kristall', reagent: false },
  { f: 'C6H5CH2OH', n: 'benzil spirti', st: 'l', c: 'spirt', d: 1.044, bp: 205, hz: ['zararli'], miscible: false, reagent: false },
  { f: '(CH2)6N4', n: 'urotropin (geksametilentetramin)', st: 's', c: 'amin', col: '#f8f8f6', form: 'kristall', hz: ['yonuvchan'], reagent: false },
  // karbon kislotalar va tuzlari
  { f: 'HCOOH', aliases: ['H–COOH', 'CH2O2'], n: 'chumoli kislota (metan kislota)', st: 'l', c: 'karbon-kislota', d: 1.22, bp: 100.8, hz: ['korroziv'], miscible: true, sto: 'shlif-tiqinli-sklyanka', sol: [[1, 'suyultirilgan', '1 M'], [22, 'konsentrlangan', '85%']] },
  { f: 'CH3COOH', aliases: ['CH3–COOH', 'C2H4O2'], n: 'sirka kislota (etan kislota)', st: 'l', c: 'karbon-kislota', d: 1.049, mp: 16.6, bp: 118, hz: ['korroziv', 'yonuvchan'], miscible: true, sto: 'shlif-tiqinli-sklyanka', sol: [[0.1, 'suyultirilgan', '0,1 M'], [1, 'suyultirilgan', '1 M'], [1.5, 'suyultirilgan', '9% (osh sirkasi)'], [17.4, 'konsentrlangan', 'muz sirka kislota']], desc: 'o\'tkir sirka hidli rangsiz suyuqlik' },
  { f: 'C2H5COOH', aliases: ['CH3CH2COOH'], n: 'propion kislota', st: 'l', c: 'karbon-kislota', d: 0.99, bp: 141, hz: ['korroziv'], miscible: true, sto: 'shlif-tiqinli-sklyanka' },
  { f: 'C3H7COOH', aliases: ['CH3CH2CH2COOH'], n: 'moy kislota (butan kislota)', st: 'l', c: 'karbon-kislota', d: 0.96, bp: 163.5, hz: ['korroziv'], miscible: true, sto: 'shlif-tiqinli-sklyanka', desc: 'yoqimsiz (achigan moy) hidli suyuqlik' },
  { f: 'C17H35COOH', n: 'stearin kislota', st: 's', c: 'karbon-kislota', col: '#f8f8f4', form: 'bo\'lak', d: 0.94, mp: 69.3, hz: [], miscible: false, sto: 'tiqinli-sklyanka', desc: 'oq yog\'simon qattiq modda' },
  { f: 'C17H33COOH', n: 'olein kislota', st: 'l', c: 'karbon-kislota', d: 0.895, mp: 13.4, hz: [], miscible: false, sto: 'tiqinli-sklyanka', desc: 'rangsiz yoki och sariq moysimon suyuqlik' },
  { f: 'C15H31COOH', n: 'palmitin kislota', st: 's', c: 'karbon-kislota', col: '#f8f8f4', form: 'bo\'lak', mp: 62.9, hz: [], miscible: false, reagent: false },
  { f: 'H2C2O4', aliases: ['HOOC–COOH', 'HOOC-COOH', '(COOH)2'], n: 'oksalat kislota (etandi kislota)', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kristall', hz: ['zararli'], sto: 'tiqinli-sklyanka', sol: [[0.05, 'suyultirilgan', '0,05 M'], [0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'H2C2O4·2H2O', n: 'oksalat kislota digidrat', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kristall', hz: ['zararli'], sto: 'tiqinli-sklyanka', diss_mol: { H2C2O4: 1, H2O: 2 }, desc: 'titrlashda boshlang\'ich modda' },
  { f: 'C6H5COOH', n: 'benzoy kislota', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kristall', mp: 122.4, hz: ['zararli'], sto: 'tiqinli-sklyanka', desc: 'oq ignasimon kristallar, sublimatlanadi' },
  { f: 'CH3CH(OH)COOH', aliases: ['C3H6O3', 'CH3–CH(OH)–COOH'], n: 'sut kislota', st: 'l', c: 'karbon-kislota', d: 1.21, hz: ['korroziv'], miscible: true, sto: 'tiqinli-sklyanka' },
  { f: 'C3H5O(COOH)3', aliases: ['C6H8O7'], n: 'limon kislota', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kristall', hz: ['zararli'], sto: 'tiqinli-sklyanka', sol: [[0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'C6H4(OH)COOH', aliases: ['C7H6O3'], n: 'salitsil kislota', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kristall', mp: 159, hz: ['zararli'], sto: 'tiqinli-sklyanka' },
  { f: 'C6H4(OCOCH3)COOH', aliases: ['C9H8O4'], n: 'atsetilsalitsil kislota (aspirin)', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kristall', mp: 135, hz: ['zararli'], sto: 'tiqinli-sklyanka' },
  { f: 'HOOC(CH2)4COOH', aliases: ['C6H10O4'], n: 'adipin kislota', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kristall', mp: 152, hz: ['zararli'], sto: 'tiqinli-sklyanka' },
  { f: 'CH2=C(CH3)COOH', n: 'metakril kislota', st: 'l', c: 'karbon-kislota', d: 1.015, bp: 161, hz: ['korroziv'], miscible: true, reagent: false },
  { f: 'CH2=CHCOOH', n: 'akril kislota', st: 'l', c: 'karbon-kislota', d: 1.05, bp: 141, hz: ['korroziv'], miscible: true, reagent: false },
  { f: 'ClCH2COOH', n: 'xlorsirka kislota', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kristall', hz: ['zaharli', 'korroziv'], reagent: false },
  { f: 'CH3COONa', aliases: ['CH3COO–Na'], n: 'natriy atsetat', custom_skip: true },
  { f: 'HCOONa', n: 'natriy formiat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'Na^+': 1, 'HCOO^-': 1 }, sol: [[0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'HCOOK', n: 'kaliy formiat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'K^+': 1, 'HCOO^-': 1 }, reagent: false },
  { f: '(HCOO)2Ca', aliases: ['Ca(HCOO)2'], n: 'kalsiy formiat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'Ca^2+': 1, 'HCOO^-': 2 }, reagent: false },
  { f: 'C2H5COONa', n: 'natriy propionat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'Na^+': 1, 'C2H5COO^-': 1 }, reagent: false },
  { f: 'C3H7COONa', n: 'natriy butirat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'Na^+': 1, 'C3H7COO^-': 1 }, reagent: false },
  { f: 'C6H5COONa', n: 'natriy benzoat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'Na^+': 1, 'C6H5COO^-': 1 }, sol: [[0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'C6H5COOK', n: 'kaliy benzoat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'K^+': 1, 'C6H5COO^-': 1 }, reagent: false },
  { f: 'C6H5COOAg', n: 'kumush benzoat', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kukun', hz: [], tex: 'mayda-kristall', reagent: false },
  { f: 'C17H35COONa', n: 'natriy stearat (qattiq sovun)', st: 's', c: 'sovun', col: '#f4f0e4', form: 'bo\'lak', hz: [], diss: { 'Na^+': 1, 'C17H35COO^-': 1 }, sol: [[0.05, 'suyultirilgan', 'sovunli suv']], desc: 'sovun; suvda ko\'piklanadi' },
  { f: 'C17H35COOK', n: 'kaliy stearat (suyuq sovun)', st: 's', c: 'sovun', col: '#f2ecd8', form: 'pasta', hz: [], diss: { 'K^+': 1, 'C17H35COO^-': 1 }, reagent: false },
  { f: '(C17H35COO)2Ca', aliases: ['Ca(C17H35COO)2'], n: 'kalsiy stearat', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kukun', hz: [], tex: 'suzmasimon', reagent: false, desc: 'oq parcha-parcha cho\'kma ("qattiq suvda sovun ko\'piklanmaydi")' },
  { f: '(C17H35COO)2Mg', aliases: ['Mg(C17H35COO)2'], n: 'magniy stearat', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kukun', hz: [], tex: 'suzmasimon', reagent: false },
  { f: '(C17H35COO)2Ba', aliases: ['Ba(C17H35COO)2'], n: 'bariy stearat', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kukun', hz: [], tex: 'suzmasimon', reagent: false },
  { f: '(CH3COO)2Cu', skip: true },
  { f: 'C17H33COONa', n: 'natriy oleat', st: 's', c: 'sovun', col: '#f2ecd8', form: 'pasta', hz: [], diss: { 'Na^+': 1, 'C17H33COO^-': 1 }, reagent: false },
  { f: 'CH3CH(OH)COONa', n: 'natriy laktat', st: 'aq', c: 'organik-tuz', hz: [], diss: { 'Na^+': 1, 'CH3CH(OH)COO^-': 1 }, reagent: false },
  { f: 'C3H5O(COONa)3', n: 'natriy sitrat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'Na^+': 3, 'C3H5O(COO)3^3-': 1 }, reagent: false },
  { f: 'C6H4(OH)COONa', n: 'natriy salitsilat', st: 's', c: 'organik-tuz', col: '#f8f8f6', form: 'kristall', hz: [], diss: { 'Na^+': 1, 'C6H4(OH)COO^-': 1 }, reagent: false },
  { f: 'HOOCCOONa', skip: true },
  // murakkab efirlar, yog'lar
  { f: 'CH3COOC2H5', aliases: ['CH3COOCH2CH3', 'C4H8O2'], n: 'etilatsetat', st: 'l', c: 'murakkab-efir', d: 0.902, bp: 77.1, hz: ['yonuvchan', 'zararli'], miscible: false, sto: 'tiqinli-sklyanka', desc: 'meva hidli rangsiz suyuqlik' },
  { f: 'CH3COOCH3', n: 'metilatsetat', st: 'l', c: 'murakkab-efir', d: 0.932, bp: 56.9, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: 'HCOOC2H5', n: 'etilformiat', st: 'l', c: 'murakkab-efir', d: 0.917, bp: 54.3, hz: ['yonuvchan'], miscible: false, reagent: false, desc: 'rom hidli suyuqlik' },
  { f: 'HCOOCH3', n: 'metilformiat', st: 'l', c: 'murakkab-efir', d: 0.97, bp: 31.8, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: 'CH3COOC5H11', n: 'izoamilatsetat', st: 'l', c: 'murakkab-efir', d: 0.876, bp: 142, hz: ['yonuvchan'], miscible: false, reagent: false, desc: 'nok (banan) hidli suyuqlik' },
  { f: 'CH3COOC4H9', n: 'butilatsetat', st: 'l', c: 'murakkab-efir', d: 0.88, bp: 126, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: 'C3H7COOC2H5', n: 'etilbutirat', st: 'l', c: 'murakkab-efir', d: 0.88, bp: 121, hz: ['yonuvchan'], miscible: false, reagent: false, desc: 'ananas hidli suyuqlik' },
  { f: 'C6H4(OH)COOCH3', n: 'metilsalitsilat', st: 'l', c: 'murakkab-efir', d: 1.17, bp: 222, hz: ['zararli'], miscible: false, reagent: false, desc: 'qishyashil (o\'tkir dorivor) hidli suyuqlik' },
  { f: 'C6H5COOC2H5', n: 'etilbenzoat', st: 'l', c: 'murakkab-efir', d: 1.05, bp: 212, hz: [], miscible: false, reagent: false },
  { f: 'CH2=C(CH3)COOCH3', n: 'metilmetakrilat', st: 'l', c: 'murakkab-efir', d: 0.94, bp: 101, hz: ['yonuvchan', 'zararli'], miscible: false, sto: 'qoramtir-sklyanka' },
  { f: '(CH3CO)2O', n: 'sirka angidrid', st: 'l', c: 'angidrid', d: 1.08, bp: 139.8, hz: ['korroziv', 'yonuvchan'], miscible: false, sto: 'shlif-tiqinli-sklyanka' },
  { f: '(C17H35COO)3C3H5', n: 'tristearin (qattiq yog\')', st: 's', c: 'yog\'', col: '#f6f2e0', form: 'bo\'lak', d: 0.86, mp: 72, hz: [], miscible: false, sto: 'tiqinli-sklyanka' },
  { f: '(C17H33COO)3C3H5', n: 'triolein (o\'simlik moyi)', st: 'l', c: 'yog\'', d: 0.91, hz: [], miscible: false, sto: 'tiqinli-sklyanka', col: '#f0d878', desc: 'sariq moysimon suyuqlik (o\'simlik moyining asosiy qismi)' },
  { f: '(C15H31COO)3C3H5', n: 'tripalmitin', st: 's', c: 'yog\'', col: '#f6f2e0', form: 'bo\'lak', hz: [], miscible: false, reagent: false },
  { f: '(C17H33COO)2Ca', skip: true },
  // aminlar, aminokislotalar, oqsillar
  { f: 'CH3NH2', aliases: ['CH3–NH2'], n: 'metilamin', st: 'g', c: 'amin', hz: ['yonuvchan', 'korroziv'], gas: { ws: 'juda-yaxshi', smell: 'ammiak va baliqqa o\'xshash hid' }, sol: [[2, 'suyultirilgan', 'suvdagi eritma']], sto: 'shlif-tiqinli-sklyanka' },
  { f: 'C2H5NH2', aliases: ['CH3CH2NH2', 'CH3–CH2–NH2'], n: 'etilamin', st: 'g', c: 'amin', bp: 16.6, hz: ['yonuvchan', 'korroziv'], gas: { ws: 'juda-yaxshi', smell: 'ammiakka o\'xshash hid' }, sol: [[2, 'suyultirilgan', 'suvdagi eritma']], sto: 'shlif-tiqinli-sklyanka' },
  { f: '(CH3)2NH', n: 'dimetilamin', st: 'g', c: 'amin', hz: ['yonuvchan', 'korroziv'], gas: { ws: 'juda-yaxshi' }, reagent: false },
  { f: 'C6H5NH2', aliases: ['C6H7N'], n: 'anilin (fenilamin)', st: 'l', c: 'amin', d: 1.022, bp: 184.1, hz: ['zaharli', 'atrof-muhit'], miscible: false, sto: 'qoramtir-sklyanka', desc: 'rangsiz moysimon suyuqlik, havoda qo\'ng\'irlashadi' },
  { f: 'C6H5NH3Cl', aliases: ['[C6H5NH3]Cl'], n: 'fenilammoniy xlorid (anilin gidroxloridi)', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kristall', hz: ['zaharli'], diss: { 'C6H5NH3^+': 1, 'Cl^-': 1 }, reagent: false },
  { f: 'CH3NH3Cl', aliases: ['[CH3NH3]Cl'], n: 'metilammoniy xlorid', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kristall', hz: [], diss: { 'CH3NH3^+': 1, 'Cl^-': 1 }, reagent: false },
  { f: 'C2H5NH3Cl', aliases: ['[C2H5NH3]Cl'], n: 'etilammoniy xlorid', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kristall', hz: [], diss: { 'C2H5NH3^+': 1, 'Cl^-': 1 }, reagent: false },
  { f: '(C6H5NH3)2SO4', n: 'fenilammoniy sulfat', st: 's', c: 'organik-tuz', col: '#f6f6f2', form: 'kristall', hz: ['zaharli'], tex: 'mayda-kristall', diss: { 'C6H5NH3^+': 2, 'SO4^2-': 1 }, reagent: false },
  { f: 'C6H2Br3NH2', n: '2,4,6-tribromanilin', st: 's', c: 'amin', col: '#f6f6f0', form: 'kukun', hz: ['zararli'], tex: 'suzmasimon', reagent: false, desc: 'oq cho\'kma' },
  { f: 'H2NCH2COOH', aliases: ['NH2CH2COOH', 'NH2–CH2–COOH', 'H2N–CH2–COOH', 'C2H5NO2'], n: 'glitsin (aminosirka kislota)', st: 's', c: 'aminokislota', col: '#f8f8f6', form: 'kristall', hz: [], sto: 'tiqinli-sklyanka', sol: [[0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'CH3CH(NH2)COOH', aliases: ['CH3–CH(NH2)–COOH', 'C3H7NO2'], n: 'alanin (2-aminopropan kislota)', st: 's', c: 'aminokislota', col: '#f8f8f6', form: 'kristall', hz: [], sto: 'tiqinli-sklyanka', sol: [[0.5, 'suyultirilgan', '0,5 M']] },
  { f: 'H2NCH2COONa', n: 'natriy glitsinat', st: 'aq', c: 'organik-tuz', hz: [], reagent: false },
  { f: '[H3NCH2COOH]Cl', aliases: ['ClH3NCH2COOH'], n: 'glitsin gidroxloridi', st: 'aq', c: 'organik-tuz', hz: [], reagent: false },
  { f: 'H2NCH2CONHCH2COOH', n: 'glitsilglitsin (dipeptid)', st: 's', c: 'peptid', col: '#f8f8f6', form: 'kristall', hz: [], reagent: false },
  { f: 'H2NCH2CONHCH(CH3)COOH', n: 'glitsilalanin (dipeptid)', st: 's', c: 'peptid', col: '#f8f8f6', form: 'kristall', hz: [], reagent: false },
  { f: '(H2NCH2COO)2Cu', aliases: ['Cu(H2NCH2COO)2'], n: 'mis(II) glitsinat', st: 's', c: 'kompleks', col: '#3a6ad0', form: 'kristall', hz: [], aq: { col: '#2a5ad0', ref: 0.05 }, reagent: false, desc: 'to\'q ko\'k ichki kompleks tuz' },
  { f: 'oqsil', formula_null: true, n: 'oqsil eritmasi (tuxum oqi)', st: 'aq', c: 'oqsil', hz: [], sto: 'tiqinli-sklyanka', desc: 'tuxum oqining suvdagi kolloid eritmasi', mixture: true },
  { f: 'jun', formula_null: true, n: 'jun ipi (oqsil tola)', st: 's', c: 'oqsil', hz: [], col: '#e8dcc8', form: 'tola', reagent: true },
  { f: 'C6H5N2Cl', skip: true },
  // uglevodlar
  { f: 'C6H12O6', n: 'glyukoza', st: 's', c: 'uglevod', col: '#f8f8f6', form: 'kristall', hz: [], sto: 'tiqinli-sklyanka', sol: [[0.5, 'suyultirilgan', '~10%']] },
  { f: 'C6H12O6', tag: 'fruktoza', n: 'fruktoza', st: 's', c: 'uglevod', col: '#f8f8f6', form: 'kristall', hz: [], sto: 'tiqinli-sklyanka', sol: [[0.5, 'suyultirilgan', '~10%']] },
  { f: 'C12H22O11', n: 'saxaroza', st: 's', c: 'uglevod', col: '#f8f8f6', form: 'kristall', hz: [], sto: 'tiqinli-sklyanka', sol: [[0.3, 'suyultirilgan', '~10%']] },
  { f: 'C12H22O11', tag: 'maltoza', n: 'maltoza', st: 's', c: 'uglevod', col: '#f8f8f6', form: 'kristall', hz: [], reagent: false },
  { f: 'C12H22O11', tag: 'laktoza', n: 'laktoza', st: 's', c: 'uglevod', col: '#f8f8f6', form: 'kristall', hz: [], reagent: false },
  { f: '(C6H10O5)n', n: 'kraxmal', st: 's', c: 'uglevod', col: '#f8f8f4', form: 'kukun', hz: [], sto: 'tiqinli-sklyanka', sol: [[0.06, 'suyultirilgan', '1% kraxmal eritmasi (kleystr)']] },
  { f: '(C6H10O5)n', tag: 'sellyuloza', n: 'sellyuloza (paxta, filtr qog\'oz)', st: 's', c: 'uglevod', col: '#fafaf6', form: 'tola', hz: [], sto: 'tiqinli-sklyanka' },
  { f: '[C6H7O2(ONO2)3]n', n: 'sellyuloza trinitrati (piroksilin)', st: 's', c: 'uglevod-efir', col: '#fafaf6', form: 'tola', hz: ['yonuvchan', 'portlash-xavfi'], reagent: false },
  { f: '[C6H7O2(OCOCH3)3]n', n: 'sellyuloza triatsetati', st: 's', c: 'uglevod-efir', col: '#fafaf6', form: 'tola', hz: [], reagent: false },
  { f: 'C6H12O7', n: 'glyukon kislota', st: 'aq', c: 'karbon-kislota', hz: [], reagent: false },
  { f: 'C6H14O6', n: 'sorbit', st: 's', c: 'spirt', col: '#f8f8f6', form: 'kristall', hz: [], reagent: false },
  { f: 'C6H11O7NH4', n: 'ammoniy glyukonat', st: 'aq', c: 'organik-tuz', hz: [], reagent: false },
  { f: 'kraxmal-yod', formula_null: true, n: 'kraxmal-yod kompleksi', st: 'aq', c: 'kompleks', hz: [], reagent: false, aq: { col: '#1a1a6a', ref: 0.0005 } },
  { f: 'C12H22O11·Cu', skip: true },
  { f: 'CO(NH2)2', aliases: ['(NH2)2CO', 'H2N–CO–NH2'], n: 'mochevina (karbamid)', st: 's', c: 'amid', col: '#f8f8f6', form: 'kristall', mp: 133, hz: [], sto: 'tiqinli-sklyanka', sol: [[1, 'suyultirilgan', '1 M']] },
  { f: 'H2NCONHCONH2', aliases: ['C2H5N3O2'], n: 'biuret', st: 's', c: 'amid', col: '#f8f8f6', form: 'kristall', hz: [], reagent: false },
  // monomerlar va polimerlar
  { f: '(–CH2–CH2–)n', aliases: ['(C2H4)n', '(CH2CH2)n'], n: 'polietilen', st: 's', c: 'polimer', col: '#f2f2ee', form: 'plyonka', hz: [], sto: 'tiqinli-sklyanka' },
  { f: '(–CH2–CH(CH3)–)n', aliases: ['(C3H6)n'], n: 'polipropilen', st: 's', c: 'polimer', col: '#f2f2ee', form: 'plyonka', hz: [], sto: 'tiqinli-sklyanka' },
  { f: '(–CH2–CHCl–)n', aliases: ['(C2H3Cl)n'], n: 'polivinilxlorid', st: 's', c: 'polimer', col: '#f0f0e8', form: 'plyonka', hz: [], sto: 'tiqinli-sklyanka' },
  { f: '(–CH2–CH(C6H5)–)n', aliases: ['(C8H8)n'], n: 'polistirol', st: 's', c: 'polimer', col: '#f6f6f2', form: 'bo\'lak', hz: [], sto: 'tiqinli-sklyanka' },
  { f: '(–CH2–C(CH3)(COOCH3)–)n', aliases: ['(C5H8O2)n'], n: 'polimetilmetakrilat (organik shisha)', st: 's', c: 'polimer', col: '#f4f8f8', form: 'bo\'lak', hz: [], sto: 'tiqinli-sklyanka' },
  { f: '(–CF2–CF2–)n', n: 'politetraftoretilen (teflon)', st: 's', c: 'polimer', col: '#f6f6f2', form: 'bo\'lak', hz: [], reagent: false },
  { f: '(–CH2–CH=CH–CH2–)n', n: 'polibutadien (butadien kauchugi)', st: 's', c: 'polimer', col: '#2a2a28', form: 'bo\'lak', hz: [], reagent: false },
  { f: '(–CH2–C(CH3)=CH–CH2–)n', n: 'poliizopren (tabiiy kauchuk)', st: 's', c: 'polimer', col: '#c8a878', form: 'bo\'lak', hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'C6H11NO', aliases: ['(CH2)5CONH'], n: 'kaprolaktam', st: 's', c: 'laktam', col: '#f8f8f6', form: 'kristall', mp: 69, hz: ['zararli'], sto: 'tiqinli-sklyanka' },
  { f: '[–NH(CH2)5CO–]n', aliases: ['(C6H11NO)n'], n: 'kapron (polikaproamid)', st: 's', c: 'polimer', col: '#f4f2ea', form: 'tola', hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'H2N(CH2)6NH2', aliases: ['C6H16N2'], n: 'geksametilendiamin', st: 's', c: 'amin', col: '#f8f8f6', form: 'kristall', mp: 41, hz: ['korroziv'], sto: 'tiqinli-sklyanka' },
  { f: '[–OC(CH2)4CONH(CH2)6NH–]n', aliases: ['(C12H22N2O2)n'], n: 'neylon-6,6 (anid)', st: 's', c: 'polimer', col: '#f4f2ea', form: 'tola', hz: [], sto: 'tiqinli-sklyanka' },
  { f: '[–C6H3(OH)–CH2–]n', aliases: ['(C7H6O)n'], n: 'fenol-formaldegid smola', st: 's', c: 'polimer', col: '#b8783a', form: 'bo\'lak', hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'ClC(O)(CH2)4C(O)Cl', n: 'adipoilxlorid', st: 'l', c: 'xlorangidrid', d: 1.26, hz: ['korroziv'], miscible: false, reagent: false },
  { f: '[–OCC6H4COOCH2CH2O–]n', aliases: ['(C10H8O4)n'], n: 'polietilentereftalat (lavsan)', st: 's', c: 'polimer', col: '#f4f4f0', form: 'tola', hz: [], sto: 'tiqinli-sklyanka' },
  { f: 'C6H4(COOH)2', n: 'tereftal kislota', st: 's', c: 'karbon-kislota', col: '#f8f8f6', form: 'kukun', hz: [], reagent: false },
  { f: 'CH3COOCH=CH2', n: 'vinilatsetat', st: 'l', c: 'murakkab-efir', d: 0.93, bp: 72.7, hz: ['yonuvchan'], miscible: false, reagent: false },
  { f: '(–CH2–CH(OCOCH3)–)n', n: 'polivinilatsetat', st: 's', c: 'polimer', col: '#f4f4ee', form: 'bo\'lak', hz: [], reagent: false },
  // indikatorlar va maxsus reaktivlar (aralashmalar va murakkab moddalar)
  { f: 'C20H14O4', n: 'fenolftalein', st: 's', c: 'indikator', col: '#f8f8f6', form: 'kukun', hz: ['kanserogen'], sto: 'tiqinli-sklyanka', indicator: 'fenolftalein', sol: [[0.003, 'suyultirilgan', '0,1% spirtli eritma']] },
  { f: 'C14H14N3NaO3S', n: 'metiloranj', st: 's', c: 'indikator', col: '#e8781a', form: 'kukun', hz: ['zaharli'], sto: 'tiqinli-sklyanka', indicator: 'metiloranj', sol: [[0.003, 'suyultirilgan', '0,1% eritma']] },
  { f: 'lakmus', formula_null: true, n: 'lakmus', st: 'aq', c: 'indikator', hz: [], sto: 'tiqinli-sklyanka', indicator: 'lakmus', mixture: true, desc: 'lishayniklardan olinadigan bo\'yoq aralashmasi' },
  { f: 'universal-indikator', formula_null: true, n: 'universal indikator', st: 'aq', c: 'indikator', hz: ['yonuvchan'], sto: 'tiqinli-sklyanka', indicator: 'universal-indikator', mixture: true },
  { f: 'C27H28Br2O5S', n: 'bromtimol ko\'ki', st: 's', c: 'indikator', col: '#c8a830', form: 'kukun', hz: [], sto: 'tiqinli-sklyanka', indicator: 'bromtimol-kok', sol: [[0.0016, 'suyultirilgan', '0,1% eritma']] },
  { f: 'C20H12N3NaO7S', n: 'erioxrom qora T', st: 's', c: 'indikator', col: '#2a1a2a', form: 'kukun', hz: ['zararli'], sto: 'tiqinli-sklyanka', indicator: 'erioxrom-qora-T', sol: [[0.002, 'suyultirilgan', 'NaCl bilan quruq aralashma']] },
  { f: 'Lugol', formula_null: true, n: 'Lugol eritmasi (yodning KI dagi eritmasi)', st: 'aq', c: 'reaktiv', hz: ['zararli'], sto: 'qoramtir-sklyanka', mixture: { I2: 0.05, 'K^+': 0.12, 'I^-': 0.12 } },
  { f: 'bromli-suv', formula_null: true, n: 'bromli suv', st: 'aq', c: 'reaktiv', hz: ['zaharli', 'korroziv'], sto: 'qoramtir-sklyanka', mixture: { Br2: 0.02 } },
  { f: 'xlorli-suv', formula_null: true, n: 'xlorli suv', st: 'aq', c: 'reaktiv', hz: ['zaharli', 'oksidlovchi'], sto: 'qoramtir-sklyanka', mixture: { Cl2: 0.05 } },
  { f: 'yodli-suv', formula_null: true, n: 'yodli suv', st: 'aq', c: 'reaktiv', hz: ['zararli'], sto: 'qoramtir-sklyanka', mixture: { I2: 0.001 } },
  { f: 'ohakli-suv', formula_null: true, n: 'ohakli suv (Ca(OH)₂ ning to\'yingan eritmasi)', st: 'aq', c: 'reaktiv', hz: ['korroziv'], sto: 'rezina-tiqinli-sklyanka', mixture: { 'Ca^2+': 0.02, 'OH^-': 0.04 } },
  { f: 'barit-suvi', formula_null: true, n: 'barit suvi (Ba(OH)₂ eritmasi)', st: 'aq', c: 'reaktiv', hz: ['zaharli', 'korroziv'], sto: 'rezina-tiqinli-sklyanka', mixture: { 'Ba^2+': 0.2, 'OH^-': 0.4 } },
  { f: 'Tollens', formula_null: true, n: 'Tollens reaktivi (kumush oksidning ammiakli eritmasi)', st: 'aq', c: 'reaktiv', hz: ['korroziv'], sto: 'yangi-tayyorlanadi', mixture: { '[Ag(NH3)2]^+': 0.1, 'OH^-': 0.1, NH3: 0.1 } },
  { f: 'Feling', formula_null: true, n: 'Feling suyuqligi', st: 'aq', c: 'reaktiv', hz: ['korroziv'], sto: 'yangi-tayyorlanadi', mixture: { 'Cu(OH)2': 0.07, 'Na^+': 1.0, 'OH^-': 1.0 }, mixture_phase: { 'Cu(OH)2': 'aq' }, aq: { col: '#2a4ad0', ref: 0.07 }, desc: 'mis(II) sulfat va segnet tuzining ishqoriy aralashmasi (to\'q ko\'k)' },
  { f: 'Nessler', formula_null: true, n: 'Nessler reaktivi (K₂[HgI₄] ning ishqoriy eritmasi)', st: 'aq', c: 'reaktiv', hz: ['zaharli', 'korroziv', 'atrof-muhit'], sto: 'qoramtir-sklyanka', mixture: { 'K^+': 0.4, '[HgI4]^2-': 0.1, 'OH^-': 0.2 } },
  { f: 'C4H8N2O2', n: 'dimetilglioksim (Chugayev reaktivi)', st: 's', c: 'reaktiv', col: '#f8f8f6', form: 'kukun', hz: ['zararli'], sto: 'tiqinli-sklyanka', sol: [[0.08, 'suyultirilgan', '1% spirtli eritma']] },
  { f: 'C10H14N2Na2O8·2H2O', n: 'Trilon B (EDTA ning dinatriyli tuzi)', st: 's', c: 'reaktiv', col: '#f8f8f6', form: 'kristall', hz: ['zararli'], sto: 'tiqinli-sklyanka', diss: { 'Na^+': 2, 'C10H14N2O8^2-': 1, H2O: 2 }, sol: [[0.05, 'suyultirilgan', '0,05 M'], [0.01, 'suyultirilgan', '0,01 M']] },
  { f: 'universal-qogoz', formula_null: true, n: 'universal indikator qog\'ozi', st: 's', c: 'indikator', hz: [], indicator: 'universal-indikator', reagent: false, paper: true },
  { f: 'C8H10N4O2', skip: true },
];

export const EXTRA_IONS_FOR_EDTA = [
  { f: 'AlOH^2+', name: 'gidroksoalyuminiy' },
  { f: 'FeOH^2+', name: 'gidroksotemir(III)', color: { hex: '#d9a03a', ref_M: 0.1 } },
  { f: 'CuOH^+', name: 'gidroksomis(II)' },
  { f: 'ZnOH^+', name: 'gidroksorux' },
  { f: 'C10H14N2O8^2-', name: 'digidroetilendiamintetraatsetat (H₂Y²⁻)' },
  { f: '[CaC10H12N2O8]^2-', name: 'kalsiy-EDTA kompleksi (CaY²⁻)' },
  { f: '[MgC10H12N2O8]^2-', name: 'magniy-EDTA kompleksi (MgY²⁻)' },
  { f: '[ZnC10H12N2O8]^2-', name: 'rux-EDTA kompleksi (ZnY²⁻)' },
  { f: 'S4O6^2-', name: 'tetrationat' },
  { f: 'C17H33COO^-', name: 'oleat' },
  { f: 'C6H5NH3^+', name: 'fenilammoniy' },
  { f: 'CH3NH3^+', name: 'metilammoniy' },
  { f: 'C2H5NH3^+', name: 'etilammoniy' },
  { f: 'Cr^2+', name: 'xrom(II)', color: { hex: '#4a7ad0', ref_M: 0.2 } },
  { f: 'HSiO3^-', name: 'gidrosilikat' },
  { f: 'HCrO4^-', name: 'gidroxromat' },
  { f: 'Hg2^2+', name: 'simob(I)' },
];
